cilium/cilium-cli

connectivity/check/features.go
connectivity/check/policy.go
connectivity/manifests/echo-ingress-auth-fail.yaml
connectivity/manifests/echo-ingress-mtls.yaml
connectivity/suite.go

This adds tests to validate that the auth handling in policy is working. It uses  the always-fail type to test the fail case. If mTLS-SPIFFE is enabled in the cluster it will also perfom a successful test run with mTLS enabled.
The auth-fail tests will be able to run against `master` of cilium, the mTLS tests can be enabled in installation once https://github.com/cilium/cilium/pull/24765 is merged

Add connectivity tests for auth

---

CODEOWNERS
bgp/bgp.go
bgp/peers.go
bgp/peers_test.go
internal/cli/cmd/bgp.go
internal/cli/cmd/cmd.go
vendor/github.com/stretchr/testify/require/doc.go
vendor/github.com/stretchr/testify/require/forward_requirements.go
vendor/github.com/stretchr/testify/require/require.go
vendor/github.com/stretchr/testify/require/require.go.tmpl
vendor/github.com/stretchr/testify/require/require_forward.go
vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
vendor/github.com/stretchr/testify/require/requirements.go
vendor/modules.txt

This change introduces new BGP status CLI : `cilium bgp peers`.  Status of BGP peers is returned from all or specific node in json or summary formats. 
```
./cilium bgp peers --help
Gets BGP peering status from all nodes in the cluster
Usage:
cilium bgp peers [flags]
Flags:
--agent-pod-selector string   Label on cilium-agent pods to select with (default "k8s-app=cilium")
-h, --help                        help for peers
--node string                 Node from which BGP status will be fetched, omit to select all nodes
-o, --output string               Output format. One of: json, summary (default "summary")
--wait-duration duration      Maximum time to wait for result, default 1 minute (default 1m0s)
```
Signed-off-by: harsimran pabla <hpabla@isovalent.com>

BGP: Introduce new cli to get bgp peering state

---

.github/workflows/aks-azure-ipam.yaml
.github/workflows/aks-byocni.yaml
.github/workflows/eks-tunnel.yaml
.github/workflows/eks.yaml
.github/workflows/externalworkloads.yaml
.github/workflows/gke.yaml
.github/workflows/go.yaml
.github/workflows/images.yaml
.github/workflows/multicluster.yaml
.golangci.yml
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
RELEASE.md
internal/cli/cmd/version.go

In order to merge this PR, we will need to rename the default branch in the GitHub UI first.
Fixes #1518

Rename master branch to main

---

.github/workflows/mirror.yaml

there should be a grace period for developers relying on the 'master' branch to catch up and switch to relying on 'main'. During that grace period, this action will clone all pushes to 'main' into the 'master' branch.
For #1518

.github: add mirror from main -> master

---

hubble/hubble.go

Deprecated Cilium Helm Chart values have been removed in the PR https://github.com/cilium/cilium/pull/24214 - [this change](https://github.com/cilium/cilium/pull/24214/files#diff-48ba11928b3e5bd05ddae3774b1f2c228f54699b357603ac3bfc72ee846a93f0) specifically.
Installing Cilium (`cilium install --chart-directory install/kubernetes/cilium`) & enabling hubble (`cilium hubble enable --chart-directory install/kubernetes/cilium`) will break the connectivity from the hubble relay to the peer service (`Failed to create peer client for peers synchronization...`).
This will consequently also fail the connectivity tests with the following error: `Timeout waiting for flow listener to become ready`.
We need to set `tls.ca.cert` & `tls.ca.key` during `cilium hubble enable` to use the same CA cert. …

cli: adapt helm chart cleanup of deprecated hubble values

---

defaults/defaults.go

which includes the new /client-ip route [1] to echo back the client IP in the response and will be used in a subsequent commit
[1] https://github.com/cilium/json-mock/releases/tag/v1.3.5

defaults: bump json-mock to 1.3.5

---

README.md

There is no guarantee that the release date is accurate, since the release might not get tagged the same day the release pull request gets created.
Let's just remove the column. We link to release pages that contain the actual timestamps of when they got tagged.

Remove "Release Date" column from the release table

---

install/helm.go

This commit fixes versioncheck so that it includes patch versions of cilium 1.13.x. Versions 1.13.x triggers en error:
level=fatal msg="Wireguard (--enable-wireguard) is not compatible with L7 proxy (--enable-l7-proxy)" subsys=daemon
Fixes: 64924bfa9663 ("enabled l7Proxy & removed err.log message for WireGuard")

fixes versioncheck for l7 proxy disabling with wireguard encryption

---

connectivity/check/policy.go

This commit adds some retry logic to the policy revision retrieval in case of a timeout. Such timeouts can happen because of simple connectivity blips.
This piece of code has been identified as fairly critical [1]. We attempt to retrieve these policy revisions when applying and deleting policies. If we fail to retrieve the policy revision, we fail the whole policy deletion. That can lead to failures in subsequent tests because of the leftover policy.
1 - https://github.com/cilium/cilium-cli/issues/1260
Fixes: https://github.com/cilium/cilium-cli/issues/1260.

connectivity: Retry getting the policy revision

---

defaults/defaults.go
install/uninstall.go
internal/cli/cmd/install.go

When running Helm in the CI setup i came against the limit that a cleanup of the tests namespace took longer than the Helm default of 5 minutes. However the timeout option was not exposed in out options thus could not be changed.
This PR exposes the `--timeout` helm option on uninstall when running in Helm mode.

Allow the Helm timeout to be set on uninstall

---

.github/in-cluster-test-scripts/multicluster.sh
.github/workflows/multicluster.yaml
clustermesh/clustermesh.go
internal/cli/cmd/clustermesh.go
internal/helm/helm.go
internal/helm/helm_test.go

Two commits for review
Implements a version of `clustermesh enable` and `clustermesh disable` using Helm actions run directly against the cluster
Enables a workflow matrix for "classic" and "helm" mode for multicluster tests using GKE. The recently added parameter for cilium_cli_mode in the `cilium-cli-test-job-chart` is used.

helm mode: add clustermesh enable/disable

---

sysdump/sysdump.go

Writing the sysdump to an absolute path doesn't work because we always append the current directory to the output filename:
$ ./cilium sysdump --output-filename /tmp/cilium-sysdump
[...]
✅ The sysdump has been saved to /home/paul/cilium-cli/tmp/cilium-sysdump.zip
Let's remove the code that does that.
Fixes: 77a1f2389 ("sysdump: initial sysdump implementation")

sysdump: Fix writing to absolute path

---

connectivity/check/action.go

When running the connectivity tests in AKS, we sometimes get interrupted commands that don't have any output [1]. Unfortunately, those commands then exit without any error and are therefore considered successful. We think this is caused by connectivity blips between Kubernetes components.
This commit adds a check for those inconclusive results. If we see a seemingly successful command with no output, we retry it until we get something conclusive. This works because all our test commands (curl, ping, nslookup) dump something to stdout.
1 - https://github.com/cilium/cilium/issues/22162

connectivity: Retry on inconclusive results

---

.github/workflows/go.yaml
Makefile
clustermesh/certs.go
cmd/internal/add-image-digests/main.go
connectivity/check/action.go
connectivity/check/context.go
connectivity/check/deployment.go
connectivity/check/features.go
connectivity/check/peer.go
connectivity/filters/filters.go
connectivity/tests/dummy.go
hubble/hubble.go
hubble/ui.go
install/autodetect.go
install/azure.go
install/certs.go
install/gke.go
install/install.go
install/kind.go
install/minikube.go
install/upgrade.go
internal/certs/certs.go
internal/cli/cmd/hubble.go
internal/logging/logging.go
internal/utils/exec_test.go
k8s/client.go
status/k8s_test.go
sysdump/sysdump.go
sysdump/sysdump_test.go

This PR updates golangci-lint to version 1.52.2
In addition, newly detected issues (mostly unused parameters) have been fixed.

build: update golangci-lint to version 1.52.2

---

.github/kind-config-1.yaml
.github/kind-config-2.yaml
.github/workflows/kind.yaml

Add a GitHub Actions Workflow for Clustermesh via Helm implementation of `cilium upgrade`
We can use the new upgrade command to enable Cluster Mesh on a set of two Cilium clusters with the following procedure.
Create a kind cluster with the following config
```bash
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: c1
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker
networking:
disableDefaultCNI: true
podSubnet: "10.10.0.0/16"
serviceSubnet: "10.50.0.0/16"
```
```
kind create cluster --config c1.kindconfig.yaml
```
Test that the kind cluster came up with `k get pods -A`
Install Cilium using the CLI, making sure to set a Cluster ID and Cluster Name
```bash
export CILIUM_CLI_MODE=helm
cilium install --help
cilium install --helm-set cluster.id=1 --helm-set …
```

helm mode: add workflow for clustermesh via upgrade

---

action.yaml

To reduce the boilerplate in cilium/cilium/.github/workflows.
$ cd cilium/.github
$ git grep 'Install Cilium CLI' | wc -l
39
Test run https://github.com/cilium/cilium/pull/25228.

Add GHA to install Cilium CLI executable

---

defaults/defaults.go
install/install.go
internal/cli/cmd/install.go
internal/helm/helm.go
internal/helm/helm_test.go

Add --repository flag in helm mode install / upgrade commands to override
the default https://helm.cilium.io repository.
I intentionally avoided adding this flag to the classic mode since it's
being deprecated in the next minor release (v0.15). The behavior of the
classic mode is unchanged in this pull request.

helm mode: Make Helm chart repository configurable

---

connectivity/manifests/echo-ingress-l7-http-from-anywhere.yaml
connectivity/suite.go

This test case covers https://github.com/cilium/cilium/issues/21954. 
A new policy `echo-ingress-l7-policy-from-anywhere` is added to allow HTTP GET / on echo pods from outside.
Use `cilium connectivity test --test north-south-loadbalancing --datapath` to run this test.
Signed-off-by: Zhichuan Liang <gray.isovalent.com>

connectivity: test accessing NodePort from outside with L7 policy

---

internal/utils/utils.go
internal/utils/utils_test.go

ParseCiliumVersion uses versioncheck.Version from Cilium's versioncheck
package ([1]), which ignores certain pre-release identifiers. Silently
ignoring certain pre-release identifiers can be confusing since you
might end up installing a different version of Cilium than what you
specified.
This commit replaces versioncheck.Version with semver.ParseTolerant ([2])
in ParseCiliumVersion function so that cilium-cli interprets the version
provided via the --version flag as is.
[1]: https://pkg.go.dev/github.com/cilium/cilium/pkg/versioncheck#Version
[2]: https://pkg.go.dev/github.com/blang/semver#ParseTolerant

Replace versioncheck.Version with semver.ParseTolerant

---

connectivity/check/check.go
connectivity/suite.go
connectivity/tests/common.go
connectivity/tests/to-cidr.go
connectivity/tests/world.go
defaults/defaults.go
internal/cli/cmd/connectivity.go

Adds --retry and --retry-delay flags to the connectivity test.
They are used in external `pod-to-world` and `po-to-cidr` tests to try to reconnect
on failures thus making flaky tests less likely.

connectivity: add retry to external targets

---

connectivity/manifests/client-egress-to-echo-service-account-deny.yaml
connectivity/manifests/client-egress-to-echo-service-account.yaml
connectivity/manifests/client-with-service-account-egress-to-echo-deny.yaml
connectivity/manifests/client-with-service-account-egress-to-echo.yaml
connectivity/suite.go

Please refer to individual commit for more details.

connectivity: Add tests for Service Account related rules

---

connectivity/check/action.go

Before:
📄 No flows recorded during action external-1111-0
📄 No flows recorded during action external-1111-0
After:
📄 No flows recorded for peer cilium-test/client-7b78db77d5-6x9vj during action external-1111-0
📄 No flows recorded for peer external-1111 during action external-1111-0

connectivity: report peer name in "no flows recorded" log message

---

README.md
internal/helm/helm.go

Tweak newChartFromRemoteWithCache() to support OCI repos:
- chartRef must be the full OCI repository path.
- RepoURL must be empty.
- RegistryClient must be initialized.

Handle OCI repositories

---

.github/workflows/kind.yaml
connectivity/check/context.go
connectivity/check/deployment.go
connectivity/check/features.go
connectivity/check/policy.go
connectivity/check/test.go
connectivity/manifests/egress-gateway-policy.yaml
connectivity/suite.go
connectivity/tests/egressgateway.go
k8s/client.go

This PR adds a first basic egress gateway test.
Given the cegp-sample CiliumEgressGatewayPolicy targeting:
- a couple of client pods (kind=client) as source
- the 0.0.0.0/0 destination CIDR
- kind-worker2 as gateway node
the test simply ensures that traffic from both clients reaches the echo-external service with the egress IP of the gateway node

connectivity: add basic egress gateway test

---

connectivity/check/features.go
connectivity/suite.go

disable:
* client-ingress-knp
* echo-ingress-knp
* client-egress-knp
* client-egress-expression-knp
as the tests are currently failing with this configuration.
Issue tracked in https://github.com/cilium/cilium-cli/issues/1585.
test run on Cilium main branch: https://github.com/cilium/cilium/actions/runs/4914096880/jobs/8775022204?pr=25194

suite: disable KNP tests when endpoint routes and IPv6 are enabled

---

connectivity/tests/service.go

Enable these test cases as https://github.com/cilium/cilium/issues/23461 has been resolved.
Signed-off-by: Zhichuan Liang <gray.liang@isovalent.com>

connectivity: enable outside to nodeport via IPv6 when IPsec is enabled

---

connectivity/check/test.go

We recently added the KNP tests, so we need to check for those too. Previously, we checked only for CNPs.
Otherwise, all KNP tests will fail for IPv6 connections among endpoints running on the same host.
Fixes: 33883604 ("connectivity: Add IPv6 tests")

connectivity: Fix IPv6 skipping when EP routes are on

---

connectivity/suite.go

This reverts commit d2bac228703a0ce7d2dfc789420b6d2e8b76f500, superseded by https://github.com/cilium/cilium-cli/pull/1587

Revert "suite: disable KNP tests when endpoint routes and IPv6 are enabled"

---

clustermesh/certs.go
clustermesh/clustermesh.go
defaults/defaults.go

Previously, we had logic to look for deprecated names like `clustermesh-apiserver-client-certs` when `clustermesh-apiserver-client-cert` was expected. With helm-based installations, we now need to look for `clustermesh-apiserver-client-cert` when `clustermesh-apiserver-remote-cert` is expected.
This implements that concpet recursively, looking for the "even more deprecated" name for secrets if applicable.
Two example runs that exercise the logic:
Using one level of deprecated names to find the secret
```
✅ ClusterMesh enabled!
Trying to get secret clustermesh-apiserver-remote-cert by deprecated name clustermesh-apiserver-client-cert
⚠️ Deprecated secret name "clustermesh-apiserver-client-cert", should be changed to "clustermesh-apiserver-remote-cert"
⚠️  Service type NodePort detected! …
```

helm mode: add additional deprecated secret logic, and fix `clustermesh connect` for helm mode

---

.github/workflows/aks-byocni.yaml

The AKS BYOCNI workflow has been timing out quite often since being re-enabled. This is mainly due to the additional tests that were added since the workflow was disabled ~5 months ago. Follow commit 13ae2fa3dcee ("gha: Increase timeout for GKE") which increased timeouts for the GKE workflow in a similar fashion and bump the timeout by 15min.
See https://github.com/cilium/cilium-cli/actions/runs/4916363553/jobs/8780012198 for a recent timeout.

.github/workflows: bump AKS BYOCNI workflow timeout

---

.github/renovate.json5

Fixes: 930832e59ffe ("Add renovate configuration")
Fixes: #1592

renovate: fix invalid JSON syntax

---

.github/renovate.json5
.github/workflows/aks-byocni.yaml
.github/workflows/eks-tunnel.yaml
.github/workflows/eks.yaml
.github/workflows/externalworkloads.yaml
.github/workflows/gke.yaml
.github/workflows/go.yaml
.github/workflows/images.yaml
.github/workflows/kind.yaml
.github/workflows/loki.yaml
.github/workflows/multicluster.yaml
.github/workflows/release.yaml

Renovate currently tries to update these dependencies in the go.mod replace section. However, these should only be updated when they are updated in upstream github.com/cilium/cilium. Exclude them from renovate updates.
Also add GH action version annotations. This is needed so that renovate will follow action version tags while still using digest pinning, see https://docs.renovatebot.com/modules/manager/github-actions/
See commits for details.

renovate configuration follow-ups

---

install/helm.go
install/install.go
install/node_init.go
install/uninstall.go

Recent changes to helm charts make nodeinit not necessary on EKS, let's enable it only on older versions.
Don't merge it until https://github.com/cilium/cilium/pull/24134 is backported and released (version check might require changes)

Don't enable nodeinit on EKS when not needed

---

.github/in-cluster-test-scripts/aks-byocni-install.sh
install/autodetect.go
install/azure.go

I assert that az-binary check is a bit too excessive since it's not always required to have az binary installed when you are installing Cilium on AKS.
Instead of forcing users to specify `--disable-check=az-binary` flag, let's just fail if az binary is needed but not found. This behavior is consistent with how we handle gcloud binary.

Remove az-binary check

---

internal/cli/cmd/clustermesh.go
internal/cli/cmd/cmd.go
internal/cli/cmd/hubble.go
internal/utils/utils.go
internal/utils/utils_test.go

There are multiple places where we check if the CLI is in Helm mode. Add a function utils.IsInHelmMode() so that this logic is in a single place.

Add a function to check if the CLI is in Helm mode

---

.github/workflows/kind.yaml

Follow commit b13b994e7535 (".github/workflows: add GH action version annotations") and also add the version annotations to the workflow steps added by commit eefbd2840e9b ("connectivity test: add junit output"). This is needed so that renovate will follow action version tags while still using digest pinning, see https://docs.renovatebot.com/modules/manager/github-actions/

.github/workflows: add missing GH action version annotations

---

internal/utils/utils_test.go

Fixes: 840b570e4515 ("Add a function to check if the CLI is in Helm mode")

unit test: Restore the original env variable using defer

---

.github/in-cluster-test-scripts/aks-byocni-install.sh
.github/workflows/aks-byocni.yaml
connectivity/check/action.go

Fixes: #1566
ended up adding an extra commit to make waitForRelay() more robust: https://github.com/cilium/cilium-cli/pull/1578/commits/e2e7202b3437c4b164f4e0f67d3468b40be40066 cc @cilium/sig-hubble 

Add helm mode test coverage for AKS BYOCNI

---

install/uninstall.go

Without this change, a helm-installed Cilium uninstall will print
Error parsing Cilium Version: Invalid character(s) found in major number "v1"
failing to autodetect the current Cilium version

uninstall: allow ciliumVersion to start with "v"

---

README.md

Add a section to describe that "cilium upgrade" can be used to downgrade to a previous version similar to "helm upgrade"
Fixes: #1558

helm mode: Clarify upgrade command

---

.github/in-cluster-test-scripts/eks.sh
.github/workflows/eks.yaml
install/install.go
install/install_test.go

helm mode: Add EKS test coverage

---

cli/cmd.go
cmd/cilium/main.go
connectivity/check/context.go
connectivity/check/test.go
connectivity/manifests/template/template.go
connectivity/suite.go
internal/cli/cmd/cmd.go
internal/cli/cmd/connectivity.go
internal/cli/cmd/hooks.go
internal/cli/cmd/sysdump.go

This allows building a version of cilium-cli externally with extended connectivity tests and sysdump tasks.

Add hooks to use cilium-cli as a package

---

sysdump/sysdump.go

Redacting sensitive info is error prone. For example, there was a bug that recently got fixed in #1631 where the cilium-cli wasn't redacting fields in last-applied-configuration.
The purpose of this check is to indicate whether cilium-etcd-secrets exists, so let's just do that without actually storing the secret in sysdump. With this change, there will be a line in cilium-sysdump.log.
If the secret exists:
% grep cilium-etcd-secrets cilium-sysdump.log
🔍 Checking if cilium-etcd-secrets exists in kube-system namespace
Secret "cilium-etcd-secrets" found in namespace "kube-system"
If the secret does not exist:
% grep cilium-etcd-secrets cilium-sysdump.log
🔍 Checking if cilium-etcd-secrets exists in kube-system namespace
Secret "cilium-etcd-secrets" not found in namespace "kube-system" - this …

sysdump: Don't save cilium-etcd-secrets

---

connectivity/check/test.go
connectivity/tests/service.go

https://github.com/cilium/cilium/issues/21954 for the IPv6 path was resolved only for v1.14, but not for v1.13. In order to be able to run the latest connectivity tests on v1.13, we need to skip curl requests to the IPv6 addresses in that particular test.
Fixes: #1627
Signed-off-by: Zhichuan Liang <gray.isovalent.com>

connectivity: Skip IPv6 requests in north-south-loadbalancing-with-l7-policy when running on < 1.14.0 Cilium

---

.github/in-cluster-test-scripts/external-workloads-install.sh
.github/workflows/externalworkloads.yaml
clustermesh/certs.go
clustermesh/clustermesh.go
internal/cli/cmd/clustermesh.go

helm mode: Add external workloads test coverage

---

.github/workflows/externalworkloads.yaml
.github/workflows/gke.yaml
.github/workflows/multicluster.yaml

The `cilium`, and `cilium-cli` use the same GCP project for provisioning GKE clusters.
If the number of simultaneously provisioned clusters is high enough we get an error like below,
```
The network "default" does not have available private IP space in 10.0.0.0/9 to reserve a /14 block for pods for cluster {Zone=us-west2-a, ProjectNum=185287498374, ProjectName=*** ....
```
With current defaults, which are below, the number of clusters that can be provisioned simultaneously is around 31.
- subnetwork (used by nodes) : /22 
- pod cidr :  /14
- service cidr : /20
The current default network ranges are too big for our use cases, per cluster only 2 nodes are provisioned.
The max pods created is 29, and the max services created is 9 
In accordance with network range requirements, the changes …

ci: fix gke network starvation

---

README.md
defaults/defaults.go
internal/cli/cmd/sysdump.go
status/k8s.go
status/status.go
sysdump/constants.go
sysdump/defaults.go
sysdump/sysdump.go

https://github.com/cilium/cilium/pull/25081 adds support for deploying Cilium's L7 Proxy (Envoy) to be deployed in its own DaemonSet instead of running it in the same container as the Cilium Agent. Currently, it needs to be explicitly enabled via helm value `envoy.enabled=true`
This PR adds support for the new Envoy DaemonSet in the Cilium CLI.
* Status
* SysDump Log collection
* SysDump DaemonSet & ConfigMap collection
Installation works out of the box with the newly introduced helm CLI mode :tada: 
Classic mode isn't supported for the time being and needs to be discussed.

Support for dedicated Cilium Envoy DaemonSet

---

.github/workflows/kind.yaml
connectivity/check/action.go
connectivity/check/logging.go
connectivity/check/metrics.go
connectivity/check/metrics_test.go
connectivity/check/metricssource.go
connectivity/check/metricssource_test.go
connectivity/check/peer.go
connectivity/check/policy.go
connectivity/check/result.go
connectivity/check/result_test.go
connectivity/suite.go
connectivity/tests/client.go
connectivity/tests/host.go
connectivity/tests/pod.go
connectivity/tests/service.go
connectivity/tests/world.go
go.mod
k8s/dialer.go
vendor/k8s.io/client-go/tools/portforward/doc.go
vendor/k8s.io/client-go/tools/portforward/portforward.go
vendor/modules.txt

Add the possibility to verify metrics from the Cilium agent pod and validate it has the expected behaviour before and after an action. 
- [commit 1](https://github.com/cilium/cilium-cli/pull/1575/commits/36277d8e22cc18328b8422eb2ac91939aa89e451) Add a k8s dialer to be able to port forward `/metrics` endpoint outside of the pod
- [commit 2](https://github.com/cilium/cilium-cli/pull/1575/commits/8d5197c451fd056e345337a3d775ee059f2d8a75) Add the logic to call `/metrics` endpoint and parse the metrics to retrieve them into a nice usable open metrics format
- [commit 3](https://github.com/cilium/cilium-cli/pull/1575/commits/86526acefae7242d946281b0719f1fa494cb3fc5) `policy.go` is a pretty long file now, let's move `Result` with its associated methods in its own file.
- [commit …

Add Prometheus metrics validation

---

Makefile
cli/cmd.go
internal/cli/cmd/cmd.go
internal/cli/cmd/connectivity.go
internal/cli/cmd/install.go
internal/cli/cmd/sysdump.go
internal/cli/cmd/version.go

When building an extended version of cilium-cli with hooks, it is not possible to set Version var with -ldflags because it is located in an internal package.
This commit exports the Version var in the cli package to allow setting it both here and in the extended cilium-cli binaries.

cli: Export Version var to be set externally

---

connectivity/check/peer.go

change the Address method to return an IP address when available (i.e. when ClusterIP is not empty, which happens in case of headless services) instead of just returning the service name.
towards: https://github.com/cilium/cilium/issues/24151

check: make (Service)Address() return an IP address

---

connectivity/check/features.go

make the feature detection logic compatible with the new flag introduced in v1.14 in [1]
[1] https://github.com/cilium/cilium/pull/24561
Towards: https://github.com/cilium/cilium/issues/24151

check: update tunneling detection logic

---

.github/workflows/kind.yaml
connectivity/check/action.go
connectivity/check/check.go
connectivity/check/context.go
connectivity/check/deployment.go
connectivity/check/features.go
connectivity/check/peer.go
connectivity/check/test.go
connectivity/manifests/echo-ingress-from-cidr.yaml
connectivity/suite.go
connectivity/tests/service.go
internal/cli/cmd/connectivity.go

This PR introduces a few changes:
1. Moves IP routes (pod CIDR => node on nodes w/o Cilium) installation to the CLI.
2. Removes `--datapath`, and introduces `--include-unsafe-tests`. The formal removal required a few changes to the flow validation and skipping some tests to make it pass on some GHA workflows.
Please review it per commit.
Successful run - https://github.com/cilium/cilium/pull/25510.

connectivity: Automatically install IP routes on nodes w/o Cilium for from CIDR tests AND get rid of --datapath

---

install/upgrade.go

release is nil if helm.Upgrade() failed.

upgrade: Check for error before accessing release

---

k8s/client.go
sysdump/client.go
sysdump/constants.go
sysdump/sysdump.go
sysdump/sysdump_test.go

This adds all GatewayAPI objects to the sysdump as well as the IngressClass object. This will be helpful for troubleshooting GatewayAPI related issues.
The objects are dumped into YAML if available prefixed with gatewayapi- for ease of use.
Fixes https://github.com/cilium/cilium-cli/issues/1567

Add GatewayAPI resources to sysdump

---

Makefile

This is currently not covered by renovate. Let's bump it manually for now and also add the correct SHA while at it.

Makefile: bump Go to v1.20.4 for release target

---

.github/workflows/kind.yaml
connectivity/check/check.go
connectivity/check/context.go
internal/cli/cmd/connectivity.go

These changes add a new key=value flag `--junit-property`
Provided key value pairs will be added to the generated junit file.
Properties will be required to distinguish junit test names in `cilium` connectivity test reporting.
The new flag is added to the kind test.

connectivity: add property flag for junit

---

README.md
RELEASE.md

Also update the release instructions to bump the version in RELEASE.md, such that we can copy-paste `export RELEASE=v...` next time ;-)

Prepare for v0.14.4 release

---

.github/renovate.json5

When renovate opens a PR, it will keep updating the dependencies as long as the PR is open. This makes it difficult have a green CI run since some dependencies are being updated frequently and we aren't able to merge the PR. Thus, add this label to prevent renovate from updating PRs after opening them.
Same as https://github.com/cilium/cilium/pull/25649

renovate: add renovate/stop-updating label on renovate's PRs

---

connectivity/check/metrics.go
connectivity/check/metrics_test.go
connectivity/check/result.go

To avoid copying this potentially large type and also work around the following erroneous govet warning:
> copylocks: metricsIncrease passes lock by value: github.com/prometheus/client_model/go.MetricFamily contains google.golang.org/protobuf/internal/impl.MessageState contains sync.Mutex (govet)
Ref. https://github.com/cilium/cilium-cli/actions/runs/5087191687?pr=1661

connectivity/check: pass metrics to metricsIncrease by pointer

---

sysdump/constants.go
sysdump/defaults.go
sysdump/sysdump.go

Let submitTetragonBugtoolTasks take these values as parameters rather than from global vars. This e.g. allows to override them based on command line options in a future change.

sysdump: refactor submitTetragonBugtoolTasks to take defaults as parameters

---

.github/renovate.json5
defaults/defaults.go

Use renovate to keep the images used in connectivity tests up to date.
Fixes #1565
Example PRs:
https://github.com/tklauser/cilium-cli/pull/5
https://github.com/tklauser/cilium-cli/pull/6
https://github.com/tklauser/cilium-cli/pull/7

renovate: add annotations for connectivity test images

---

Makefile

This fixes the following error reported in #1599
> Renovate failed to look up the following dependencies: Could not
> determine new digest for update (datasource: docker).
> Files affected: Makefile

Makefile: fix golangci-lint renovate datasource annotation

---

connectivity/check/context.go
connectivity/check/peer.go
connectivity/check/policy.go
connectivity/check/test.go
connectivity/manifests/egress-gateway-policy-excluded-cidrs.yaml
connectivity/manifests/egress-gateway-policy.yaml
connectivity/suite.go
connectivity/tests/egressgateway.go
k8s/client.go

see individual commits
Towards: https://github.com/cilium/cilium/issues/24151

connectivity: add full egress gateway test suite

---

connectivity/check/test.go
install/autodetect.go
install/install.go
internal/cli/cmd/install.go

Various connectivity and install fixes

---

connectivity/check/metrics_test.go

Avoid the following erroneous govet warning:
> copylocks: literal copies lock value from ciliumForwardCountTotalBefore: github.com/prometheus/client_model/go.MetricFamily contains google.golang.org/protobuf/internal/impl.MessageState contains sync.Mutex (govet)
Ref. https://github.com/cilium/cilium-cli/pull/1661/files#annotation_11568423750

connectivity/check: store metrics by pointer in TestMetricsIncrease

---

.github/workflows/multicluster.yaml

The multicluster test set up two clusters in blocking mode sequentially. Every cluster provisioning takes 4 to 5 min.
This commit changes provisioning to none blocking mode and adds a step to wait for provisioning to finish.
This change would cut the run time by 4 to 5 min.
The [link](https://github.com/cilium/cilium-cli/actions/runs/5133451203) to the run, one failed and successful
but both of the installation steps are successful, which is what counts here.

CI: Change multicluster provisioning to none blocking mode

---

.github/workflows/kind.yaml

Currently, JUnit reports are uploaded with different names
This causes 5 different zip archives in the run history.
This commit makes all the files uploaded under the same archive file
There are changes to report names so that will follow the same naming as the Cilium repository when Junit reporting will be added to it.

CI: Simplify Junit uploads

---

.github/in-cluster-test-scripts/multicluster.sh

As of https://github.com/cilium/cilium-cli/pull/1551, the clustermesh connect subcommand looks for all three possible names for the clustermesh-apiserver client certificate in the local cluster. 
This removes the logic needed by the GKE-based CI workflow prior to that change.

multicluster tests: simplify secret rename logic

---

install/install.go
install/uninstall.go

2 commits for helm mode:
- for `uninstall`, cilium-cli does not need to know the running cilium version since it simply runs `helm uninstall`.
- for `install`, `--version` specifies the Helm chart version. cilium-cli succeeds or fails depending on whether the specified version either exists or it doesn't. there is no need to perform additional version format check.

Do not call utils.CheckVersion() in Helm mode

---

internal/helm/helm.go
status/k8s.go
status/status.go

Print Helm chart version as a part of the "cilium status" output.

status: Print Helm chart version in Helm mode

---

.github/workflows/aks-byocni.yaml
.github/workflows/eks-tunnel.yaml
.github/workflows/eks.yaml
.github/workflows/externalworkloads.yaml
.github/workflows/gke.yaml
.github/workflows/multicluster.yaml

Sometimes resources cleanup for CI tests might fail (due to the different reasons).
Then user won't be able to retry a pipeline till Custodian drops the provisioned resources.
Current PR adds pipeline retry counter to the resource names to avoid conflicts.

Make CI test resources unique for retries.

---

k8s/client.go

Modify GetRunningCiliumVersion in Helm mode to return Helm chart version so that the function properly returns the running Cilium version in Helm mode without relying on image tags.

Helm mode: Use Helm chart version as running version

---

clustermesh/clustermesh.go
internal/cli/cmd/clustermesh.go
internal/helm/helm.go

Add an implementation for `clustermesh connect` using Helm.
Like the classic mode implementation, we autodetect the `clustermesh-apiserver` IPs and port numbers in order to write the `endpoints:` configuration. However, rather than generate the certificates in-process, we rely on the `cronJob` (certgen) mode of the Helm chart to generate (and re-generate) all of the ClusterMesh related certs.
As a first pass, we support the same set of flags as the classic mode.
A second pass PR will include all `--helm-*` flags, which will allow the use of `extraDnsNames` for the purpose of Service resolvability, and the use of other PKI modes.
Fixes: #1620

helm mode: add implementation for clustermesh connect

---

defaults/defaults.go
install/helm.go

This to make sure that Cilium Operator will not be scheduled to the node having label io.cilium/no-schedule:true

install: Add node affinity for Operator

---

.github/workflows/externalworkloads.yaml

External workloads CI was broken due to GKE name limit of up to 40 characters.
Example of successful GKE provisioning: https://github.com/cilium/cilium-cli/actions/runs/5212662316/jobs/9406570993?pr=1709.

External workloads CI fixed.

---

k8s/client.go
sysdump/client.go
sysdump/defaults.go
sysdump/sysdump.go
sysdump/sysdump_test.go

Recently, tetragon added namespaced tracing policies (TracingPolicyNamespaced). Collect this as well.
Tested manually on a kind cluster.

sysdump: gather tetragon namespaced policies

---

install/azure.go
install/azure_test.go

Read Azure resource group name from azure.resourceGroup Helm value so that azureRetrieveAKSClusterInfo() doesn't fail in Helm mode.
need this for https://github.com/cilium/cilium/issues/25156

helm mode: Handle azure.resourceGroup Helm value

---

connectivity/check/check.go
connectivity/check/context.go
connectivity/check/deployment.go
connectivity/suite.go
connectivity/tests/upgrade.go
internal/cli/cmd/connectivity.go

Please see each individual commit msg when reviewing.
Testing in https://github.com/cilium/cilium/pull/25790 (red builds can be ignored, as they are due to Cilium issues which the upgrade tests have caught).
Related https://github.com/cilium/cilium/issues/25037.

connectivity: Add upgrade tests

---

sysdump/sysdump.go

Currently, we incorrectly dump CiliumBGPPeeringPolicy for CiliumLoadBalancerIPPools dump. Fix it.
```
$ cat ciliumloadbalancerippools-20230331-074532.yaml
apiVersion: cilium.io/v2alpha1
items:
- apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
...
```

sysdump: Fix wrong CiliumLoadBalancerIPPools collector

---

k8s/client.go
sysdump/client.go
sysdump/constants.go
sysdump/sysdump.go
sysdump/sysdump_test.go

The CiliumPodIPPool resource was introduced in https://github.com/cilium/cilium/pull/25824 and
is used to define pod IP pools in the multi-pool IPAM mode. See https://github.com/cilium/cilium/issues/24764 for more information.
Updates cilium/cilium#25470

sysdump: collect CiliumPodIPPools

---

defaults/defaults.go
internal/cli/cmd/sysdump.go
k8s/client.go
sysdump/client.go
sysdump/constants.go
sysdump/defaults.go
sysdump/sysdump.go
sysdump/sysdump_test.go

This PR adds resources & logs of the Cilium SPIRE installation (mutual authentication) to the Cilium CLI SysDump.
* Logs of agent & server
* DaemonSet of agent
* StatefulSet of server
* ConfigMaps of agent & server
By default, SPIRE gets installed into the namespace `cilium-spire` during the installation of Cilium. Therefore, it was necessary to add an additional "namespace detection". The detection defaults to the Cilium namespace in case of a failure.

sysdump: collect resources & logs of Cilium SPIRE installation

---

clustermesh/clustermesh.go
internal/cli/cmd/clustermesh.go

This PR extends the `cilium clustermesh enable` command with a new flag which can be used to enable kvstoremesh (cilium/cilium#26083). The new flag is supported only when using the new Helm mode, and requires cilium >= 1.14 (it has no effect on earlier versions). Related: https://github.com/cilium/cilium/pull/26348

clustermesh enable: add enable-kvstoremesh flag

---

connectivity/check/policy.go

Previously, we always waited for the r+1 revision, which in the case of multiple policies being applied may result in a race condition where some, but not all, of the policies are in place prior to proceeding with tests.

while applying policies, wait for all expected policy revisions.

---

connectivity/suite.go
connectivity/tests/errors.go

connectivity: Add checks for agent error logs and drops due to missed tail calls

---

internal/cli/cmd/install.go
internal/cli/cmd/install_test.go

Normalize the following --helm-* flags so that you can specify these flags with or without the "helm-" prefix:
* --helm-set: Normalize to --set.
* --helm-set-file: Normalize to --set-file.
* --helm-set-string: Normalize to --set-string.
* --helm-values: Normalize to --values, and add -f shorthand flag.
Fixes: #1701

install: Normalize --helm-* flags

---

internal/cli/cmd/install.go

Here are a few minor fixes for some error messages from the CLI, in particular on uninstall when trying to disable Hubble.
- internal/cli/cmd: Add line breaks after error messages
- internal/cli/cmd: Fix error displayed on failure to disable Hubble

Minor fixes for error messages on failure to disable Hubble

---

.github/workflows/kind.yaml

The pkill invocation in the kind workflow is meant to kill background tasks started earlier in the workflow. It seems like some of them exit of their own accord, with tests still passing.
Ignore the pkill error code 1 which indicates that no processes were matched / signalled:
1      No processes matched or none of them could be signalled.
Ref. https://github.com/cilium/cilium/issues/26075

.github/workflows: don't error out if pkill finds no processes

---

connectivity/check/deployment.go
connectivity/tests/upgrade.go

* The repo was renamed to cilium/test-connection-disruption.
* The executables were renamed.
* The client stores a file which can be used for probing client readiness.
The changes PR: https://github.com/cilium/test-connection-disruption/pull/2

connectivity: Address migrate-svc changes

---

.gitignore
clustermesh/clustermesh.go
clustermesh/clustermesh_test.go
internal/cli/cmd/clustermesh.go

- Surface new command to match cluster disconnect when CLI helm mode in enabled
Signed-off-by: Fernand Galiana <fernand.galiana@isovalent.com>

Add Helm Clustermesh disconnect command

---

.github/renovate.json5
.github/workflows/aks-byocni.yaml
.github/workflows/eks-tunnel.yaml
.github/workflows/eks.yaml
.github/workflows/externalworkloads.yaml
.github/workflows/gke.yaml
.github/workflows/kind.yaml
.github/workflows/multicluster.yaml
defaults/defaults.go

Let renovate update the Cilium version which is installed by default and used in GH actions workflows. This avoid creating these update PRs manually, see e.g. https://github.com/cilium/cilium-cli/pull/1686
Example PR bumping to Cilium v1.13.4: https://github.com/tklauser/cilium-cli/pull/16

renovate: let renovate update default Cilium version

---

action.yaml

This PR extends the 'install-cilium-cli' composite workflow to additionally support building the cilium CLI from source if the corresponding repository is available locally.

GHA: extend 'install-cilium-cli' to build from source

---

connectivity/check/context.go
connectivity/check/delete.go
connectivity/check/deployment.go
connectivity/check/features.go
connectivity/check/test.go

Expose Features on ConnectivityTest structure.

connectivity: Expose Features on ConnectivityTest

---

defaults/defaults.go

Update alpine-curl to v1.7.0, version is retrieved from[ this workflow](https://github.com/cilium/alpine-curl/actions/runs/5378553798/jobs/9758619474).

defaults: update connectivity test alpine curl image version

---

connectivity/check/check.go
connectivity/check/deployment.go
connectivity/check/logging.go
connectivity/check/wait.go

Please refer to the individual commit messages for additional details.

connectivity tests: wait functions improvements and refactoring

---

connectivity/check/deployment.go

It was observed on a Kind cluster, that during Cilium upgrade (v1.13.4 -> main) kubelet set the taint node.kubernetes.io/network-unavailable which evicted test-conn-disrupt pods. This resulted in a false negative in the upgrade tests.
Fix the issue by tolerating any taint.

connectivity: Add op=Exists toleration for test-conn-disrupt

---

install/azure.go

In Helm mode, the flag `--azure-resource-group` was removed. However, we currently suggest it as a possible fix for various invocations against an AKS cluster. This change suggests only the Helm value in Helm mode.

helm mode: don't suggest removed Azure flag

---

.github/workflows/kind.yaml
install/autodetect.go
install/autodetect_test.go
install/install.go

- Refactor preinstall to call HelmOpts.MergeValues() once at the top of
the function, and pass the merged values to autodetectAndValidate().
- Set install.Parameters.ClusterName to cluster.name Helm value if it's
not empty.
- Skip the cluster name validation altogether in Helm mode. I boldly
assert that any input validation must be performed inside the Helm
chart, and not in cilium-cli. This ensures that the validation logic
is consistent between "helm install" and "cilium install".
Fixes: #490

Helm mode: Handle "cluster.name" Helm value

---

connectivity/check/deployment.go
connectivity/check/features.go
connectivity/check/wait.go

0dccab2ea3f1 ("connectivity: wait for service propagation in agents") introduced an additional check to wait until all test services have been synchronized by cilium agents before starting the actual tests. Yet, this check will never succeed if the cluster is configured in dual stack mode, but only one IP family is enabled by Cilium. Indeed, the backends for the disabled IP family will never be populated. Hence, let's skip this check if the ClusterIP belongs to a disabled IP family.
Fixes: 0dccab2ea3f1 ("connectivity: wait for service propagation in agents")
Reported-by: Donia Chaiehloudj

connectivity: don't wait for service backends if the IP family is disabled

---

clustermesh/clustermesh.go
hubble/hubble.go
internal/cli/cmd/install.go
k8s/client.go
status/k8s.go

Sharing the same RESTClientGetter between Helm client and direct Kubernetes API calls causes "concurrent map read and map write" fatal error as reported in #1794. Introduce a dedicated RESTClientGetter for Helm client so that you don't have to worry about synchronizing access to the same RESTClientGetter. No sharing, no concurrent map read and map write. Problem solved.
Fixes: #1794

Create a separate RESTClientGetter for Helm client

---

connectivity/check/test.go

As https://github.com/cilium/cilium/issues/23852 and https://github.com/cilium/cilium/issues/23910 has been resolved, we can enable IPv6 test for per-endpoint routing.
Signed-off-by: Zhichuan Liang <gray.liang@isovalent.com>

connectivity: enable IPv6 test for per-endpoint routing

---

connectivity/tests/errors.go

I was overly naive to ignore level=errors exceptions. So far we hit only failedToListCRDs \[1\]. Let's add it as an exception.
\[1\]: https://github.com/cilium/cilium/issues/26591
Reported-by: Sebastian Wicki <sebastian@isovalent.com>

connectivity: Ignore failedToListCRDs error

---

connectivity/check/deployment.go

Unfortunately, the op=Exists toleration (127d9b8c2d) made the upgrade pods to be scheduled on nodes which do not run Cilium.
The upgrade issue got resolved by setting "cni.uninstall=false", so let's remove the toleration.

connectivity: Remove test-conn-disrupt tolerations

---

.github/workflows/eks-tunnel.yaml
.github/workflows/eks.yaml

This is fix for the below error in pipeline:
```
Error: unable to describe cluster control plane: operation error EKS: DescribeCluster, https response error StatusCode: 404, RequestID: 007b2aae-2936-44cb-9cbf-4958dd3df8c2, ResourceNotFoundException: No cluster found for name: cilium-cilium-cli-5505927612-1-classic.
```
Successful runs: https://github.com/cilium/cilium-cli/actions/runs/5510195812/jobs/10044035655?pr=1817
**The latest CI EKS related tests failed which is expected due to the issue with `eksctls` tool.**

Eksctl version pinned.

---

action.yaml

This PR modifies the install-cilium-cli action to respect the specified destination path also when it is relative. Additionally, the binary is now built in a temporary directory to mimic the behavior of the other steps, and prevent possible name clashes.

GHA: fix 'install-cilium-cli' issue when building from source

---

k8s/client.go
k8s/tables.go

This change fixes a bug which caused clusters with more than 500 pods to fail pod summary step.
The code assumed that if result.Infos had more than one element, the k8s request returned more than 1 resource type which is not correct for a table.
The result specifies pods as a resource type, so the assumption was wrong. Multiple Infos objects resulted from client dividing requests into chunks, as specified by RequestChunksOf function on request builder.
The change merges all Info objects into one table and returns it.
fixes: https://github.com/cilium/cilium-cli/issues/905

Fix pod summary for large numbers of pods

---

sysdump/sysdump.go

If Cilium is not installed, the namespace of Cilium and Cilium operator cannot be detected. This means that, unless those two parameters are set by the user, the sysdump command will return an error. This means that sysdump cannot be used in Tetragon installations where Cilium is not installed.
This patch changes the code to split the tasks cilium and tetragon tasks, and disable the cilium tasks instead of erring out when the namesapce cannot be autodetected.

sysdump: do not fail if cilium is not installed

---

cli/cmd.go
connectivity/check/action.go
connectivity/check/context.go
connectivity/check/peer.go
connectivity/suite.go
internal/cli/cmd/connectivity.go
internal/cli/cmd/hooks.go

- In order to extend the possibility to setup and initialise for extended functionalities, a new hook is needed `SetupAndValidate`. 
- Create a method on service (like for pod) NameWithoutNamespace() to remove the namespace prefix. It will enable to make call to the domain easily.
- Realised that an error log was not properly formatted, just fixing it (not related to the PR).

hooks: Add new hook SetupAndValidate()

---

connectivity/check/test.go

This commit partly reverts 6c20d0da12 by adding the exclusion check for < v1.14. The EP issue for v6 was resolved only in >= v1.14.0
The successful run on v1.13 - https://github.com/cilium/cilium/actions/runs/5574065263/jobs/10182228218. I'm going to fix the failed 9th job in [a separate PR](https://github.com/cilium/cilium/pull/26856).
#agony-of-cli-cilium-repo-split

Partly revert "connectivity: enable IPv6 test fort per-endpoint routing"

---

.github/external-targets/certs.yaml
.github/external-targets/nginx.yaml
.github/kind-config.yaml
.github/workflows/kind.yaml
connectivity/check/check.go
connectivity/manifests/client-egress-l7-tls.yaml
connectivity/suite.go
connectivity/tests/errors.go
internal/cli/cmd/connectivity.go

3 commits:
- add `--external-target-ca-{name,namespace}` flags to override CA bundle secret for client-egress-l7-tls tests.
- add an error log exception for "Unable to find identity of previously used CIDR" message for cilium version <1.14. see https://github.com/cilium/cilium/issues/26881 for details.
- set up external targets inside the cluster for the kind workflow.

kind: Configure external targets inside the cluster

---

connectivity/check/check.go
connectivity/check/deployment.go
connectivity/suite.go
connectivity/tests/ipsec_xfrm.go
connectivity/tests/upgrade.go
internal/cli/cmd/connectivity.go

This PR extends upgrade test, so IPsec key rotation interruption test can base on the same workflow.
The expected test flow is:
1. Run "cilium-cli connectivity test --conn-disrupt-test-setup --include-conn-disrupt-test" to deploy connectivity sensitive pods, then record the current restart counts and xfrm error counts.
2. Perform IPsec key rotation. This part can be done in the cilium's ci-e2e.
3. Run "cilium-cli connectivity test --include-conn-disrupt-test" to check restart counts and xfrm error counts again, test fails if any diff is found.
Partially Fixes: https://github.com/cilium/cilium/issues/26350
Signed-off-by: Zhichuan Liang <gray.liang@isovalent.com>

Extend upgrade test for IPsec key rotation test

---

connectivity/tests/ipsec_xfrm.go

Previously, it was failing with:
[-] Scenario [no-ipsec-xfrm-errors/no-ipsec-xfrm-error]
No cilium pods found
Fixes: e656f5873 ("connectivity: add xfrm error check for IPsec conn disrupt test")

connectivity: Fix fetching of XFRM counters

---

connectivity/check/action.go
connectivity/check/action_test.go

When running the connectivity tests in AKS, we sometimes get interrupted commands that don't have any output [1]. Therefore, successful command terminations with an empty output are treated as inconclusive that result in a retry [2].
Unfortunately, the ping command might get stuck by only outputting its header line to the output.
`PING 10.0.0.1 (10.0.0.1) 56(84) bytes of data.`
This commit adds an additional check for the ping commands. If we see an output only containing the header, we treat it as inconclusive result.
1 - cilium/cilium#22162
2 - cilium/cilium-cli#1543

connectivity: Special inconclusive result treatment for ping command

---

internal/cli/cmd/install.go

Since `--helm-set` is an alias of `--set` and only `--set` is listed in help, it would be confusing when example still use
```
cilium install --context kind-cluster1 --helm-set cluster.id=1 --helm-set cluster.name=cluster1
```
Instead we should use set as follows
```
cilium install --context kind-cluster1 --set cluster.id=1 --set cluster.name=cluster1
```
This way, users can easily find the correct flag in the `--help` command.

fix(cli-example): optimize the example of the 'install' command line.

---

internal/cli/cmd/connectivity.go

The flag can break all connections.
Suggested-by: Paul Chaignon <paul@cilium.io>

connectivity: Hide --flush-ct

---

connectivity/check/action.go
connectivity/check/metrics.go
connectivity/check/result.go
connectivity/check/result_test.go

When a cluster is freshly deployed and no traffic was observed, certain metrics does not appear yet.  This commit intents to set to 0 the counters of the MetricFamily if the metric was not present.
Testing on a fresh cluster:
No metrics at the beginning, set to 0:
```
2023/07/25 10:45:42 [WARNING] metric xxx was not found before the action was run
2023/07/25 10:45:42 [WARNING] metric xxx counters was set to 0
```
Finally checked the metrics properly:
```
🐛 Forwarding from [::1]:60476 -> 9967
🐛 Handling connection for 60476
🐛 checked metrics properly on node kind-worker
🐛 Finalizing Test external-cilium-dns-proxy
🐛 Pod kube-system/cilium-dzmnb's current policy revision: 2
🐛 Pod kube-system/cilium-wmvfn's current policy revision: 2
ℹ️  📜 Deleting CiliumNetworkPolicy …
```

metrics: Set first retrieved metrics to 0 if absent

---

connectivity/tests/errors.go

Add "removing identity not added to the identity manager!" to the error log exception until https://github.com/cilium/cilium/issues/16419 is fixed.

Update the error log exceptions

---

clustermesh/clustermesh.go
clustermesh/clustermesh_test.go
internal/cli/cmd/clustermesh.go
internal/utils/utils.go
status/k8s.go

This PR includes a set of improvements for the `cilium clustermesh status` command, to simplify troubleshooting and reduce CI flakiness:
* Always check the readiness of the clustermesh-apiserver deployment.
* Report a node as not ready also when the configuration has not yet been detected (as the secret modification has not propagated yet).
* Report explicit errors about why a node is not ready, based on the additional information introduced in https://github.com/cilium/cilium/pull/26788 (e.g., etcd connection, cluster configuration retrieval, data synchronization).
* Remove duplicate checks and fix inaccuracies in output messages.
Please refer to the individual commit messages for additional information.
Fixes: https://github.com/cilium/cilium-cli/issues/1773
~~I'm currently marking this …

Improve the clustermesh status command

---

install/autodetect.go

Fixes #1871 
Helm validates capital letters during name check of clusters. Extended the same for cilium cli.

fix: Changed regex to include capital letters.

---

.github/renovate.json5

v0.0.0-20230801115018-d63ba01acd4b causes this complilation error:
Error: vendor/github.com/cilium/cilium/pkg/hive/cell/health.go:194:23:
type func(a Status, b Status) bool of func(a, b Status) bool {…} does not match inferred
type func(a Status, b Status) int for func(a E, b E) int
Ref: https://github.com/cilium/cilium-cli/actions/runs/5732604742/job/15535855918?pr=1873

renovate: Don't update golang.org/x/exp

---

.golangci.yml
Dockerfile
Makefile

Renovate didn't catch these updates in commit 307aa320d53f ("chore(deps): update dependency go to v1.21.0"), update them to Go 1.21 manually. Also bump the release build to use alpine 3.18 while at it.
Fixes: 307aa320d53f ("chore(deps): update dependency go to v1.21.0")

Update missing dependencies to Go 1.21

---

connectivity/check/features.go
connectivity/tests/encryption.go

This PR extends the node-to-node encryption tests. Before no actions would fail when running them with encryption disabled (Before https://github.com/cilium/cilium/pull/26712 it was 1/3, because the tunneling feature wasn't correctly detected) in one of my environments (WireGuard, tunnel, vxlan, endpointRoutes). I've adapted them so they work with native routing and tunneling with WireGuard (as far as I could test it), i.e. all actions fail when encryption is disabled and succeed if it is enabled.
The first two commits are just some minor cleanup and documentation in the feature detection. Feedback regarding the detection preference comment is especially welcome.
Output before:
```
[=] Test [node-to-node-encryption]
[-] Scenario [node-to-node-encryption/node-to-node-encryption]
🐛 Detected …
```

connectivity: extend node to node encryption tests

---

internal/cli/cmd/sysdump.go
k8s/client.go
sysdump/client.go
sysdump/constants.go
sysdump/defaults.go
sysdump/sysdump.go
sysdump/sysdump_test.go
vendor/helm.sh/helm/v3/pkg/cli/output/output.go
vendor/modules.txt

include the helm get values in the sysdump collecting, and it will try to grab the user provide value and write to a file. when users provides a sysdump file, we don't have to ask the user to submit a separate helm value file. 
in this implementation, we just grab the latest value and user provide values for cilium. in the future, there can be more enhancement for this.
1. we can provide more options to collect previous version or the rendered helm values for everything.
btw, this is my first golang/OSS PR. feel free to let me know what I can do to make this better

implement helm get values with sysdump

---

install/autodetect.go
install/helm.go
install/install.go
install/upgrade.go
internal/cli/cmd/install.go

The `--kube-proxy-replacement` flag has been marked as deprecated for a while in favor of `--helm-set kubeProxyReplacement=<value>`. It's no longer used in cilium/cilium or cilium/cilium-cli CI. Remove the flag and get rid of some incomplete KPR mode auto-detection.

install: remove deprecated kube-proxy-replacement CLI flag

---

connectivity/check/context.go
connectivity/check/features.go
connectivity/check/features_test.go
connectivity/check/test.go

I wanted to re-run a specific Test for reproducing a CI failure, but was surprised to see the test wouldn't run despite targeting it explicitly with --test. The test in question being north-south-loadbalancing, has a feature constraint that was not met in my environment. Thus began the printf rabbit hole.
This patch introduces skip reasons included in brackets after each skipped Test or Scenario. Currently, only one reason is shown, but care was taken to pick the most surprising reason for a skip. For example, excluding all tests by means of `--test "!.*"` would still display feature or version constraints despite the obvious test exclusion.
Some example output (using '--test no-policies/pod-to-world'):
```
[=] Test [no-policies]
[-] Skipping Scenario [no-policies/pod-to-cidr] (skipped by …
```

connectivity: display reason for skipping Tests and Scenarios

---

connectivity/check/check.go
connectivity/check/context.go
connectivity/check/deployment.go
connectivity/tests/service.go
internal/cli/cmd/connectivity.go

First, this commit introduces "--secondary-network-iface" flag. The flag is used to determine a secondary network IP addr of each node.
Second, the commit extends the NodePort from outside tests. When the aforementioned flag is set, in addition to the regular curl request, the test case sends HTTP requests to an IP addr on each Cilium node which is set to the "--secondary-network-face".
Testing PR https://github.com/cilium/cilium/pull/27738 (https://github.com/cilium/cilium/actions/runs/6010840377/job/16303159003)
cc @julianwiedmann @borkmann

connectivity: Add secondary network NodePort tests

---

connectivity/tests/service.go

Instead of make + copy. This should silence the linter's false positive.

connectivity: Use slices.Clone

---

clustermesh/clustermesh.go

Currently, when the Cilium agent running on a VM joins an existing cluster, it automatically infers the corresponding ClusterID and ClusterName. Yet, this introduces a dependency order, because all consumers of that field need to be initialized after the connection to the remote cluster, which is especially problematic as more components get converted to cells. Additionally, this may also lead to possible user confusion, as the corresponding parameter is reported as not initialized in the logs.
Instead, let's explicitly configure these fields in the installation script, so that the Cilium agent can interpret them normally.

Explicitly configure ClusterID/Name in external workloads script

---

k8s/client.go
sysdump/client.go
sysdump/constants.go
sysdump/sysdump.go
sysdump/sysdump_test.go

Fixes https://github.com/cilium/cilium-cli/issues/1923
As mentioned in the issue above, this is not ideal as there might be many k8s-apiserver instances, also behind LB, but at least it will give us some insights into the k8s control plane health.

Scrape Kubernetes metrics in sysdump

---

connectivity/check/context.go
connectivity/check/deployment.go

In the CI upgrade tests we sometimes see the following:
The failure connectivity test failed: timeout reached waiting for
deployment cilium-test/test-conn-disrupt-client to become ready
(last error: only 3 of 5 replicas are available)
@jschwinger233 pointed out that it might be related to "--flush-ct", because according to some output of "kubectl get po", the test-conn-disrupt client pods crashed at the end of last connectivity test, when the "--flush-ct" took place.
Tested with https://github.com/cilium/cilium/pull/27966

connectivity: Delete test-conn-disrupt pods after running tests

---

connectivity/check/check.go
connectivity/check/deployment.go
internal/cli/cmd/connectivity.go

Expose the test-conn-disrupt --dispatch-interval via --conn-disrupt-dispatch-interval.
Suggested-by: Michi Mutsuzaki <michi@isovalent.com>

connectivity: Expose test-conn-disrupt dispatch period

---

connectivity/check/check.go
connectivity/check/deployment.go
internal/cli/cmd/connectivity.go

It's more commonplace to use DurationVar to specify duration CLI flags and gives users more flexibility.
Example usage:
$ cilium connectivity test --conn-disrupt-dispatch-interval 20ms
Fixes: 67b8025b4d43 ("connectivity: Expose test-conn-disrupt dispatch period")

connectivity: convert conn-disrupt-dispatch-interval to duration

---

clustermesh/clustermesh.go
internal/cli/cmd/clustermesh.go

Add a `--service-annotation` argument so that custom annotations can be added to the Kubernetes Service when clustermesh is being enabled.  
A use case for this flag is to create a private NLB in AWS instead of a public classic LB:
> cilium clustermesh enable --service-type LoadBalancer --service-annotation 'service.beta.kubernetes.io/aws-load-balancer-internal=0.0.0.0/0' --service-annotation 'service.beta.kubernetes.io/aws-load-balancer-type=nlb'

clustermesh: Add support for kubernetes service annotations

---

Makefile

This will print just the version, no Go version or other information not relevant for the version check.
Ref. https://github.com/cilium/cilium/pull/28162

make: use short golangci-lint version format when comparing versions

---

connectivity/check/test.go

in order to allow hooks to use it

check: export label prefixes constants

---

connectivity/check/check.go
connectivity/check/context.go
connectivity/check/features.go
connectivity/manifests/client-egress-to-cidr-node-knp.yaml
connectivity/suite.go
internal/cli/cmd/connectivity.go

We now support selecting cluster nodes in policy by CIDR. Previously, only the `remote-node` and `host` entities could select nodes. So, add a corresponding feature and test case for this.
This required adding a function to autodetect node CIDRs.

connectivity: test referencing nodes by CIDR

---

connectivity/check/context.go
connectivity/check/deployment.go
connectivity/check/features.go

- Remove nodesWithoutCilium list as it is redundant, and rename nodesWithoutCiliumMap to nodesWithoutCilium.
- Initialize both nodes and nodesWithoutCilium in getNodes to avoid listing nodes twice.
- Associate extractFeaturesFromNodes with FeatureSet instead of ConnectivityTest to decouple FeatureSet from ConnectivityTest.
Ref: #1962

Clean up the node feature detection logic

---

connectivity/check/features.go
connectivity/check/features_test.go

- Move the code to get the Cilium ConfigMap out of the loop to avoid
getting it multiple times.
- Associate extractFeaturesFromConfigMap with FeatureSet instead of
ConnectivityTest.
- Add unit tests.
Ref: #1962

Refactor extractFeaturesFromConfigMap

---

.golangci.yml
clustermesh/clustermesh_test.go
connectivity/check/action_test.go
connectivity/check/secrets.go
connectivity/check/test_test.go
connectivity/tests/dummy.go
connectivity/tests/health.go
install/helm.go
internal/helm/helm.go

To make sure all Go files have a proper copyright header. Also add the copyright header to files where it was previously missing.
Ref. https://github.com/cilium/cilium-cli/pull/1986/files#r1337029656

golangci-lint: enable goheader check

---

sysdump/sysdump.go
sysdump/sysdump_test.go

Get Cilium pods and cilium-config ConfigMap once at the beginning to reduce the number of Kubernetes API calls.
Ref: #1962

sysdump: Cache Cilium pods and cilium-config ConfigMap

---

clustermesh/clustermesh.go
install/helm.go
install/install.go

The tunnel option is deprecated and will be removed in Cilium v1.15. This commit fixes the remaining uses I have found where the Cilium CLI still set the old `tunnel` flag unconditionally, which will lead to issues once the flag is no longer accepted [1]. The Cilium CLI now only uses the deprecated `tunnel` flag for Cilium versions 1.13 and older.
When reading the ConfigMap (such as in the clustermesh code), we attempt to first parse the new values, before falling back on the old ones.
[1] https://github.com/cilium/cilium/pull/27841#issuecomment-1707275681

install: Avoid using deprecated "tunnel" flag

---

internal/cli/cmd/sysdump.go
sysdump/defaults.go

Specify default label selectors for log collection tasks to avoid collecting logs from all the pods in a given namespace.
Fixes: f88a976e ("sysdump: collect SPIRE agent and server Pod logs")
Fixes: ebaf4fbd ("sysdump: Collect node init Pod logs and DaemonSet")

sysdump: Specify default selectors for log collection tasks

---

clustermesh/clustermesh.go

Use the 'cilium' binary from a Cilium container to copy into
/usr/bin/cilium and /usr/bin/cilium-dbg so that this script will be
compatible with newer CI workflows in future that rely on running
cilium-dbg commands rather than cilium commands directly within the Pod.
The 'cp -L' symbolic link dereferencing will make this compatible with
upcoming v1.15-dev based images after https://github.com/cilium/cilium/pull/28085 is merged.
This PR must be merged first, otherwise older versions of this script will
shallow-copy the symlink for 'cilium' into the host and then the 'cilium'
commands will not work. This also implies that when users upgrade to Cilium
v1.15, they will need to update this CLI tool if using external workloads
support, otherwise the script will fail.
Other than that, the code …

clustermesh: Adapt clustermesh script to install cilium-dbg

---

clustermesh/clustermesh.go

Ensure the symlink is installed even if it already exists.
Fixes: 1e059407dc39 ("clustermesh: Adapt clustermesh script to install cilium-dbg")
Signed-off-by: Joe Stringer <joe@cilium.io>

clustermesh: Make cilium symlink install idempotent

---

.github/workflows/kind.yaml

helm-upgrade-clustermesh recently started running out of disk space
[^1]. Run "docker system prune -fa" to make some space before running
cilium connectivity test.
[^1]: https://github.com/cilium/cilium-cli/actions/runs/6423071562/job/17440825179

helm-upgrade-clustermesh: Free up some disk space

---

connectivity/check/features.go

f5ac9776fb21 unintentionally changed the detectFeatures logic by calling ExtractFromConfigMap() and ExtractFromNodes() on ct.Features instead of the features variable declared at the beginning of the loop [^1].
Fixes: f5ac9776fb21 ("Refactor extractFeaturesFromConfigMap()")
[^1]: https://github.com/cilium/cilium-cli/blob/f5ac9776fb217d883edc9f916cb61cb916576693/connectivity/check/features.go#L518

connectivity test: Fix detectFeatures() logic

---

Makefile

Make sure renovate also updates the Go image used to build release binaries.
Example PR in my test repo: https://github.com/tklauser/cilium-cli/pull/25

renovate: update Go image version used to build releases

---

sysdump/sysdump.go

- Call FeatureSet.ExtractFromConfigMap to extract features from cilium-config.
- Add tasks related to SPIRE server if and only if "mutual-auth-spiffe" feature is enabled.
Ref: #1962

sysdump: Detect features from cilium-config ConfigMap

---

status/status.go

This parses the SPIRE connection status if enabled. And will surface errors if present. This also makes sure `--wait` will wait on SPIRE to be up and running in e2e tests.
Fixes https://github.com/cilium/cilium-cli/issues/1821
Uses https://github.com/cilium/cilium/pull/26896 for agent status
```
user@maartje-XPS-9315 ~/g/s/g/c/cilium-cli (main)> ./cilium status
/¯¯\
/¯¯\__/¯¯\    Cilium:          2 errors
\__/¯¯\__/    Operator:        OK
/¯¯\__/¯¯\    Hubble Relay:    disabled
\__/¯¯\__/    ClusterMesh:     disabled
\__/
Deployment        cilium-operator    Desired: 1, Ready: 1/1, Available: 1/1
DaemonSet         cilium             Desired: 2, Ready: 2/2, Available: 2/2
Containers:       cilium             Running: 2
cilium-operator    Running: 1
Cluster Pods:     3/3 managed by Cilium …
```

Pick up SPIRE status messages from cilium-agent

---

sysdump/sysdump.go
utils/features/features.go

Check if "enable-gateway-api" is set to "true" in cilium-config ConfigMap, and collect resources related to Gateway API if and only if the feature is enabled.

sysdump: Detect if Gateway API support is enabled

---

connectivity/check/features.go
sysdump/sysdump.go
utils/features/features.go
utils/features/features_test.go

Detecting Cilium version can get arbitrary complicated. Let's not even try during sysdump feature detection since sysdump doesn't depend on any version-specific features yet.
This commit separates ExtractFromConfigMap into two functions:
- ExtractFromConfigMap to detect version-independent features.
- ExtractFromVersionedConfigMap to detect version-specific features.
Then sysdump uses ExtractFromConfigMap to extract enabled features it needs to know about without having to detect Cilium version. Problem solved, at least for now...
Fixes: #2029

sysdump feature detection: Don't depend on Cilium version

---

connectivity/check/deployment.go

Create echo-external-node deployment if and only if there is a node with "cilium.io/no-schedule=true" label. Otherwise Kubernetes cannot schedule this deployment.
Fixes: d541be5e7ce5 ("connectivity: add echo-external deployment")
Fixes: cilium/cilium#27009

echo-external-node: Check if NodeWithoutCilium is enabled

---

.github/in-cluster-test-scripts/eks-tunnel.sh

Extend the eks-tunnel script to additionally flush the stale AWS-CNI iptables rules left by the aws-node DaemonSet, which break host to pod connectivity. Using the cleanup commands from the documentation [1].
[1]: https://github.com/cilium/cilium/blob/cc2051eec0ba5e57842d8a7d4b4b33f31b12509f/Documentation/installation/k8s-install-helm.rst?plain=1#L208-L211
For https://github.com/cilium/cilium-cli/pull/2035.

gha: cleanup stale AWS-CNI iptables rules in EKS tunnel workflow

---

connectivity/check/deployment.go
connectivity/suite.go
connectivity/tests/encryption.go

Please refer to the individual commit messages for additional details.

Make encryption-related connectivity tests more reliable

---

README.md

The v0.10.x version is no longer supported and so is Cilium 1.10.

README.md: remove v0.10.x from release table

---

connectivity/check/deployment.go

as otherwise replies to traffic SNATed with that same source port will get rejected by the HostPort service

connectivity: don't use an ephemeral port for the echo server

---

.github/workflows/aks-byocni.yaml
.github/workflows/eks-tunnel.yaml
.github/workflows/eks.yaml
.github/workflows/externalworkloads.yaml
.github/workflows/gke.yaml
.github/workflows/kind.yaml
.github/workflows/multicluster.yaml
defaults/defaults.go

This reverts commit 0245001fd6fd9c907780ef0b78547caf118c72eb.
It looks like the external workloads test started failing after upgrading Cilium to v1.14.3. Let's revert while we investigate. It's unclear to me why #2057 didn't fail though.
edit: it's clear to me now why #2057 didn't fail. it ran the CI with v1.14.2 because it uses the pull_request_target trigger.
Ref: #2070

Revert "chore(deps): update dependency cilium/cilium to v1.14.3"

---

k8s/copy.go

I've encountered an issue in a cluster, where the tetragon bugtool files were not complete. After debugging it seems that not all the files were copied. This patch tries to handle this problem by getting the size of the file before the copy. If it is succesful in doing so, then it checks whether we have read everything and if not it returns an error.
There is already support for handling partial reads in the code, so after this patch I am able to read the full size.

k8s/copy: check file size

---

internal/cli/cmd/sysdump.go
sysdump/constants.go
sysdump/defaults.go
sysdump/sysdump.go

- Add support for "serial" tasks in the sysdump subcommand.  Serial tasks are the ones that cannot be executed concurrently with other tasks.
- Add the collection of the data from the Go execution tracer as a "serial" sysdump task.
See the individual commit messages for further details.

sysdump: Add "serial" tasks support to enable trace data collection

---

connectivity/manifests/allow-all-except-world.yaml
connectivity/manifests/client-egress-l7-tls.yaml
connectivity/manifests/client-egress-only-dns.yaml
connectivity/manifests/client-egress-to-echo.yaml
connectivity/manifests/client-egress-to-entities-world.yaml
connectivity/manifests/client-egress-to-fqdns-one-one-one-one.yaml

Connectivity tests fail with the `node-local-dns` environment. This PR adds missing `DNS` rules and changes protocol from `UDP` to `ANY`

fix(connectivity): add dns rules and change protocol to ANY

---

connectivity/check/check.go
connectivity/check/context.go
connectivity/check/deployment.go
connectivity/check/features.go
connectivity/check/peer.go
connectivity/manifests/client-egress-to-cidr-cp-host-knp.yaml
connectivity/manifests/client-egress-to-cidr-k8s.yaml
connectivity/manifests/client-egress-to-entities-host.yaml
connectivity/manifests/client-egress-to-entities-k8s.yaml
connectivity/suite.go
connectivity/tests/host.go
connectivity/tests/k8s.go
internal/cli/cmd/connectivity.go

The control plane nodes create unique policy selection contexts that allow us to test that label selection of host and kube-apiserver entities is correct.

connectivity: Add Control Plane Node Connectivity Tests

---

connectivity/check/context.go

Add a convenient function GetTestOrDie(). There isn't much you can do if GetTest() fails anyways.

connectivity: Add GetTestOrDie()

---

connectivity/check/context.go

Fixes: 89c7ff04254f ("connectivity: Add GetTestOrDie()")
Ref: https://github.com/cilium/cilium-cli/pull/2096#pullrequestreview-1721958513

Rename GetTestOrDie to MustGetTest

---

connectivity/tests/host.go

This commit changes the output format of
the `pod-to-host` test cases.
From:
```
Action [allow-all-except-world/pod-to-host/ping-ipv4-1
```
to:
```
Action [allow-all-except-world/pod-to-host/ping-ipv4-internal-ip
```
by utilizing the `field Type v1.NodeAddressType`
With this change, a user can immediately see if the ping to the ExternalIP or InternalIP of the node is failing. Without the need to run `kubectl get po -o wide` separately.

Add node addr type to pod to host test

---

connectivity/manifests/deny-ingress-backend.yaml
connectivity/manifests/deny-ingress-entity.yaml
connectivity/suite.go

This commit is to add two more tests related to Ingress Controller:
- Deny policy on reserve:ingress identity
- Deny policy on backend service of ingress (e.g. echo-same-node)
Relates: #2015
Testing was done locally as per below
```
$ ./cilium connectivity test --test ingress-service
...
[=] Test [pod-to-ingress-service]
..
[=] Test [pod-to-ingress-service-deny-all]
..
[=] Test [pod-to-ingress-service-deny-ingress-identity]
..
[=] Test [pod-to-ingress-service-deny-backend-service]
..
[=] Test [pod-to-ingress-service-allow-ingress-identity]
..
[=] Skipping Test [dns-only] (skipped by user)
[=] Skipping Test [to-fqdns] (skipped by user)
✅ All 5 tests (10 actions) successful, 53 tests skipped, 0 scenarios skipped.
```

connectivity: Add more tests for Ingress Controller

---

connectivity/check/action.go

I need to be able to access this field when I'm using the connectivity package as a library.

connectivity: Add IPFamily() to Action

---

connectivity/tests/errors.go

Spotted when running upgrade tests in Cilium \[1\]. That particular map is OK to recreate.
\[1\]: https://github.com/cilium/cilium-cli/issues/1858

connectivity: Add exception to policy map recreation

---

connectivity/tests/encryption.go

2ff3df00a04f ("connectivity: fix encryption validation when running in ENI mode") fixed the encryption validation when running in ENI mode, by extending the source interface determination logic to additionally consider the source address, i.e., running
> ip route get dst from src iif lo
The `iif lo` part is required, otherwise the command returns "RTNETLINK answers: Network is unreachable" in case the src address is not assigned to any local interface (which is expected, being src a pod IP).
Yet, this fails with "RTNETLINK answers: Invalid cross-device link" in case rp_filter=1 (strict) is set of the given interface (lo in this case). Given that any local interface can be used there, let's switch it to `cilium_host`, as it is managed by Cilium, and we explicitly set rp_filter=0 to it. …

Fix source interface determination in encryption tests when rp_filter is set to strict

---

clustermesh/clustermesh.go
defaults/defaults.go

The flag 'max-connected-clusters' is a cilium-agent option that allows the user to extend the number of clusters that can be connected in a Clustermesh. This changes the maximum ClusterID that can be used, and thus cilium-cli will now validate according to the agent's configuration.
Additionally, all clusters in a Clustermesh must be configured with the same 'max-connected-clusters', and this is now validated on connection.
Associated PR introducing `max-connected-clusters`  option: https://github.com/cilium/cilium/pull/27520

clustermesh: add support for max-connected-clusters

---

action.yaml

allow to specify the repository from which the release is downloaded, to allow the action to work with different forks of the CLI

action: allow to specify release repository

---

k8s/client.go
k8s/exec.go

When running connectivity tests, it's up to debug logs to provide information on failure errors. This is not always the case, making it hard to understand where to start investigating errors.
This adds pod/container to the error message for calls to k8s exec to make it easier to understand where the issue occurred.
Ex use [case](https://github.com/cilium/cilium/issues/28693):
`Running test echo-ingress-l7-named-port: setting up test: applying network policies: policies were not applied on all Cilium nodes in time: Timeout occurred`
Raises the questions:
* On what Agent Pod?
* "Timeout occurred" error is ambiguous, did the k8s exec request timeout, or the passed command itself?

e2e: add pod/container info in error form exec in pod.

---

defaults/defaults.go
install/helm.go

This change sets the same affinity on the SPIRE agent as CIlium has when` --nodes-without-cilium` is used, this prevents it from being scheduled where Cilium agent is not present.

Make --nodes-without-cilium work with SPIRE

---

defaults/defaults.go

In the last change due to a copy paste error the wrong key got into the spire agent affinity resulting in an install error.

Set operator key correct in SpireAgentScheduleAffinity

---

.github/workflows/release.yaml
Makefile

2 commits:
- build release artifacts on pull requests to make sure all the binaries build successfully.
- drop 32-bit binaries from release artifacts. it's time to move on.

Build release binaries on pull requests

---

action.yaml

- Ignore .git directory. There would be a directory called cilium-cli in .git/refs/tags if there is a Git tag that contains '/cilium-cli/'.
- Ignore vendor directory in case the Go module depends on a package that contains '/cilium-cli/' in the name.

install action: Ignore .git and vendor directories

---

connectivity/tests/health.go

Currently, the health probe connectivity test fails forever if an Cilium Agent Pod that existed when starting the connectivity tests no longer exists.
The reason is that the health probes uses the list of Cilium Agent pods that got fetched at the beginning of the connectivity test run.
Therefore, this commit adds a check whether the Pod still exists. If not, the health probe check fails.
The underlying reason is often that a underlying K8s node has been deleted in the meantime (since starting the tests).
Example of an infinite health probe attempt (until GitHub action timeout) in cilium/cilium due to Cilium Agent Pod deletion (Node has been deleted): https://github.com/cilium/cilium/actions/runs/7060997016/job/19221753163 
Related PR (connectivity test timeout): …

connectivity test: check for deleted cilium agent pod in health probe

---

connectivity/check/check.go
defaults/defaults.go
internal/cli/cmd/connectivity.go

Currently, the connectivity test suite command doesn't have a timeout. Its context only gets cancelled due to interrupt of SIGTERM signal.
For most connectivity test scenarios and actions, this isn't a problem as they have individual fine-grained timeouts (e.g. request timeout).
But there are test scenarios (e.g. `health ` - `Cilium Health Probe`) that might run infinitely on failiure (e.g. if a Cilium Agent Pod no longer is available).
Therefore, this commit introduces a new flag `--timeout` that provides the possibility to configure an overall timeout for the connectivity test suite. It defaults to `0` - meaning no timeout by default (current behavior).
Alternative: Introduce timeout for health probe test (I thought it's better to solve with a global timeout - because other test …

connectivity test: introduce connectivity test suite timeout flag

---

internal/cli/cmd/connectivity.go

The previous non-zero delay might have allowed to slip datapath upgrade bugs unnoticed.

connectivity: Set test-conn-disrupt dispatch interval to 0ms

---

README.md

Cilium v1.11 has been EOLed, so let's remove it from the list.
Also change the wording from "supported" to "compatible". In general I'd like to avoid using the word "supported". It might give users a false impression that the Cilium community is on the hook to provide some form of support.

Remove Cilium v1.11 from the version list

---

connectivity/check/check.go
connectivity/suite.go
connectivity/tests/errors.go
connectivity/tests/errors_test.go
defaults/defaults.go
internal/cli/cmd/connectivity.go

This pull requests ensures we fail the connectivity tests if we hit any unexpected packet drops. The first commit transforms the existing missed-tail-call drops check into a new check for unexpected packet drops. The second commit defines a new flag to set the list of expected packet drop reasons. The last commit adds a bunch of packet drop reasons.

connectivity: Check for unexpected packet drops

---

.github/workflows/aks-byocni.yaml
.github/workflows/eks-tunnel.yaml
.github/workflows/eks.yaml
.github/workflows/externalworkloads.yaml
.github/workflows/gke.yaml
.github/workflows/kind.yaml
.github/workflows/multicluster.yaml

Assign unique names to connectivity test jobs so that we can control which of these jobs are required.

Assign unique names to connectivity test jobs

---

.github/cilium-cli-test-job-chart/templates/job.yaml
.github/cilium-cli-test-job-chart/values.yaml
.github/in-cluster-test-scripts/external-workloads-install.sh
.github/workflows/aks-byocni.yaml
.github/workflows/eks-tunnel.yaml
.github/workflows/eks.yaml
.github/workflows/externalworkloads.yaml
.github/workflows/gke.yaml
.github/workflows/kind.yaml
.github/workflows/multicluster.yaml

Let's remove classic mode tests from the main branch. In a very unlikely event of having to fix a bug in the classic mode for Cilium v1.12 or v1.13, we can create v0.14 branch from v0.14.8 tag and patch it there.
Ref: https://github.com/cilium/cilium-cli#releases

Remove classic mode tests from the main branch

---

.github/workflows/kind.yaml

Michi reported that reverting [1] fix the Kind CI job flake, and that they were due to too many flow events generated by the test-conn-disrupt pods.
As we don't care about the sensitivity of those tests in cilium/cilium-cli, set the interval to 100ms to reduce the events count (and thus, the test runtime).
[1]: https://github.com/cilium/cilium-cli/pull/2156
Reported-by: Michi Mutsuzaki <michi@isovalent.com>

kind: Set conn-disrupt-test-setup

---

install/azure.go
install/install.go
internal/cli/cmd/install.go
internal/helm/helm.go

In EKS mode, don't stop the AWS node DaemonSet when running in dry-run mode. In AKS mode, don't create any cloud resources.
Fixes #2161

Don't modify running cluster in dry-run mode

---

connectivity/check/deployment.go

To include arm64 build - https://github.com/cilium/test-connection-disruption/pull/9.

connectivity: Bump test-connection-disruption img to v0.0.13

---

.github/workflows/eks-tunnel.yaml
.github/workflows/eks.yaml
connectivity/check/deployment.go

for some upcoming tests we will need a new client scheduled on a different node than the first 2 clients. This commit adds this new client.

check: add third client scheduled on a different node

---

connectivity/check/check.go
connectivity/suite.go
connectivity/tests/errors.go
connectivity/tests/ipsec_xfrm.go
defaults/defaults.go
internal/cli/cmd/connectivity.go
utils/features/utils.go
utils/features/utils_test.go

First commit refactors the existing logic for the `--expected-drop-reasons`. The second adds a new `--expected-xfrm-errors`.

connectivity: Ignore expected XFRM errors

---

defaults/defaults.go

This excludes the drop reason introduced in https://github.com/cilium/cilium/pull/29482. It occurs when Cilium is first installed on a node, the host firewall is enabled, a workload endpoint gets created before the host endpoint, and the workload endpoint in question tries to talk to the host.
Preventing these drops would require redesigning parts of the datapath, particularly the clustermesh bootstrap procedure. This is not feasible at the moment, and maybe it's not the right thing to do.

defaults: add 'Host datapath not ready' to expected drop reasons

---

connectivity/check/deployment.go
connectivity/check/wait.go
utils/features/features.go

Looks like Cilium endpoint verification is no longer needed because Cilium should be already provisioned correctly in the environment before deploying the connectivity apps, and these tests already validate that the k8s deployment resource is ready before continuing.
This should also unblock connectivity tests for Customers that have `disableEndpointCRD: "true"` property configured.

Drop cilium endpoint verification.

---

clustermesh/clustermesh.go

The clustermesh-apiserver cannot be used in combination with Cilium running in kvstore mode when the identity allocation mode is kvstore. In this case, remote clusters shall be configured to directly connect to the local etcd cluster. Let's extend the `clustermesh status` command to additionally cover this setup, ignoring the validation of clustermesh-apiserver specific resources.
Additionally, let's improve the reporting in case `cilium clustermesh status --wait` times out, and fix an issue causing it to always report an error if the clustermesh secret also includes the configuration for the local cluster.

Make cilium clustemesh status compatible with external kvstore

---

internal/cli/cmd/install.go

fixed spelling mistake in help output

Cilium-cli - fixed spelling mistake in "install" help output

---

.github/kind-config-1.yaml
.github/kind-config-2.yaml
.github/workflows/kind.yaml
connectivity/check/context.go
connectivity/check/deployment.go
connectivity/check/wait.go
connectivity/suite.go
connectivity/tests/from-cidr.go
k8s/client.go

Please review commit by commit, and refer to the individual messages for additional details.

Enable running connectivity tests requiring a node without Cilium in combination with clustermesh

---

connectivity/check/deployment.go

Let's use the proper pause entrypoint, instead of sleep, so that the container reacts to signals and terminates immediately when the pod is deleted, instead of waiting for the expiration of the grace period.
Related: https://github.com/cilium/alpine-curl/pull/97

Make connectivity test pods terminate quickly

---

defaults/defaults.go

This pull request adds XfrmInStateInvalid errors to the list of XFRM errors to ignore if they are rare (less than 10 occurrences), as per https://github.com/cilium/cilium/pull/30151.

defaults: Ignore XfrmInStateInvalid errors if rare

---

.github/workflows/kind.yaml

Due to some recent changes on GitHub's side, uploading the JUnit reports on the second job to finish in the kind workflow will fail with:
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
Avoid this from happing by giving the artifacts unique names.
Fixes #2222

ci: unique artifact name for junit reports in kind workflow

---

.github/workflows/kind.yaml

The nodes are no longer labeled in the kind workflow since commit e1b543279e1c ("kind: Configure external targets inside the cluster") so they also don't need to be unlabeled on cleanup.

ci: remove unnecessary steps unlabeling nodes in kind workflow

---

clustermesh/clustermesh.go

Fix hardcoding of service type in clustermesh code

clustermesh: fix hardcode at service type

---

internal/cli/cmd/version.go

Refactored the error messaging logic for obtaining the running Cilium version in the `GetRunningCiliumVersion` function. This modification enhances clarity and provides more detailed error information when encountering issues.
Current implementation:
This error message is misleading since the pods are running in the specified namespace.
After this change, the correct error message is returned:

refactor: improve error messaging for version command

---

connectivity/manifests/allow-host-entity-egress.yaml
connectivity/manifests/allow-host-entity-ingress.yaml
connectivity/suite.go
connectivity/tests/host.go

Extend the connectivity suite to additionally validate that node to pod connectivity works as expected, both in absence of policies and if the ingress policy allows the host identity. Currently, we are only partially testing this path as part of the node-to-node encryption test, which makes it more difficult to pinpoint the cause of possible failures.

Add host to pod tests to the connectivity suite

---

connectivity/check/deployment.go

Fixes #2236 
The host-netns-non-cilium and host-netns daemonsets leveraged by the connectivity tests are only deployed in specific situations. Do not wait for them in other cases, as it blocks the tests.
Only tested on my environment, not sure if maintainers would prefer a different fix. Happy to update the PR as needed, thanks!
An alternative approach would be for `WaitDaemonSet` to not retry any `not found` errors, but that might have more unintended consequences, hence I decided not to do it like this.

connectivity: only wait for daemonsets if needed

---

connectivity/check/logging.go
connectivity/tests/encryption.go
utils/lock/buffer.go
utils/sniff/filters.go
utils/sniff/sniffer.go

Please review commit by commit and refer to the individual commit messages for additional details. Most of the changes in this PR are due to moving code around, and are isolated in their own commits (second, third and sixth).

Extract and generalize the sniffer logic used by encryption tests for easier reusability

---

bgp/routes.go
internal/cli/cmd/bgp.go

As the necessary cilium-dbg functionality for retrieving BGP routes was backported to cilium v1.14.6 (https://github.com/cilium/cilium/pull/30205), we have to use the `cilium` binary instead of `cilium-dbg` to fetch routes from cilium pods, as the rename from `cilium` to `cilium-dbg` happened in 1.15.
This also updates the minimal cilium version for this command in the command description.

bgp: routes CLI - update min. cilium version, use `cilium` binary

---

sysdump/sysdump.go

Currently, hubble flows are retrieved during sysdump collection passing the `--follow` parameter to hubble observe. According to the comment, this appeared to be a necessary hack to prevent the "requested data has been overwritten and is no longer available" error. Yet, the consequence is that the hubble observe command becomes blocking, and we relying on the specified timeout only for its termination. When capturing a sysdump, though, we are interested in storing (as many as possible) flows prior to that moment (e.g., to investigate the causes of a connectivity test failure), not the ones occurring during the collection of the sysdump itself.
Given that the original reason for using the `--follow` parameter got fixed quite some time ago \[1\] and the fix is included in any Cilium …

sysdump: don't specify --follow while collecting hubble flows

---

Makefile

After this commit running make with "DEBUG=true make" (or really any value, we only check that DEBUG is defined) will no longer strip debug info from the resulting binary.
This allows dlv to be used for debugging the cilium cli.

make: allow building with debug symbols

---

.github/workflows/go.yaml

This step is now redundant since we've added the Release workflow [^1] that runs `make release' for each pull request.
[^1]: https://github.com/cilium/cilium-cli/blob/main/.github/workflows/release.yaml

Go workflow: Remove Cross-build step

---

utils/features/features.go
utils/features/features_test.go

Please refer to the individual commit messages for additional details.

Minor improvements concerning the tunnel feature determination for connectivity tests

---

internal/cli/cmd/status.go

`cilium status` does currently return exit-code 0 in case of errors.
Adding an error here in case exists in the sub command, so it will result in correct exit-code `1`.
Fixes #2232

Fix status exit code

---

connectivity/check/action.go
connectivity/check/logging.go
connectivity/check/test.go

When developing new connectivity tests, we may be interested in creating an _action_ also in case we are not strictly running a connectivity check, but for instance checking for error logs or similar (to benefit from better progress and error reporting). Let's introduce a `NewGenericAction` method for such use-cases, as well as the possibility of tuning the sysdump collection policy, as it may be superfluous to collect one sysdump for each failure.
Please review commit by commit, and refer to the commit messages for additional details.

Simplify executing generic checks as part of the connectivity suite

---

connectivity/check/context.go

Add CiliumNodes to the list of resources which are retrieved during connectivity tests initialization, and stored for later access from individual tests. Indeed, CiliumNodes contain additional information compared to plain Kubernetes Node objects, especially around IPAM. Additionally, leverage them to determine the PodCIDRs used for certain (unsafe) tests, so that we retrieve the correct CIDR both in case of kubernetes and cluster-pool IPAM modes, whereas now it only works in the first case.

Retrieve CiliumNodes in connectivity tests context, and use them to determine PodCIDRs

---

bgp/routes.go
bgp/routes_test.go

After simplification of `cilium-dbg bgp routes advertised` command in https://github.com/cilium/cilium/pull/30033 is merged, we can rely on it to make the same simplifications in cilium CLI:
- allow retrieving advertised routes for each peer (without the need to specify a peer)
- introduce defaulting for AFI & SAFI
Examples:
```
$ cilium bgp routes                                                                                                                                                                      ✔ 
(Defaulting to `available ipv4 unicast` routes, please see help for more options)
Node                                  VRouter   Prefix          NextHop   Age   Attrs
clab-bgp-cplane-devel-control-plane   65001     10.244.0.0/24   0.0.0.0   3s    [{Origin: i} {Nexthop: …
```

bgp: enhance defaulting of `bgp routes` command

---

cli/cmd.go
connectivity/check/context.go
connectivity/suite.go
internal/cli/cmd/connectivity.go
internal/cli/cmd/hooks.go

Currently, the SetupAndValidate extension hook is executed right after feature detection, but before the setup and validation of the different connectivity test pods and artifacts. While this has the advantage of nicely integrating with the logging of the detected features, it does not allow the hook function to rely on the existence of the pods created immediately afterwards. To enable both functionalities, let's split the hook into two -- one first function to detect extra features, and a second to perform the actual setup and validation of extra pods.

hooks: split feature detection from setup and validation

---

connectivity/tests/health.go

Fix a possible panic occurring if the cilium-health test fails and flow validation is enabled, or --print-flow is given. Indeed, that action is configured with a nil destination (as the check has no strict destination target), in turn causing the panic during flow visualization. Hence, let's switch to creating a generic action (i.e., intended for generic assertions), effectively disabling flow collection and display.
Hit in https://github.com/cilium/cilium-cli/actions/runs/7708934175/job/21020724137?pr=2273

connectivity: fix panic if the cilium-health test fails

---

clustermesh/clustermesh.go

`cilium clustermesh disconnect` never work with helm version:
`remote cluster has cluster ID %d out of acceptable range (1-0)`
So i fix it.

Fixes cilium clustermesh disconnect

---

README.md
RELEASE.md

Also drop Cilium 1.12 from the Release section of README.md since it's been EOLed.

Prepare for v0.15.22 release

---

sysdump/constants.go

This is to avoid the below warning
```
W0205 12:29:06.703289  146168 warnings.go:70] The v1alpha2 version of ReferenceGrant has been deprecated and will be removed in a future release of the API. Please upgrade to v1beta1.
```

gateway: Upgrade API version

---

encrypt/ipsec_key_status.go
internal/cli/cmd/encrypt.go

`encryption key-status` command implementation to address: https://github.com/cilium/cilium/issues/28174.

IPsec key status command implementation.

---

clustermesh/clustermesh.go
internal/cli/cmd/clustermesh.go

Currently, the `cilium clustermesh external-workload install` command attempts to retrieve the Cilium version from either the secret created by the CLI (when running in classic mode) or from the helm release. The retrieved version is then used to tune the one of the options passed to the Cilium container on the external workload, which at a certain point got renamed. Given that all supported Cilium stable versions do support the new flag, and considering that the retrieval logic is potentially fragile (e.g., it fails if Cilium is installed with a non-default release name), let's just drop all of this logic. Regardless, we retrieve the Cilium image from the existing DaemonSet.

Remove no longer necessary step from the external workloads installation script generation process

---

connectivity/check/check.go
connectivity/suite.go
connectivity/tests/errors.go
defaults/defaults.go
go.mod
internal/cli/cmd/connectivity.go
k8s/client.go
sysdump/client.go
sysdump/sysdump.go
sysdump/sysdump_test.go

Currently, we check for errors in Cilium agent logs only when unsafe tests are enabled. Let's promote this check to be always performed for Cilium v1.14 and subsequent (earlier versions are not compatible with the Cilium CLI v0.15 series), to ensure that we catch unexpected errors early (as unsafe tests are only enabled in a limited set of CI workflows) given that it does not perform any unsafe operation. Additionally, let's extend it to also cover the init containers in the cilium agent pods, as well as other cilium components, such as the operator and the clustermesh-apiserver.

Enable no-errors-in-logs check by default, and extend it to all Cilium components

---

connectivity/manifests/client-egress-only-dns.yaml
connectivity/manifests/client-egress-to-entities-world.yaml
connectivity/manifests/client-egress-to-fqdns-one-one-one-one.yaml

OpenShift runs coreDNS in openshift-dns namespace and uses port 5353.
This PR adds rules to CiliumNetworkPolicies so that name resolution can succeed during the connectivity tests.

chore: Amend connectivity tests for OpenShift

---

.github/workflows/aks-byocni.yaml
.github/workflows/gke.yaml

I've been recently hitting the timeout quite frequently on these two workflows. Let's try increasing it to see if the situation improves.

Increase timeouts in AKS and GKE GHA workflows

---

.github/workflows/externalworkloads.yaml

Recently, I've been hitting [pretty consistent issues](https://github.com/cilium/cilium-cli/actions/runs/7884573763/job/21527869230?pr=2299) on this workflow caused by pods being evicted due to DiskPressure. Let's try increasing the disk size from 10GB to 15GB to see if the situation stabilizes.

gha: increase GKE disk size in external workloads workflow to 15GB

---

.github/workflows/externalworkloads.yaml
.github/workflows/gke.yaml
.github/workflows/multicluster.yaml

GCP OIDC authentication instead of Service Account credentials.
Workflow examples:
- https://github.com/cilium/cilium-cli/actions/runs/7931483164
- https://github.com/cilium/cilium-cli/actions/runs/7931483170
- https://github.com/cilium/cilium-cli/actions/runs/7931483171

GCP OIDC instead of SA creds.

---

defaults/defaults.go

When host firewall is enabled, we automatically drop certain ICMPv6 messages according to RFC4890 recommendations. Let's add that drop reason to the default list of expected ones, as possibly generated in legitimate cases, independently from Cilium.
As a special case, an ICMPv6 redirect message can be also triggered when Cilium is first installed on a node, the host firewall is enabled and KPR is disabled, a workload endpoint gets created before the host endpoint (e.g., the health one), and a remote node tries to talk to it. Indeed, the reply is passed to the stack, which is then unable to redirect it through the tunnel as the BPF program has not yet been loaded.
Related: https://github.com/cilium/cilium/pull/30818

connectivity: add forbidden ICMPv6 message as expected drop reason

---

connectivity/check/context.go
connectivity/check/features.go
connectivity/check/policy.go
connectivity/check/test.go
connectivity/manifests/host-firewall-egress.yaml
connectivity/manifests/host-firewall-ingress.yaml
connectivity/suite.go
utils/features/features.go

Introduce two new tests covering the host firewall functionality, i.e., asserting that both ingress and egress CiliumClusterwideNetworkPolicies specifying a NodeSelector correctly block the expected traffic. The
tests are executed only when the unsafe tests are enabled, as potentially disruptive if executed against a live cluster.
The initial five commits are refactor and generalize the logic in charge of parsing, registering and creating/updating the policies used during the tests, to uniform it, reduce code duplication, and in preparation for the support for CCNPs. The sixth commit introduces the actual support for CCNPs in connectivity test. The last commit introduces the actual tests.
Please review commit by commit, and refer to the commit messages for additional details.

Introduce host firewall connectivity tests

---

CODEOWNERS

With the new encryption commands added by Viktor, I believe we should add the relevant codeowners

Add sig/encryption as owner of /encrypt/ in CODEOWNERS

---

connectivity/suite.go
connectivity/tests/errors.go

Let's leverage the GenericAction construct to provide better progress and error reporting for the given test, displaying the node associated with any issue and ensuring that we continue checking for problems also after that a first one has been found. Let's also configure it to still capture a single sysdump regardless of the number of failures.

connectivity: improve reporting for no-unexpected-packet-drops check

---

clustermesh/clustermesh.go
hubble/hubble.go
install/install.go
k8s/client.go
status/k8s.go
status/k8s_test.go
status/status.go

Introduce an additional step to the cilium status command to check
(and optionally wait) for endpoints readiness. This check is
particularly relevant in CI to ensure that the datapath of already
existing endpoints has been fully updated (i.e., restoration and
regeneration phases have completed) after agent restart, before
proceeding with the subsequent tests. Otherwise, we may continue
to incorrectly exercise the old datapath and miss possible issues,
especially concerning dropped connections and missed tail calls.

cilium status: additionally check for endpoints readiness

---

internal/cli/cmd/status.go

Currently, `cilium status` might fail with the following output (which is not informative):
```
status check failed
```
New output example:
```
status check failed: [the server could not find the requested resource (get ciliumendpoints.cilium.io)]
```

Status check error message improved.

---

utils/sniff/sniffer.go

Let's improve the handling of tcpdump termination by the Sniff utility in two main directions:
* Don't return an error if tcpdump successfully exited before we determined it was ready. This can happen when running in sanity mode, as tcpdump exits after capturing a single packet matching the filter. Fixes the `Failed to execute tcpdump: %!w(<nil>)'` flake.
* Explicitly assert that tcpdump didn't terminate in advance when running in assert mode, as otherwise we may have missed packets.

sniffer: improve handling of tcpdump termination

---

status/k8s.go

The fix is required for the Customers that have `disableEndpointCRD: "true"` in the Cilium configuration.
Status output example when `disableEndpointCRD: "true"`:
The logic was stolen from: https://github.com/cilium/cilium-cli/blob/main/install/install.go#L582-L587

Ignore Cilium endpoints not found error for the status command.

---

k8s/client.go

A non-empty stderr is interpreted as a command failure. However, calling code still assumes the output it gets is the output of the command, whereas we currently just return a pristine buffer.
Fix it by returning the buffer.
An example of why this is annoying: https://github.com/cilium/cilium/actions/runs/8043919487/job/21966754656#step:17:328

k8s: don't drop stdout of kubectl exec

---

connectivity/tests/encryption.go

In Cilium v1.15 and later (as well as v1.14 if the --wireguard-encapsulate flag is set), when both tunnel encapsulation and WireGuard encryption are enabled, packets are first encapsulated and then encrypted. Let's fix the connectivity check inter-node interface determination when host firewall is additionally enabled, as currently always defaulting to the tunnel interface, which is incorrect (we would flag the packets as unencrypted, even though the encapsulated packets are encrypted afterwards).

connectivity: fix encryption validation with wireguard encap + host fw

---

connectivity/check/context.go
hubble/hubble.go
install/uninstall.go
internal/cli/cmd/install.go

By default, the helm libraries will use background cascading delete which means the call to do helm uninstall returns following the deployment being removed.
This means that running workloads, such as hubble-relay, may continue to be in the terminating state following `cilium uninstall --wait` exiting.
We depend on this behavior in CI E2E to clean up and reuse clusters for testing Cilium in different configurations.
In flakes such as: https://github.com/cilium/cilium/issues/30993 it seems like the old Hubble Pods are bleeding into the "fresh" install. These should be harmless, however this is triggering failures of the [no-error-logs] assertion in the following connectivity tests.
This change will provide a more thorough uninstall procedure in this case.

uninstall: when --wait is specified, use foreground deletion.

---

internal/cli/cmd/version.go
internal/helm/helm.go
k8s/client.go
status/k8s.go

Namespace is already configured in HelmActionConfig, so defining Get and GetParameter is somewhat redundant and misleading. Directly call Helm client Get() instead.

helm: Remove Get and GetParameter

---

.github/in-cluster-test-scripts/eks-tunnel.sh
.github/in-cluster-test-scripts/eks.sh
.github/in-cluster-test-scripts/external-workloads-install.sh
.github/in-cluster-test-scripts/gke.sh
.github/in-cluster-test-scripts/multicluster.sh
clustermesh/clustermesh.go
install/autodetect.go
install/helm.go
internal/cli/cmd/install.go

I assert that #1347 is no longer an issue since we've removed the classic mode in #2327.

Remove --cluster-name flag

---

k8s/exec.go
k8s/internal/ctrlcreader.go

CtrlCReader is only used by the k8s package.

refactor: Move ctrlcreader.go under /k8s/internal/

---

action.yaml

Add go-mod-directory parameter to override the directory that contains go.mod in case go.mod is not in local-path.

action: Add go-mod-directory parameter

---

utils/sniff/sniffer.go

Currently, we dump unexpected captured packets only when debug mode is enabled. However, this makes troubleshooting possible CI flakes (e.g., caused by too open tcpdump filters) difficult, due to the lack of information about the exact captured packets. Hence, let's just always output them, regardless of the verbosity mode.

sniffer: always dump captured packets in assert mode

---

cli/cmd.go
internal/cli/cmd/connectivity.go
internal/cli/cmd/hooks.go
internal/cli/cmd/sysdump.go
sysdump/sysdump.go

Move SysdumpHooks and InitSysdumpFlags to the sysdump package so that they can be imported from outside the cilium-cli repo.

sysdump: Export Hooks and InitSysdumpFlags

---

Makefile
cli/cmd.go
defaults/defaults.go
internal/cli/cmd/cmd.go
internal/cli/cmd/connectivity.go
internal/cli/cmd/install.go
internal/cli/cmd/sysdump.go
internal/cli/cmd/version.go

Move the CLI version string from internal/cli/cmd to default/ so that it can be exported from outside the cilium-cli repo.

Move the CLI version string to the default package

---

.golangci.yml
connectivity/check/deployment.go
connectivity/check/metrics_test.go
connectivity/check/peer.go
connectivity/check/test.go
connectivity/tests/ipsec_xfrm.go
sysdump/sysdump.go

See commits for details.
Same as https://github.com/cilium/cilium/pull/30215 did in cilium/cilium.

Remove duplicate imports and enable stylecheck linter to prevent them

---

connectivity/tests/errors.go

Add error log check exception for leader election errors.
The operator uses the client-go leader election sdk, which reattempts acquiring the lock, logging failures via klog [1].
[1] https://github.com/cilium/cilium/blob/6a70af21c3b6985096fca3f8240139b548ac4760/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go#L332
In general, such errors should be transient, if it is persistent then it wouldn't be isolated to just this api so it should be ok to ignore all such errors.
Signed-off-by: Tom Hadlaw <tom.hadlaw@isovalent.com>

Add error log check exception for leader election errors.

---

connectivity/check/deployment.go

This is to use echo-same-node instead of echo-other-node, which is only available for multi-node cluster. The reason is mainly for local development, no impact on CI.

ingress: Update backend service for Ingress

---

.github/in-cluster-test-scripts/external-workloads-install.sh
.github/workflows/kind.yaml
connectivity/check/features.go
connectivity/tests/service.go
hubble/hubble.go
install/autodetect.go
install/azure.go
install/helm.go
install/install.go
internal/helm/helm.go

Please review commit by commit, and refer to the individual messages for additional details.
* Remove unused fields/parameters from the `getHelmValues` logic;
* Drop support for EOL Cilium v1.11 and earlier in helm values generation;  
* Drop broken `bpf.masquerade` autodetection logic;
* Fix retrieval of the user-configured routing mode, and uniform retrieval of nested helm value;
* Improve KPR autodetection logic to not override user configuration, and not configure deprecated values;
* Fix KPR probing in connectivity tests to account for both legacy and current values.
* Replace the remaining references to deprecated KPR settings in GHA workflows.

Improve the helm values autodetection logic

---

cli/cmd.go
cli/cmd_test.go
cli/hooks.go

Call InitializeCommand hook with the root command before returning from cli.NewCiliumCommand.

Add InitializeCommand hook

---

api/api.go
api/api_test.go
cli/cmd.go

Store namespace and k8sClient as command context values so that the connectivity package can access them from outside the cli package once it moves to cilium/cilium repo.

Store namespace and k8sClient in the command context

---

.github/renovate.json5
go.mod

Let's not pick up new Go patch versions in go.mod to be consistent with cilium/cilium. https://github.com/cilium/cilium/pull/28686 has more context about the rationale.

renovate: Don't pick up new Go patch versions in go.mod

---

.github/workflows/multicluster.yaml

Recently the Multicluster workflow started to timeout pretty often.
Try to increase the timeout and see if the problem re-appears.

gha: increase Multicluster timeout

---

connectivity/check/deployment.go

This reverts commit 7e7fa6a640dd11db48d922ce199b1eda2851c19b.
Let's revert this commit until we figure out what's going on with https://github.com/cilium/cilium/pull/31386#issuecomment-1999858350.
Ref: #2383

Revert "ingress: Update backend service for Ingress"

---

.github/workflows/kind.yaml
cli/install.go
install/helm.go
install/install.go

Explicitly configure the appropriate affinities to not schedule Cilium components on the nodes labeled as `cilium.io/no-schedule` during the preinstall phase, which is executed both during the initial installation and on subsequent upgrades. This change removes the side-effect from the getHelmValues method, which is no longer executed on upgrade after a recent refactoring. Additionally, let's convert the `--nodes-without-cilium` flag to boolean, as the values are always ignored.

Explicitly configure the "nodes without cilium" affinity on both initial installation and subsequent upgrades 

---

connectivity/tests/errors.go

Add "Failed to update lock:" and "Failed to release lock:" to log level error excpetions, as these errors originate from vendored code and we can not silence them otherwise. This prevents CI flake like this:
❌ Found 1 logs in kind-kind/kube-system/cilium-operator-799cff46cd-n2lfz (cilium-operator) matching list of errors that must be investigated:
level=error msg="Failed to update lock: Operation cannot be fulfilled on leases.coordination.k8s.io \"cilium-operator-resource-lock\": the object has been modified; please apply your changes to the latest version and try again" subsys=klog (1 occurrences)

tests: Add exceptions for error logs check

---

connectivity/check/deployment.go

Let's prevent possible conflicts if the given NodePorts are already allocated, as well as headaches to create multiple ingresses.

connectivity: don't hard-code ingress service NodePorts

---

Makefile
defaults/defaults.go

Make Version and HelmRepository variables instead of consts so that they can be overridden using build tags or go build -X ldflag.

defaults: Move Version and HelmRepository from const to var

---

defaults/defaults.go

The connectivity tests sometimes runs into "Unsupported L2 protocol" drops for issues unrelated to Cilium. Ignore those as it otherwise just adds noise.

Ignore "Unsupported L2 protocol" to known drops

---

connectivity/builder/to_fqdns.go
connectivity/check/action.go

Make sure that we don't append a trailing dot to the DNS name to be matched if already fully-qualified, and remove it from HTTP validation to match the behavior of the curl action.

Fix flow validation with fully-qualified DNS names

---

.github/renovate.json5

Configure renovate to pick up github.com/cilium/cilium prereleases instead of upgrading it manually like I did in cilium/cilium-cli#2360.

renovate:: Pick up github.com/cilium/cilium prereleases

---

connectivity/check/deployment.go
connectivity/check/wait.go

Rather than just listing the services, let's explicitly wait until we successfully retrieve all expected services, so that we can provide a clear error in case something went wrong and they were not created.

Explicitly wait for ingress service creation

---

.github/in-cluster-test-scripts/aks-byocni-install.sh

Follow https://github.com/cilium/cilium/pull/31504, quoting its commit description:
> The default service CIDR of AKS clusters is 10.0.0.0/16 [1].
> Unfortunately, we don't set a pod cidr for clusterpool IPAM, and hence
> use cilium's default of 10.0.0.0/8, which overlaps. This can
> lead to "fun" situations in which e.g. the kube-dns service ClusterIP is
> the same as the hubble-relay pod IP, or similar shenanigans. This
> usually breaks the cluster utterly.
>
> The fix is relatively straight-forward: set a pod CIDR for cilium which
> does not overlap with defaults of AKS. We chose 192.168.0.0/16 as this
> is what is recommended in [2].
>
> [1]: https://learn.microsoft.com/en-us/azure/aks/configure-kubenet#create-an-aks-cluster-with-system-assigned-managed-identities
> [2]: …

ci: avoid overlapping pod and service CIDRs on AKS

---

.github/in-cluster-test-scripts/aks-byocni-install.sh

The trailing " makes the installation fail on AKS with:
2024-03-26T19:25:46.385719258Z /root/test/in-cluster-test-script.sh: line 15: syntax error: unterminated quoted string
See e.g. https://github.com/cilium/cilium-cli/actions/runs/8440743477/job/23118350044
Fixes: 918ae165b699 ("ci: avoid overlapping pod and service CIDRs on AKS")

ci: fix installation on AKS

---

cli/clustermesh.go
cli/cmd.go
cli/hubble.go
cli/install.go
cli/sysdump.go
cli/version.go
clustermesh/clustermesh.go
defaults/defaults.go
hubble/hubble.go
install/install.go
install/uninstall.go
install/upgrade.go
internal/helm/helm.go
k8s/client.go
status/k8s.go
sysdump/defaults.go
sysdump/sysdump.go

This update introduces a new parameter across several functions and actions to allow the user to specify a Helm release name for the Cilium installation. This enables referencing installations installed via Helm directly. The default Helm release name remains "cilium" when no custom release name is provided.
The new global flag proposed here is: `--helm-release-name`.
Fixes: #2274
Signed-off-by: Matthew Hembree <47449406+matthewhembree@users.noreply.github.com>

feat: Make Cilium CLI work with Cilium installed through helm with a non-default name.

---

connectivity/tests/errors.go
connectivity/tests/errors_test.go

FQDN Proxy together running with Wireguard has an issue where proxied dns requests can cause a port collision. See: https://github.com/cilium/cilium/issues/31535
Despite this, the actual fqdn tests seem to be resilient to this, likely due to retries.
While we work on a fix for this issue, let's add a temporary exception here.

errors: add [no-error-logs] exception for issue caused by fqdn bug.

---

install/autodetect.go

The logic to determine whether KPR should be enabled using the "true" setting or the legacy "strict" one, based on the Cilium version, appears to be inverted, apparently due to a test change which got incorrectly committed. Let's fix it.
Fixes: ad3a82c210ee ("helm: improve KPR autodetection logic")

helm: fix KPR autodetection value

---

.github/renovate.json5
go.mod
go.sum
vendor/modules.txt

Use the same version of github.com/osrg/gobgp/v3 as cilium/cilium.
Ref: https://github.com/cilium/cilium/pull/31123

Pin github.com/osrg/gobgp/v3 to v3.23.0

---

k8s/client.go
sysdump/client.go
sysdump/constants.go
sysdump/sysdump.go
sysdump/sysdump_test.go

Collect information about the release like the chart repo, chart version, revision, status, etc.
After collecting a sysdump:
```
$ unzip -l cilium-sysdump-20240321-143159.zip | grep helm-meta
154  03-21-2024 14:32   cilium-sysdump-20240321-143159/cilium-helm-metadata-20240321-143159.yaml
$ unzip -p cilium-sysdump-20240321-143159.zip cilium-sysdump-20240321-143159/cilium-helm-metadata-20240321-143159.yaml
appVersion: 1.14.7
chart: cilium
deployedAt: "2024-03-20T16:24:27-07:00"
name: cilium
namespace: kube-system
revision: 1
status: deployed
version: 1.14.7
```

sysdump: Collect helm metadata

---

connectivity/builder/builder.go
connectivity/builder/host_firewall_egress.go
connectivity/builder/host_firewall_ingress.go
connectivity/check/test.go

Introduce two new tests covering the host firewall functionality, i.e., asserting that both ingress and egress CiliumClusterwideNetworkPolicies specifying a NodeSelector correctly block the expected traffic. The tests are executed only when the unsafe tests are enabled, as potentially disruptive if executed against a live cluster.
Original commit by Marco Iorio
https://github.com/cilium/cilium-cli/commit/7a928d68204172547ff2cbf0a858da0e27233737
has been accidentally dropped by the following commit during merge
https://github.com/cilium/cilium-cli/commit/486eb991b228aef825294008a1ce11a098c0c377

connectivity: introduce host firewall tests

---

cli/connectivity.go
connectivity/check/check.go
connectivity/check/deployment.go
defaults/defaults.go

Please review commit by commit, and refer to the individual messages for additional details. Brief summary follows:
* Make test-conn-disrupt image configurable, to simplify testing new versions.
* Bump the test-conn-disrupt image to v0.0.14 to include https://github.com/cilium/test-connection-disruption/pull/12.
* Configure CPU requests to prevent stalling due to CPU starvation.

connectivity: misc conn-disrupt-test improvements

---

CODEOWNERS
connectivity/builder/builder.go
connectivity/builder/endpointslice-clustermesh-sync.go
connectivity/check/context.go
connectivity/check/deployment.go
connectivity/check/wait.go
connectivity/tests/clustermesh-endpointslice-sync.go
utils/features/features.go

This adds endpointslice synchronization testing inside a clustermesh. It does that by checking that we can get a DNS answer with a global headless service with endpointslice synchronization enabled across two clusters.
Testing it via DNS ensures that the created EndpointSlice are correctly linked to the headless service.
Related to https://github.com/cilium/cilium/pull/28440 e2e testing

connectivity: add endpointslice clustermesh sync test

---

connectivity/check/context.go

If the `--cilium-namespace` and `--agent-pod-selector` (default `kube-system` and `k8s-app=cilium`) don't match anything, `cilium connectivity test` segfaults.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x102fbe948]
goroutine 24 [running]:
github.com/cilium/cilium-cli/connectivity/check.(*ConnectivityTest).detectCiliumVersion(0x140004ace08, {0x104e88238?, 0x140002f9f40?})
/Users/oklischat/src/cilium-cli/connectivity/check/features.go:266 +0x168
github.com/cilium/cilium-cli/connectivity/check.(*ConnectivityTest).SetupAndValidate(0x140004ace08, {0x104e88238, 0x140002f9f40}, {0x12e860658, 0x10736f180})
/Users/oklischat/src/cilium-cli/connectivity/check/context.go:290 +0xa4 …
```

connectivity test: avoid segfault if no agent pods are found

---

Makefile

Windows users nearly never use tar.gz files but it's common to use zip files.
I suggest this PR to change in the releases the output format for windows binaries.

ci: Use zip output for windows releases

---

connectivity/builder/builder.go
connectivity/suite.go

New functions implemented for the test builder component to split connectivity tests into a few chunks:
1. Network performance tests
2. Conn disrupt tests
3. Concurrent tests
4. Sequential tests
5. Final tests
This refactoring is a preparation for the conn tests concurrent run.

Split conn tests into chunks

---

cli/install.go
connectivity/check/context.go
install/install.go
install/uninstall.go

Move UninstallResources() to the install package. UninstallResources() is only called from K8sUninstaller, and the logic to delete the test namespace doesn't depend on anything from the connectivity package. Also rename the function to DeleteTestNamespace() to be a bit more descriptive.

Move the test namespace deletion logic to the install package

---

cli/sysdump.go
sysdump/sysdump.go

Use --namespace flag for cilium-operator if --cilium-operator-namespace flag is not specified. Otherwise sysdump doesn't execute Cilium-related tasks [^1].
[^1]: https://github.com/cilium/cilium-cli/blob/c29afa4bbe93f90531b7611847f7703db603a27c/sysdump/sysdump.go#L1362
Fixes: aad7a72065fa ("Support operator running in a different namespace")

sysdump: Check --namespace flag for cilium-operator

---

clustermesh/clustermesh.go
connectivity/check/policy.go
k8s/client.go
status/k8s.go
status/k8s_test.go

Currently, the logic to retrieve all logs from Cilium Pods is implemented using `bufio.Scanner`. This might result in errors for long  loglines - hiding the actual error.
```
Error reading Cilium logs: error reading cilium-agent logs for kube-system/cilium-c2sx7: bufio.Scanner: token too long
```
AFAIU, the only reason to use the `bufio.Scanner` is the support for filtering the logs by a given regular expression. But this functionality is not used.
Therefore, this commit removes the filter functionality and the usage of `bufio.Scanner`.

k8s: remove unused filter functionality from k8sclient.CiliumLogs

---

connectivity/check/deployment.go

Please refer to the individual commits for additional details.
Blocked by https://github.com/cilium/cilium/issues/31653

connectivity: Improve coverage of Ingress service

---

RELEASE.md

In case the creation of the release preparation branch fails, the current instructions would push whatever branch was checked out before. Avoid this by explicity specifiying the pr/prepare-$RELEASE branch to be pushed. Also make sure to check out and sync the main branch before modifying README.md and creating the release branch.

RELEASE.md: make sure to push correct release branch

---

.golangci.yml

Currently, the Go version for some linters is configured via separate properties. This has been deprecated in favor of the global config property `run.go` and results in the following warning.
% golangci-lint
WARN [config_reader] The configuration option `linters.staticcheck.go` is deprecated, please use global `run.go`.
WARN [config_reader] The configuration option `linters.gosimple.go` is deprecated, please use global `run.go`.
...
In addition, the new property `run.go` defaults to the Go version defined in the `go.mod` file.
Therefore, remove the deprecated properties completely and depend on the fallback mechanism (`go.mod`).

golangci: remove deprecated go version properties

---

.github/workflows/aks-byocni.yaml

This PR introduces a couple of fixes:
1. Workaround for the Azure BYOCNI workflow: asynchronous Azure OIDC token fetch to avoid token assertion issues.
2. Azure location changed to the `eastus2` that used less intensive.
Workflow run example: https://github.com/cilium/cilium-cli/actions/runs/9063109497/job/24898372774?pr=2546
Workaround for: https://github.com/cilium/cilium-cli/issues/2478

fix: Azure BYOCNI workflow

---

clustermesh/clustermesh.go
defaults/defaults.go
k8s/client.go
status/k8s.go
status/k8s_test.go

* Additionally retrieve and output KVStoreMesh status, when enabled;
* Output troubleshooting tips associated with the most common errors;
Please review commit by commit, and refer to the respective messages for additional information.
Fixes: https://github.com/cilium/cilium/issues/29161

Improve ClusterMesh status reporting to include KVStoreMesh information and troubleshooting tips

---

clustermesh/clustermesh.go

cilium/cilium#28763 decoupled the helm settings to enable the clustermesh-apiserver and provide the list of clusters to connect to. Let's reflect this change to the 'cilium clustermesh disable' command as well, explicitly disabling and resetting the remote clusters configs when invoked, to correctly disconnect from possible leftover clusters.
Fixes: cilium/cilium#32300

clustermesh: reset remote clusters configuration upon disconnection

---

.github/external-targets/certs.yaml
.github/workflows/kind.yaml
cli/connectivity.go
cli/connectivity_test.go
connectivity/builder/builder.go
connectivity/check/check.go
connectivity/check/context.go
connectivity/check/deployment.go
connectivity/check/logging.go
connectivity/check/policy.go
connectivity/suite.go
connectivity/tests/host.go
go.mod
utils/runner/multierror.go
utils/runner/multierror_test.go

This PR introduces connectivity test concurrent run.
The new `test-concurrency` input param can be used to specify a count of K8S test namespaces.
So, most connectivity tests will run concurrently across test namespaces.
The new parameter is marked `hidden` because of the following reasons:
1. test and stabilisation internally (e.g.: in CI)
2. report output must be improved to avoid mess (especially for the `debug` and `verbose` modes). I want to address this in a separate PR.
Command run example: `cilium connectivity test --test-concurrency=5`
Local test in a 4 node kind cluster result:
- ~17 minutes with [`--test-concurrency=1`](https://github.com/cilium/cilium-cli/actions/runs/9057864520/job/24882553506?pr=2496)
- ~5 minutes with …

Connectivity test concurrent run

---

cli/encrypt.go
encrypt/ipsec_key_rotator.go
encrypt/ipsec_key_rotator_test.go

The MD5 and SHA1 IPsec algorithms removed as they are known broken.

encrypt: broken IPsec algo removed

---

sysdump/sysdump.go

Let's avoid to report the file extension twice, as in
```
clustermesh-apiserver-5dc46d9cf7-cg5db-kvstoremesh-troubleshoot-txt-20240517-150749.txt
```
as redundant. The correct version would be
```
clustermesh-apiserver-5dc46d9cf7-cg5db-kvstoremesh-troubleshoot-20240517-150749.txt
```
Fixes: 7029b16aa949 ("sysdump: collect clustermesh-related debug information")

sysdump: don't write extension twice in clustermesh debug files

---

cli/connectivity.go
cli/connectivity_test.go
connectivity/check/action.go
connectivity/check/context.go
connectivity/check/logger.go
connectivity/check/logger_test.go
connectivity/check/logging.go
connectivity/check/test.go
connectivity/suite.go

This PR introduces connectivity tests concurrent logger component.
The concurrency logger used for output aggregation and ordering in case of `--test-concurrency` param is > than 1.
Also, the PR contains fixes for JUnit repot name and some cleanup.

Connectivity tests concurrent logger.

---

k8s/client.go

The blamed commit broke clustermesh status retrieval on Cilium v1.14 when kvstoremesh is enabled. Indeed, although it already included a check to try to figure out whether the kvstoremesh status was not yet exposed by a given Cilium version, it did not account for v1.14 using a completely separate image (and binary name) for kvstoremesh. Let's fix this by adding the appropriate exception.
Fixes: fa7e30e1a5db ("clustermesh: output kvstoremesh status as part of clustermesh status")

Fix clusteremesh status retrieval on Cilium v1.14 when kvstoremesh is enabled

---

cli/connectivity.go
utils/junit/junit.go
utils/junit/junit_test.go

The fix for the connectivity tests JUnit report filename.
The name must be namespace specific in case of tests concurrent run to avoid report override.
Also, JUnit file parameter might contain folder(s).

fix: conn tests JUnit file name

---

go.mod
status/k8s.go

Signed-off-by: Raphaël Pinson <raphael@isovalent.com>

fix: properly count wrapped lines in status output in --wait mode

---

CODEOWNERS
connectivity/builder/builder.go
connectivity/builder/egress_gateway_with_l7_policy.go
connectivity/builder/manifests/client-egress-icmp.yaml
connectivity/builder/manifests/client-egress-l7-http-external-node.yaml
connectivity/check/context.go
connectivity/check/deployment.go
connectivity/check/peer.go
connectivity/tests/egressgateway.go

egress-gateway-with-l7-policy checks if traffic from Pods that are selected by both Egress Gateway Policy and L7 Network Policy is properly SNATed with an Egress IP.
https://github.com/cilium/cilium/pull/32828

connectivity: add egress-gateway-with-l7-policy test

---

connectivity/builder/builder.go
connectivity/builder/local_redirect_policy.go
connectivity/builder/manifests/local-redirect-policy.yaml
connectivity/check/action.go
connectivity/check/context.go
connectivity/check/deployment.go
connectivity/check/peer.go
connectivity/check/policy.go
connectivity/check/result.go
connectivity/check/test.go
connectivity/tests/lrp.go
k8s/client.go
utils/features/features.go
utils/features/features_test.go

This PR introduces local redirect policy tests to the connectivity suite.
In order to break the circular dependency, there is a separate PR on cilium/cilium repo that enables these tests using a custom version of cilium-cli obtained from this PR changes.  Here are successful test runs from the cilium/cilium PR CI runs - 
Runs after addressing review comments - 
https://github.com/cilium/cilium/actions/runs/9409627836/job/25920752091
https://github.com/cilium/cilium/actions/runs/9409627836/job/25919911738
https://github.com/cilium/cilium/actions/runs/9387516652/job/25850621644
https://github.com/cilium/cilium/actions/runs/9377202073/job/25819021276
https://github.com/cilium/cilium/actions/runs/9375976798/job/25815109405 
https://github.com/cilium/cilium/actions/runs/9377202073/job/258183917 …

connectivity: Add local redirect policy tests

---

.github/workflows/gke.yaml
.github/workflows/multicluster.yaml

We are increasingly witnessing test failures in these workflows due to test pods being evicted as nodes are under disk pressure.

gha: increase disk size for GKE clusters

---

connectivity/builder/manifests/client-egress-l7-http-from-any.yaml
connectivity/builder/pod_to_pod_encryption.go

CI run https://github.com/cilium/cilium/pull/32995. Only for WG (see https://github.com/cilium/cilium/issues/33168 for IPsec issues).

connectivity: Extend pod-to-pod encryption tests (for WG)

---

connectivity/check/action.go

When tests have metrics expectations and those expectations are never met, we fail the test. However, the reason for the failure is never displayed unless debug logging is enabled. This commit fixes that by displaying the last assertion error when the test is failed.

connectivity: Display last assertion error on failure

---

.github/cilium-cli-test-job-chart/templates/job.yaml
.github/in-cluster-test-scripts/aks-byocni-install.sh
.github/in-cluster-test-scripts/aks.sh
.github/in-cluster-test-scripts/eks-tunnel.sh
.github/in-cluster-test-scripts/eks-uninstall.sh
.github/in-cluster-test-scripts/eks.sh
.github/in-cluster-test-scripts/external-workloads-install.sh
.github/in-cluster-test-scripts/external-workloads.sh
.github/in-cluster-test-scripts/gke.sh
.github/in-cluster-test-scripts/multicluster.sh
Dockerfile

Install cloud CLIs so that you can run cilium-cli from inside a container and connect to AKS / EKS / GKE clusters.
This commit also changes in-cluster scripts to use bash instead of sh. Some of these scripts are not POSIX-compliant, and they don't work with sh that comes with Ubuntu.
Ref: #2623

Dockerfile: Install aws / azure / gcloud CLIs

---

connectivity/check/context.go

This PR refactors the single node detection. 
Primarily, we now look for the newer `node-role.kubernetes.io/control-plane` taint along with explicitly examining the taint's effect to ensure it is "NoSchedule".

[Connectivity] Refactor single node detection

---

connectivity/builder/builder.go
connectivity/builder/no_fragmentation.go
connectivity/builder/pod_to_pod_encryption.go
connectivity/check/context.go
connectivity/tests/pod.go
defaults/defaults.go

CI run - https://github.com/cilium/cilium/pull/33286. Only ci-ipsec and ci-eks failures are relevant. I will fix them in a PR for cilium/cilium, which bumps CLI vsn.

connectivity: Add pod-to-pod-no-frag to check MTU misconfigurations

---

.github/tools/cilium.sh
.github/workflows/aks-byocni.yaml
action.yaml

Add image-repo and image-tag parameters to the cilium-cli action that set up cilium-cli to run inside a container. Update aks-byocni.yaml to run cilium-cli inside a container using the action instead of using cilium-cli-test-job-chart.
Ref: #2623

action: Add an option to run cilium-cli inside a container

---

.github/workflows/kind.yaml
install/autodetect.go
install/azure.go
install/install.go
k8s/client.go

Replace underscores and dots with dashes, as they are not allowed characters for cluster names. 
~~Additionally perform the same validation already implemented by the latest Cilium version, to exit early and provide a helpful message in case of errors.~~
Edit. I've removed these changes as bumping the Cilium dependency seems to cause a couple of tests to fail quite consistently.
~~(The large diff count is caused by bumping the Cilium dependency to the current main, to reuse the already available validation function. Please review commit by commit)~~

Sanitize the autodetected cluster name

---

cli/connectivity.go
cli/connectivity_test.go

The fix for connectivity tests ExternalTargetCANamespace name.
The name must be namespace specific in case of tests
concurrent run for proper CiliumNetworkPolicy provisioning.
- GKE [workflow](https://github.com/cilium/cilium-cli/actions/runs/9680663068/job/26709342342?pr=2637)
- AKS BYOCNI [workflow](https://github.com/cilium/cilium-cli/actions/runs/9681060475/job/26710815715?pr=2637)
- External workloads [workflow](https://github.com/cilium/cilium-cli/actions/runs/9681060471/job/26710757362?pr=2637)
- EKS tunnel [workflow](https://github.com/cilium/cilium-cli/actions/runs/9681060443/job/26711054780?pr=2637) failed (not enough resources for `test-concurrency=5`)
- EKS ENI [workflow](https://github.com/cilium/cilium-cli/actions/runs/9681060455/job/26711054745?pr=2637) failed (not enough …

fix: ExternalTargetCANamespace name

---

.github/workflows/aks-byocni.yaml

Disable flow validation until #2642 is fixed.

aks: Temporarily disable Hubble Relay

---

cli/sysdump.go
sysdump/sysdump.go

sysdump: fix no Cilium output if operator was not detected

---

.github/workflows/aks-byocni.yaml
.github/workflows/eks-tunnel.yaml
.github/workflows/eks.yaml
.github/workflows/externalworkloads.yaml
.github/workflows/gke.yaml
.github/workflows/multicluster.yaml

The PR adds `test-concurrency` param for connectivity tests concurrent run to speedup CI workflows.
Workflow stats:
- AKS [BYOCNI](https://github.com/cilium/cilium-cli/actions/runs/9687502486/job/26732261111?pr=2639): ~10m vs ~30m before
- EKS [ENI](https://github.com/cilium/cilium-cli/actions/runs/9687502474/job/26732261088?pr=2639): ~10m vs ~27m before
- EKS [tunnel](https://github.com/cilium/cilium-cli/actions/runs/9687502485/job/26732261079?pr=2639): ~8m vs ~19m before
- External [workloads](https://github.com/cilium/cilium-cli/actions/runs/9687502491/job/26732261355?pr=2639): ~6m vs  ~16m before
- [GKE](https://github.com/cilium/cilium-cli/actions/runs/9687502480/job/26732260922?pr=2639): ~10m vs ~27m before
- [Multicluster](https://github.com/cilium/cilium-cli/actions/runs/9687502465 …

ci: speedup workflows

---

.github/workflows/kind.yaml

Simplify the Kind workflow now that we use --test-concurrency flag in all the other workflows.
- Run "Installation and Connectivity Test job" with --test-concurrency=5. This takes around 20 minutes.
- Run "Helm Upgrade Clustermesh" job without --test-concurrency flag so that we run cilium connectivity test without --test-concurrency flag at least once. This takes around 15 minutes.
Also remove --debug flag from all the invocations of cilium connectivity test. It's a bit too noisy, and it makes it difficult to find relevant logs when tests fail.

Simplify Kind workflow

---

Dockerfile

Fix this warning [^1]:
1 warning found (use --debug to expand):
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 6)
[^1]: https://github.com/cilium/cilium-cli/actions/runs/9667251137/job/26668630277#step:6:9076

Dockerfile: Fix a warning

---

.github/workflows/aks-byocni.yaml
.github/workflows/eks-tunnel.yaml
.github/workflows/eks.yaml
.github/workflows/externalworkloads.yaml
.github/workflows/gke.yaml
connectivity/check/deployment.go

Sometimes the perf command fails to schedule pods because there are too many pods [^1]. Add app.kubernetes.io/name label [^2] to connectivity test namespaces, and use the label to delete test namespaces before running the perf command.
[^1]: https://github.com/cilium/cilium-cli/actions/runs/9730132031/job/26852838732
[^2]: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels

connectivity: Label test namespaces

---

action.yaml

Use ${{ github.action_path }} [^1] when accessing cilium.sh. Otherwise this action cannot find the file when it's used in a different repo.
[^1]: https://docs.github.com/en/actions/learn-github-actions/contexts#github-context

action: Use github.action_path when accessing cilium.sh

---

cli/install.go

I accidentally removed this flag in #2328. Validation checks still exist [^1], so it's useful to have this flag.
Tested locally by disabling Kind version check:
% ./cilium install --disable-check=minimum-version
🔮 Auto-detected Kubernetes kind: kind
✨ Running "kind" validation checks
⏭️   Skipping disabled validation test "minimum-version"
ℹ️   Using Cilium version 1.15.6
🔮 Auto-detected cluster name: kind-chart-testing
🔮 Auto-detected kube-proxy has been installed
Fixes: e435b47ba63c ("Delete classic mode install/uninstall/upgrade commands")
[^1]: https://github.com/cilium/cilium-cli/blob/120fcbbb52845e04f94412fb44190ac450080a61/install/autodetect.go#L24-L33

Add --disable-check flag back

---

cli/clustermesh.go
clustermesh/clustermesh.go

In 1.16 we enabled kvstoremesh by default in helm. Currently, cilium-cli was still setting kvstoremesh.enabled to false. Now, if user does not explicitly specify if kvstoremesh should be enabled or disabled, we will rely on default helm value.

kvstoremesh: don't disable by default

---

CODEOWNERS
cli/connectivity.go
connectivity/builder/bgp_control_plane.go
connectivity/builder/builder.go
connectivity/check/check.go
connectivity/check/context.go
connectivity/check/deployment.go
connectivity/check/frr.go
connectivity/check/test.go
connectivity/check/wait.go
connectivity/tests/bgp.go
defaults/defaults.go
k8s/types.go
utils/features/features.go
utils/features/features_test.go

Introduces BGP Control Plane connectivity tests, working with FRR router instance running in the host network namespace on the `node-without-cilium`.
The aim of this PR is mostly to introduce the BGP + FRR testing infrastructure, more testing scenarios need to be added in follow-up PRs. At the moment, we are testing:
- BGPv1 control plane, IPv4 + IPv6 scenario,
- BGPv2 control plane, IPv4 + IPv6 scenario,
- in both scenarios we test PodCIDR advertisements and ClusterIP service advertisements.
<details>
<summary>Example run with debug enabled:</summary>
```
[=] [cilium-test] Test [bgp-control-plane-v1] [80/84]
[.] Action [bgp-control-plane-v1/bgpv1-advertisements/curl-echo-pod-ipv4-0: cilium-test/echo-external-node-89864b5bd-4lzt4 (172.22.0.4) -> cilium-test/echo-same-node-7f896b84-sbqv4 …
```

connectivity: Introduce BGP CP connectivity tests

---

cli/install.go

The upgrade command performs the same validation checks as the install command, so add --disable-check flag to the upgrade command as well.
Fixes: a5598ec8ed0e ("Add --disable-check flag back")

Add --disable-check flag to upgrade command

---

clustermesh/clustermesh.go

The blamed commit explicitly reset the list of remote clusters upon clustermesh deactivation. However, it did so setting the corresponding setting to nil, which in Cilium v1.16 triggers an error due to not matching the schema configured. Let's address this by configuring an empty array instead.
Fixes: b148800cf7a2 ("clustermesh: reset remote clusters configuration upon disconnection")

clustermesh: fix remote clusters configuration reset upon deactivation

---

cli/clustermesh.go
clustermesh/clustermesh.go

Currently, the "clustermesh enable" command lists ClusterIP as one of the supported service types. However, exposing the clustermesh-apiserver via a ClusterIP service is hardly ever a sensible idea, as this component must be reachable from other clusters. Still, this possibility has proved to be sometimes confusing for newbie users, who ended up with a broken setup.
In an effort to prevent these problems, let's explicitly validate the specified service type, and allow only NodePort and LoadBalancer services. In any case, it is still possible to configure a service of type ClusterIP via the helm chart in the handful of very advanced use-cases (if any) which can actually work and benefit from it.
While being there, let's also update the deprecated annotations used to configure internal …

clustermesh: validate service type, and fix deprecated LB annotations

---

connectivity/builder/echo_ingress_l7.go

Add testcase to cover https://github.com/cilium/cilium/issues/32899.
The new testcase has been tested by https://github.com/cilium/cilium/pull/33691, two failing checks are ci-e2e-upgrade and mergeability.

connectivity: Add echo-ingress-l7-via-hostport-with-encryption testcase

---

.github/workflows/kind.yaml
cli/connectivity.go
connectivity/check/check.go
connectivity/check/context.go
connectivity/check/deployment.go

Deploy conn-disrupt test actors only in the first test namespace in case of tests concurrent run to avoid resource wasting. Conn-disrupt tests always run at the beginning, sequentially and in the first test namespace.

connectivity: disrupt deployment improved

---

connectivity/builder/echo_ingress_l7.go

…with cilium 1.16.0 or newer.
Fixes: https://github.com/cilium/cilium-cli/pull/2670

connectivity: echo-ingress-l7-via-hostport-with-encryption only runs with cilium 1.16.0 or newer

---

cli/connectivity.go
cli/connectivity_test.go

Use option.NewNamedMapOptions instead of flags.StringToStringVar to avoid getting lint errors when merging cilium-cli repo to cilium repo [^1].
[^1]: https://github.com/cilium/cilium/blob/main/contrib/scripts/check-viper.sh

flags: Use option.NewNamedMapOptions

---

cli/version.go
connectivity/check/action.go
connectivity/check/context.go
connectivity/check/logger.go
connectivity/check/policy.go
connectivity/check/test.go
connectivity/check/wait.go
connectivity/sniff/sniffer.go
connectivity/tests/health.go
k8s/client.go
status/status.go
sysdump/sysdump_test.go
utils/runner/multierror.go
vendor/github.com/cilium/cilium/pkg/safeio/safeio.go
vendor/modules.txt

3 commits to fix various lint errors to get ready to be merged to cilium/cilium repo:
- Replace sync with github.com/cilium/cilium/pkg/lock
- Replace timer.After with inctimer.After
- Replace io.ReadAll with safeio.ReadAllLimit

Fix lint errors

---

.golangci.yml
bgp/peers.go
bgp/routes.go
clustermesh/clustermesh.go
config/config.go
connectivity/check/context.go
connectivity/check/deployment.go
connectivity/check/frr.go
connectivity/check/policy.go
connectivity/perf/common/metrics.go
connectivity/tests/health.go
encrypt/ipsec_key_status.go
encrypt/ipsec_rotate_key.go
encrypt/status.go
internal/helm/helm.go
k8s/client.go
status/k8s.go
status/status.go
sysdump/sysdump.go
utils/wait/wait.go

Add errorlint linter to be consistent with cilium/cilium configuration [^1], and fix lint errors.
Ref: https://github.com/cilium/design-cfps/pull/9
[^1]: https://github.com/cilium/cilium/blob/3fa34b170493b48ef7befedef72badbd05429b18/.golangci.yaml#L117

golangci-lint: Add errorlint

---

connectivity/check/deployment.go

Deploy perf test actors only in the first test namespace in case of tests concurrent run to avoid resource wasting.
Perf tests always run at the beginning, sequentially and in the first test namespace.

connectivity: perf deployment improved

---

.github/workflows/kind.yaml
cli/connectivity.go
cli/connectivity_test.go

Always suffix test namespace with concurrent group number.
Unhide `--test-concurrency` input param.
Thanks @asauber and @michi-covalent for the idea.
However I think these changes might be breakable for users who rely on test namespace (e.g.: in CI or other automation stuff). WDYT?

connectivity: test namespace suffix

---

.github/node-local-dns/kustomization.yaml
.github/node-local-dns/node-local-dns-lrp.yaml
.github/node-local-dns/node-local-dns.yaml
.github/workflows/kind.yaml
connectivity/builder/builder.go
connectivity/builder/local_redirect_policy.go
connectivity/builder/local_redirect_policy_with_nodedns.go
connectivity/builder/manifests/client-egress-node-local-dns.yaml
connectivity/check/deployment.go
connectivity/check/features.go
connectivity/tests/lrp.go
k8s/client.go
utils/features/features.go

This PR introduces local-redirect-policy-with-node-dns connectivity test that checks if the LRP with node-local-dns setup is properly working.
https://docs.cilium.io/en/stable/network/kubernetes/local-redirect-policy/#node-local-dns-cache
ref: https://github.com/cilium/cilium/issues/33415
context: https://github.com/cilium/cilium-cli/pull/2657#issuecomment-2215725134

connectivity: add local-redirect-policy-with-node-dns test

---

connectivity/check/frr.go
connectivity/tests/bgp.go

This change asserts that BGP peering connections used in the BGP connectivity tests use the BGP timer intervals as configured via Cilium.

connectivity: Assert BGP timer intervals in BGP connectivity tests

---

cli/connectivity.go
connectivity/check/context.go
connectivity/check/junit.go
connectivity/suite.go

The commit introduces JUnit collector component that collects connectivity test data and writes a report into a single file, even if `test-concurrency` parameter is larger than 1.
Fixes: https://github.com/cilium/cilium-cli/issues/2689

connectivity: single JUnit report

---

CODEOWNERS

Assign release-related files that are mostly updated as a part of the release process to cilium-cli-maintainers:
% git log --format='%an' README.md | sort | uniq -c | sort -nr | head -n 3
58 Michi Mutsuzaki
34 Tobias Klauser
8 Thomas Graf
% git log --format='%an' RELEASE.md | sort | uniq -c | sort -nr | head -n 3
39 Michi Mutsuzaki
21 Tobias Klauser
1 Gilberto Bertin
% git log --format='%an' stable-v0.14.txt | sort | uniq -c | sort -nr | head -n 3
1 Michi Mutsuzaki
% git log --format='%an' stable.txt | sort | uniq -c | sort -nr | head -n 3
36 Michi Mutsuzaki
27 Tobias Klauser
1 Andrew Sauber

Assign release-related files to cilium-cli-maintainers

---

connectivity/builder/bgp_control_plane.go

Multiple `WithCondition` statements were causing that only the last one was effective, making version checks ineffective. This combines the conditions into a single `WithCondition` statement per test.

connectivity: Fix ineffective version check in BGP tests

---

.github/kind-config.yaml

opened https://github.com/cilium/cilium-cli/issues/2720 to keep the kind node image up to date. need to figure out why nodes without cilium don't get ready with newer kind node images.
in the meantime let's do this to unblock https://github.com/cilium/cilium-cli/pull/2716.

Pick up kindest/node:v1.21.10

---

connectivity/check/test.go
connectivity/check/test_test.go

Save all the condition functions from WithCondition() instead on only remembering the one from the latest invocation. Run the test if and only if it satisfies all the conditions.
Fixes: #2713

connectivity: Support multiple conditions

---

connectivity/builder/builder.go
connectivity/builder/egress_gateway_with_l7_policy.go
connectivity/builder/manifests/client-egress-l7-http-external-node.yaml

in client-egress-l7-http-external-node CNP instead of the fixed values to accommodate the test namespace and external deployment port change.

connectivity: use TestNamespace and ExternalDeploymentPort params

---

.github/workflows/externalworkloads.yaml
.github/workflows/multicluster.yaml

Shorten cluster names to avoid getting this error:
Error: Unable to install Cilium: execution error at (cilium/templates/validate.yaml:100:5):
The cluster name is invalid: must not be more than 32 characters.
Configure 'upgradeCompatibility' to 1.15 or earlier to temporarily
skip this check at your own risk
Ref: https://github.com/cilium/cilium/pull/33939
edit: added another commit to set cluster.id in externalworkloads.

{externalworkloads,multicluster}: Shorten cluster names

---

CODEOWNERS

Most of the Go code has been moved to cilium/cilium repo [^1], and the only direct dependencies are cilium/cilium and google/gops at this point. I don't think it makes much sense to pull in the vendor team for reviewing new versions of cilium and / or gops. I'm imagining the new release process will look something like this:
- Renovate picks up a new cilium/cilium pre-release from main branch. Pre-releases happen roughly once a month.
- cilium-cli-maintainers team approves and merges the Renovate PR.
- cilium-cli-maintainers team cuts a new cilium-cli release.
[^1]: https://github.com/cilium/cilium/pull/34178

CODEOWNERS: Assign vendor/ to cilium-cli-maintainers

---

Makefile

seeing some build failure on the homebrew side, https://github.com/Homebrew/homebrew-core/pull/181762, and realized the package re-org per https://github.com/cilium/cilium-cli/pull/2762

build: fix CLIVersion ldflag ref

---

Makefile

Follow-up change for https://github.com/cilium/cilium/pull/34666. We need to set the latest stable Cilium version based on stable.txt from the main Cilium repo as it isn't vendored.
> curl it, man.
> 
>   -- @michi-covalent

make: set set latest stable version based on stable.txt

---

action.yaml

Specify --client flag so that the command succeeds even if .kube/config does not exist.
Ref: https://github.com/cilium/cilium/pull/34914

action: Run version command with --client flag

---

Dockerfile
Makefile

Install curl in the release make target so that CILIUM_VERSION gets set properly.
Fixes: #2795
Fixes: #2802

release: Install curl

---

.github/workflows/multicluster.yaml

Use the correct variable to specify the destination context for the clustermesh connect step, which is otherwise left empty:
>   cilium --context gke... clustermesh connect --destination-context ''
Although the workflow is currently working regardless (as the context referring to the second cluster is the default one), that no longer applies when pulling in the latest Cilium CLI changes, as --dst-context has been converted to possibly take a list of contexts.
Fixes: f2fba32482e0 ("multicluster: Run cilium-cli inside a container")

multicluster: correctly specify the dst context to clustermes connect

---

.github/workflows/close-stale-issues.yaml

Copied from https://github.com/cilium/cilium/blob/main/.github/workflows/close-stale-issues.yaml

github: Add a workflow to close stale issues and PRs

---

Dockerfile

Only the Dockerfile for now as discussed with @michi-covalent because it will diverge everytime
taken from the original commit:
--
This way we are not diverging in multiple dockerfiles and we can choose between two targets:
- cilium-cli-ci The original target based on ubuntu and the default
- cilium-cli Only contains the cilium cli based on scratch 
- --

Prepare for #2755 - Dockerfile only

---

.github/workflows/eks-tunnel.yaml
.github/workflows/eks.yaml
.github/workflows/gke.yaml
.github/workflows/kind.yaml
.github/workflows/multicluster.yaml

Once 0.16.20 is merged, we can remove branching and support for the kubectl version.

.github: support native hubble port-forwarding

---

.github/workflows/eks-tunnel.yaml
.github/workflows/eks.yaml
.github/workflows/gke.yaml
.github/workflows/kind.yaml
.github/workflows/multicluster.yaml

Use more robust method for checking if hubble port-forward is successful using netcat.
Do note that the workflows use `on.pull_request_target` therefore the changes will not be reflected in this PR checks, but we've tested these on the isovalent CI with success.
CC @michi-covalent 
Will fix upcoming CI failure caused by: https://github.com/cilium/cilium/pull/35483

.github: use netcat to check hubble port-forward success

---

.github/workflows/kind.yaml
action.yaml

Temporarily set go-version explicitly to avoid hitting this cache restore issue [^1]. We can revert this when Go 1.24 gets released.
Also modify kind.yaml to install Cilium CLI using the local action.
[^1]: https://github.com/actions/setup-go/issues/506

action: Explicitly set go-version

---

.github/workflows/renovate-config-validator.yaml

Add a GHA workflow to validate the renovate configuration when it is changed by a PR.
This was taken from the main cilium repository.

.github/workflows: add validation of renovate config

---

Makefile

Now Cilium CLI sets the default Cilium version without relying on the compile-time flag [^1].
[^1]: https://github.com/cilium/cilium/pull/36344

Makefile: Remove CILIUM_VERSION variable

---

Dockerfile

This is being updated by renovate for not much use. We don't use any fancy or deprecated Dockerfile syntax features so it should be fine to leave this unspecified.

Dockerfile: drop syntax comment

---

.github/renovate.json5

This is mostly the same as https://github.com/cilium/cilium-cli/pull/2913 but done by hand and split into understandable commits.
I've also taken the liberty of dropping a few unused things from the config, that's the first couple of commits.

renovate config migration remake

---

README.md

Cilium v1.14 has gone end of life.

Remove v0.15.22 from the release list

---

.github/tools/cilium.sh

GITHUB_WORKFLOW_REF will be used in future in CI runs via GitHub actions
to identify the workflow where the CLI is running, in order to better
attribute code owners during failures. Pass it through as part of the
GitHub actions scripting.

.github: Pass through GITHUB_WORKFLOW_REF

---

.github/workflows/aks-byocni.yaml
.github/workflows/eks-tunnel.yaml
.github/workflows/eks.yaml
.github/workflows/externalworkloads.yaml
.github/workflows/gke.yaml
.github/workflows/kind.yaml
.github/workflows/multicluster.yaml

This is a prerequisite for using Cilium 1.17 in CI.
Follow https://github.com/cilium/cilium/pull/37428

ci: avoid using deprecated tls.secretsBackend flag

---

.github/renovate.json5
RELEASE.md

Currently, renovate will try to update to the latest patch release, i.e. 1.17.1 at the moment but the stable branches on github.com/cilium/cilium don't contain the cilium-cli/ directory, thus breaking the build on update PRs, see e.g. https://github.com/cilium/cilium-cli/pull/2948
Instead, we should always be vendoring the latest version from main. Drop the renovate configuration accordingly and instead update the github.com/cilium/cilium dependency upon release of a new cilium-cli version.

Always update github.com/cilium/cilium from main

---

action.yaml

- Partially revert commit cc1a61d40 [^1] since Cilium updated the Go version to 1.24 in main branch [^2].
- Change the default go-mod-directory to the top-level directory to match the current code structure in cilium/cilium where go.mod file is only in the top-level directory.
- Set setup-go cache-dependency-path parameter to '**/go.sum' so that caching works regardless of how go-mod-directory parameter is set.
[^1]: https://github.com/cilium/cilium-cli/pull/2871
[^2]: https://github.com/cilium/cilium/pull/37852

action: Clean up the logic to handle go-mod-directory

---

README.md
RELEASE.md

Bumping up the minor version to indicate that there is a behavior change in cilium-cli GitHub Action [^1].
[^1]: https://github.com/cilium/cilium-cli/pull/2956

Prepare for v0.18.0 release

---

action.yaml

Define a priority order for installing a version of the CLI:
- Pick the release version, if specified; or
- Build a version from a local tree, if available and not skipped; or
- Pull from a specified image repository / tag, if specified; or
- Pull from a specified image repository and set it to run inside a
container; or
- Fail out to require the user to specify which one they want.
Related: https://github.com/cilium/cilium/issues/37319
Tasks:

action: Only install a single version

---

.github/workflows/aks-byocni.yaml
.github/workflows/eks-tunnel.yaml
.github/workflows/eks.yaml
.github/workflows/gke.yaml
.github/workflows/images.yaml
Dockerfile

- Make the same change as https://github.com/cilium/cilium/pull/37970 to remove cloud provider CLIs. This way we can use the same Dockerfile for CI and releases.
- Get rid of the step to install kubectl. Let's just use the one that comes in the actions runner.
- Clean up images.yaml workflow a bit. Remove the steps for generating image digest files since we don't currently use them.
- Handle the release environment so that images get pushed to the release repo quay.io/cilium/cilium-cli on tag pushes.

Simplify Dockerfile and clean up docker image workflow

---

Dockerfile

By moving the parts least likely to change first there will be less
layers that have to be rebuild/pushed/pulled.

Optimize image layers

---

Dockerfile

We no longer use the syntax directive in Cilium upstream Dockerfile, they were removed by commit cilium/cilium@005f900c4060 ("docker: Do not specify syntax"). Drop it in the cilium-cli Dockerfile as well and avoid noisy renovatebot PRs updating the synatx version.

Dockerfile: do not specify syntax

---

README.md

The respective workflows were removed in commit 654223e5f45f ("github: Remove cloud provider workflows").

README.md: remove status badges for removed cloud provider workflows

---

RELEASE.md

The v0.10 branch hasn't been maintained for more than 2 years. All releases are cut from the main branch these days.

RELEASE.md: drop reference to v0.10 branch
