.github/workflows/aks.yaml
.github/workflows/eks.yaml
.github/workflows/gke.yaml
.github/workflows/go.yml
.github/workflows/kind.yaml
.github/workflows/multicluster.yaml
Makefile
README.md

~Would it make sense to also adjust the github action templates to make use of the Makefile?~
EDIT: just pushed a commit to do the above.

add a Makefile to build, install and test

---

defaults/defaults.go
go.mod
go.sum
vendor/modules.txt

Bump vendored cilium and install target to v1.9.3

---

.github/workflows/eks-tunnel.yaml
internal/cli/cmd/install.go

Add EKS tunnel CI

---

.github/build
.github/workflows/build-binaries.yaml
.github/workflows/release.yaml

Automate release building

---

.github/workflows/release.yaml

Upload tarball instead of binaries

---

README.md

README: Update badges

---

.github/build
.github/workflows/release.yaml

This ensures that the appropriate version of Go is used.

release: generate release artifacts using docker

---

.github/workflows/multicluster.yaml
clustermesh/clustermesh.go

multicluster: Split test into more steps for simplified troubleshooting

---

.github/workflows/aks.yaml

aks: Re-enable CI

---

clustermesh/clustermesh.go
connectivity/check.go
internal/cli/cmd/clustermesh.go
internal/cli/cmd/hubble.go

See individual commits for details.

Various small cleanups in log/help messages and command invocation

---

hubble/hubble.go
internal/cli/cmd/install.go

disable hubble on uninstall

---

.github/workflows/aks.yaml
.github/workflows/eks-tunnel.yaml
.github/workflows/eks.yaml
.github/workflows/gke.yaml
.github/workflows/kind.yaml
.github/workflows/multicluster.yaml

ci: Run all workflows in intervals every 6 hours

---

connectivity/check.go

This resolves failures like these:
```
---------------------------------------------------------------------------------------------------------------------
🔌 [pod-to-pod] Testing cilium-test/client-6c46bff775-db2rz -> cilium-test/echo-same-node-77fcdfc797-zgc7l...
---------------------------------------------------------------------------------------------------------------------
❌ curl connectivity check command failed: error in stream: command terminated with exit code 7
✅ Drop not found for pod cilium-test/client-6c46bff775-db2rz
❌ RST found for pod cilium-test/client-6c46bff775-db2rz
❌ SYN-ACK not found for pod cilium-test/client-6c46bff775-db2rz
❌ FIN-ACK not found for pod cilium-test/client-6c46bff775-db2rz
✅ Drop not found for pod cilium-test/echo-same-node-77fcdfc797-zgc7l
❌ RST …
```

connectivity: Add readiness probe for connectivity deployments

---

install/install.go
internal/k8s/client.go

Add the conditional parameters necessary to install into a microk8s cluster.
This doesn't do any changes in the Hubble side for now, but it at least gets Cilium installed & running in the cluster.
Supersedes: #105

install: Add support for microk8s clusters

---

connectivity/check.go
defaults/defaults.go

Wait up to 5 seconds for some flows to arrive.

connectivity: Wait for flows to arrive

---

install/install.go

This commit adds the same logic present in the configmap helm template
to disable the `--install-no-conntrack-iptables-rules` option (set to
true by default) in case Cilium is going to be installed in a managed
Kubernetes environment (such as AKS, EKS or GKE) or with a chained CNI
setup.
Signed-off-by: Gilberto Bertin <gilberto@isovalent.com>

install: add support for --install-no-conntrack-iptables-rules option

---

hubble/hubble.go

Since commit 15910bdc1195 ("install: Disable hubble by default") Hubble
is disabled by default on installations with `cilium install`. This
leads to failures on `cilium uninstall` due to the fact that it tries to
disable Hubble first (regardless of whether it was previously enabled):
$ cilium uninstall
🔥 Deleting Relay...
🔥 Deleting Relay certificates...
✨ Patching ConfigMap cilium-config to disable Hubble...
Error: Unable to disable Hubble:  unable to patch ConfigMap cilium-config with patch "[{\"op\": \"remove\", \"path\": \"/data/hubble-tls-key-file\"},{\"op\": \"remove\", \"path\": \"/data/hubble-tls-client-ca-files\"},{\"op\": \"remove\", \"path\": \"/data/enable-hubble\"},{\"op\": \"remove\", \"path\": \"/data/hubble-socket-path\"},{\"op\": \"remove\", \"path\": …

hubble: fix `cilium uninstall` if Hubble is disabled

---

status/k8s.go
status/status.go

Instead of reporting a warning, report the component as disabled.
```
/¯¯\
/¯¯\__/¯¯\    Cilium:         1 errors, 2 warnings
\__/¯¯\__/    Operator:       1 errors, 1 warnings
/¯¯\__/¯¯\    Hubble:         disabled
\__/¯¯\__/    ClusterMesh:    disabled
\__/
```

status: Report Hubble + ClusterMesh as disabled

---

connectivity/check/check.go

When checking whether to enable single node connectivity tests, also
check the individual nodes and exclude the master node from the nodes
where connectivity test pods can be scheduled. Otherwise the multi-node
connectivity test will later fail to schedule pods due to unsatisfied
affinity/anti-affinity:
```
0/2 nodes are available: 1 node(s) didn't match pod affinity/anti-affinity, 1 node(s) didn't match pod anti-affinity rules, 1 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate.
```
Fixes #167

connectivity: check node taints when determining single cluster mode

---

clustermesh/clustermesh.go

`cilium clustermesh status` was inadvertently broken by
https://github.com/cilium/cilium-cli/pull/123 when clusters have not
been connected yet. Fix this by expliticly checking cluster's name and
id instead of checking the number of connections.
Add a warning about missing cluster name and/or id to `cilium
clustermesh enable` with a note that external workloads do not need
either.
Fixes: #166
Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

clustermesh: Fix clustermesh status when clusters are not connected

---

connectivity/check/check.go
defaults/defaults.go
hubble/ui.go

Pin image tags for arm64 support, and update hubble tags

---

.github/workflows/go.yml

Check the correct module vendoring as part of the Go GitHub action.

.github: check Go module vendoring

---

install/certs.go
install/encryption.go
install/install.go

Error was spotted in https://github.com/cilium/cilium-cli/pull/251/checks?check_run_id=2686864068.

install: fix rollback for operator deployment

---

install/azure.go
install/install.go
internal/cli/cmd/install.go

Please see individual commits.
This is a follow-up to #227.

azure: refactor subscription handling + small improvements

---

.github/maintainers-little-helper.yaml

This pull request adds the configuration file for maintainer's little helper.
@aanm What else is needed?

.github: Add maintainer's little helper integration

---

install/azure.go
install/install.go

Commit 6bbb25c3aa67 ("azure: refactor subscription parameter") wasn't
properly `gofmt`ed.

install: gofmt

---

.github/in-cluster-test-scripts/eks-install.sh
.github/in-cluster-test-scripts/eks-tunnel-install.sh
.github/in-cluster-test-scripts/eks-tunnel.sh
.github/in-cluster-test-scripts/eks.sh
.github/in-cluster-test-scripts/external-workloads-install.sh
.github/in-cluster-test-scripts/external-workloads.sh
.github/in-cluster-test-scripts/gke.sh
.github/in-cluster-test-scripts/multicluster.sh
.github/workflows/aks.yaml
.github/workflows/eks-tunnel.yaml
.github/workflows/eks.yaml
.github/workflows/externalworkloads.yaml
.github/workflows/gke.yaml
.github/workflows/go.yml
.github/workflows/kind.yaml
.github/workflows/multicluster.yaml
.github/workflows/release.yaml

Please see individual commits :)

workflows: overhaul and standardize all jobs

---

connectivity/check/action.go

Introduced by commit bc766b94897c ("test: Clarify flow validation
output") (PR #301).

connectivity/check: fix indent-error-flow linter warning

---

connectivity/check/action.go

Fixes: https://github.com/cilium/cilium-cli/issues/293.

test: Implement `--flow-validation=disabled`

---

connectivity/check/deployment.go

Signed-off-by: Steven Armstrong <steven.armstrong@id.ethz.ch>
Fixes #133 (#270)

run test pods/containers with CAP_NET_RAW so ping and friends can work

---

install/azure.go

Changes in #226 broke creation of a new Azure Service Principal when not providing an existing Service Principal for installing Cilium. This happens because Azure adds warnings for preview, deprecated and experimental commands, and incidentally there is one at the moment on the SP create command:
```console
$ az ad sp create-for-rbac --scopes /subscriptions/REDACTED --output json
In a future release, this command will NOT create a 'Contributor' role assignment by default. If needed, use the --role argument to explicitly create a role assignment.
Creating 'Contributor' role assignment under scope '/subscriptions/REDACTED'
The output includes credentials that you must protect. Be sure that you do not include these credentials in your code or check the credentials into your source control. …
```

azure: fix Service Principal creation

---

clustermesh/clustermesh.go
defaults/defaults.go
hubble/hubble.go
hubble/relay.go
install/install.go
internal/cli/cmd/clustermesh.go
internal/utils/utils.go
internal/utils/utils_test.go

Reopening this PR: https://github.com/cilium/cilium-cli/pull/196
Fixes: #187

Validate image version

---

.github/workflows/aks.yaml
install/azure.go
install/install.go

Please see invidivual commits :)

azure: restrict Service Principal scope to Resource Group

---

connectivity/check/deployment.go

Wait until Cilium implements nodeports on all the nodes before starting
the connectivity test. For now it uses `nc` in a client pod to check if
the nodeports are open.
Fixes: #344

check: Wait for nodeports

---

connectivity/check/action.go

Do not fail a test if hubble can't retrieve all the flows.

test: Treat hubble errors as warnings rather than failures

---

connectivity/check/action.go

Try to mitigate test flakes due to hubble failing to return any flows
by retrying longer than normal in that case. This could fix flakes
where no flows were returned for the source pod, but right after flows
were returned for destination pod, and the returned flows include
flows for the source pod.

test: Retry harder if hubble returns no flows

---

clustermesh/clustermesh.go

Wait for the clustermesh-apiserver deployment to be ready in `cilium
clustermesh status`.
This will help debug CI flakes where the
deployment does not progress for long enough for the VM install to
fail.
For example, clustermesh-apiserver may be stuck at Pending state for several minutes as shown in this excerpt from a failed external workloads CI run:
```
kube-system   clustermesh-apiserver-7bb55d69-85g2s                             0/2     Pending     0          7m1s    <none>        <none>                                                <none>           <none>
```

clustermesh: Wait for deployment to be ready

---

install/install.go

This new flag was introduced in Cilium 1.10 and it deprecates the
'masquerade' option. With https://github.com/cilium/cilium/pull/16502
being merged, Cilium-cli was still using the 'masquerade' option which
caused Cilium installation to fail on AKS.

install/aks: set 'enable-ipv4-masquerade' as false

---

.github/in-cluster-test-scripts/eks.sh

This was a leftover from https://github.com/cilium/cilium-cli/issues/57 that was since fixed.
PR for testing workflow changes: #376

workflows: remove test exception from EKS

---

.github/workflows/kind.yaml

Update kind to v0.11.1 and the helm/kind-action to v1.2.0

Update kind and helm/kind-action

---

.github/workflows/kind.yaml
README.md
connectivity/check/context.go

Seems like we had missed some of these.

misc: use hubble command rather than port-forwards

---

install/install.go

On Cilium ≥ 1.10.0, use the `enable-ipv4-masquerade` option rather than
`masquerade` which was used on 1.9.x and earlier.

install: set `enable-ipv4-masquerade` by default on ≥ Cilium 1.10.0

---

.github/in-cluster-test-scripts/eks-tunnel.sh
.github/in-cluster-test-scripts/eks.sh
.github/in-cluster-test-scripts/external-workloads.sh
.github/in-cluster-test-scripts/gke.sh
.github/in-cluster-test-scripts/multicluster.sh
.github/workflows/aks.yaml
.github/workflows/kind.yaml

This should give us some additional information to debug flakes, e.g.
for #361

CI: enable debug logs in connectivity tests

---

connectivity/check/deployment.go

Running `cilium connectivity check` on a Cilium 1.8 cluster currently
fails with:
Error: Connectivity test failed: unable to list external workloads: the server could not find the requested resource (get ciliumexternalworkloads.cilium.io)
Error: Process completed with exit code 1.
This is because support for external workloads was only introduced in
Cilium 1.9.
Fix this by treating such errors as non-fatal in deployment validation.
This will allow to run connectivity checks against Cilium 1.8 as well.
Reported-by: André Martins <andre@cilium.io>
Signed-off-by: Tobias Klauser <tobias@cilium.io>

connectivity/check: support running on Cilium 1.8

---

install/install.go

skip Succeeded pods

---

.github/workflows/externalworkloads.yaml

Retry GCP VM creation

---

sysdump/defaults.go
sysdump/sysdump.go

2 commits:
- remove a duplicate task 😞 
- collect flows by default.

Minor sysdump flow collection fixes

---

.github/workflows/go.yml
.github/workflows/kind.yaml
.github/workflows/release.yaml
Makefile

Also bump the alpine image used for the release build to 3.14.

Update Go to 1.16.7

---

status/k8s.go

add hubble-ui status

---

connectivity/check/deployment.go
defaults/defaults.go

fix #464 
use `default/kubernetes` to test for dns
Signed-off-by: zhaojizhuang <571130360@qq.com>

use `default/kubernetes` to test for dns

---

sysdump/constants.go
sysdump/sysdump.go

Collect hubble relay configmap in sysdump

---

sysdump/sysdump.go

Cilium v1.8 writes the archive name to stdout.

sysdump: Check both stdout and stderr for bugtool archive name

---

install/install.go
internal/cli/cmd/install.go

Cilium v1.11 [has deprecated --native-routing-cidr in favor of a new --ipv4-native-routing-cidr flag][1]. This patch bring the same change in the Cilium CLI.
[1]: https://github.com/cilium/cilium/pull/16646/commits/a66b2f2824522c3129a27552cee435ac7ce11135

install: replace --native-routing-cidr by --ipv4-native-routing-cidr

---

install/gke.go
install/install.go
install/node_init.go
install/uninstall.go

Brings in https://github.com/cilium/cilium/pull/16840 and https://github.com/cilium/cilium/pull/17845, and closes #622. Please see individual commits for details.

Add a node-init script for EKS.

---

defaults/defaults.go

Signed-off-by: Dmitry Kharitonov <dmitry@isovalent.com>

ui: v0.8.5 as default

---

install/install.go

install: remove deprecated cluster roles

---

README.md

Added K3s as a supported environment

---

connectivity/check/context.go
connectivity/manifests/allow-all-except-world-pre-v1.11.yaml
connectivity/suite.go

- connectivity: Run setup & validation before registering tests
- connectivity: Use specific policy depending on Cilium version
Fixes: https://github.com/cilium/cilium-cli/issues/719

Use specific policy depending on Cilium version

---

connectivity/check/check.go
connectivity/check/context.go
connectivity/suite.go
install/install.go
internal/cli/cmd/connectivity.go
internal/utils/utils.go
internal/utils/utils_test.go

This should fix version detection for `cilium/cilium` CI images.
Ref. https://github.com/cilium/cilium-cli/pull/720#discussion_r813626778
See individual commits for details.

Address #720 review comments

---

.github/in-cluster-test-scripts/aks.sh
.github/in-cluster-test-scripts/eks-tunnel.sh
.github/in-cluster-test-scripts/eks.sh
.github/in-cluster-test-scripts/external-workloads.sh
.github/in-cluster-test-scripts/gke.sh
README.md
connectivity/check/action.go
connectivity/check/check.go
connectivity/check/context.go
connectivity/check/deployment.go
connectivity/suite.go
connectivity/tests/perfpod.go
defaults/defaults.go
internal/cli/cmd/connectivity.go

Allow the user to test network performance for [TCP,UDP]_STREAM,[TCP,UDP]_RR,TCP_CRR on a single node, as well as across nodes (if the deployment has > 1 node). 
`>  ./cilium connectivity test --test network-perf`
The user can override some of the default functionality,  
- The number of samples the test captures (default, 1 sample per test). 
- Test duration (default, 30 second per test) 
`> cilium connectivity test --perf --duration 5s --samples 3`
```
🔥 Performance Test Summary
-----------------------------------------------------------------------------------------------------------------------------
📋 Scenario                                           | Test            | Num Samples     | Duration        | Avg value      
--------------------------------------------------------------- …
```

Network performance test

---

hubble/relay.go
hubble/ui.go

hubble: fix installation of 1.10 versions

---

install/azure.go

install: fix AKS installation on Cilium >= 1.12.0

---

install/install.go

install: add support for AWS with CNI chaining

---

hubble/hubble.go
install/install.go

Signed-off-by: Nate Sweet <nathanjsweet@pm.me>

relay: Move Peer Service to Hubble Relay Enablement

---

hubble/hubble.go

The Peer Service file will exist under the hubble subdirectory
in the Cilium Helm chart. Additionally, we should create the Peer
Service before Hubble-Relay is created, as Relay relies on the Peer
Service for communication.
Signed-off-by: Nate Sweet <nathanjsweet@pm.me>

bug: Correct Peer Service Filename; Create Before Relay

---

.github/workflows/aks.yaml
.github/workflows/eks-tunnel.yaml
.github/workflows/eks.yaml
.github/workflows/externalworkloads.yaml
.github/workflows/gke.yaml
.github/workflows/kind.yaml
.github/workflows/multicluster.yaml

Ref: https://github.com/cilium/cilium/pull/19716

Pin kubectl version

---

clustermesh/clustermesh.go

Run `cilium` command in external workload install script with sudo if
user is not root.
Fixes: cilium/cilium#19711

clustermesh: Run `cilium` with sudo in VM install script

---

defaults/defaults.go
install/install.go
install/upgrade.go
internal/cli/cmd/install.go

If hubble relay deployment is present on the cluster, try to upgrade it if needed
https://github.com/cilium/cilium-cli/issues/689
Fixes: https://github.com/cilium/cilium-cli/issues/260

Upgrade hubble relay with cli

---

hubble/hubble.go

hubble: Fix version check for generatePeerService

---

.github/maintainers-little-helper.yaml
CODEOWNERS
clustermesh/clustermesh.go
install/autodetect.go
install/install.go
install/uninstall.go
install/upgrade.go
internal/cli/cmd/sysdump.go
internal/k8s/client.go
sysdump/client.go
sysdump/sysdump.go
sysdump/sysdump_test.go

Two more backports from `master` wrt. the `cilium sysdump` command.

v0.10 backports 2022-05-19

---

install/install.go

This commit is to make sure that you only create IngressClass if it's
required.
Relates: #844 

ingress: Create ingress class if required.

---

sysdump/sysdump.go

Timeout was hardcoded to be 5 seconds, and --hubble-flows-timeout was
not being used.
Fixes #907

sysdump: Use --hubble-flows-timeout flag

---

README.md

Update the badges to accommodate for the renamed AKS BYOCNI workflow and
the additional ASK Azure IPAM workflows.
Ref. https://github.com/cilium/cilium-cli/pull/924

README.md: update AKS test badges

---

connectivity/check/deployment.go

The first step of the connectivity check is to test the DNS.
Since the DNS service pod may be located either on the same node of the client or on any other node, the test may introduce randomness, depending on how the connectivity is actually broken (e.g. same-node connectivity only is broken or across-nodes connectivity only is broken).
To guarantee a reliable check, the connectivity test has been extended to perform the following step for each client:
1) query a DNS server on a pod located on the same node
2) query a DNS server on a pod located on a different node
3) query the DNS service
To perform the first two steps, the already existing `echo-same-node` and `echo-other-node` deployments have been modified to deploy a multi-container pod containing a test CoreDNS server.
The test …

Improve DNS validation in connectivity test

---

.github/workflows/aks.yaml

ci: fix AKS testing on `v0.10`

---

install/install.go

Signed-off-by: Raphaël Pinson <raphael@isovalent.com>

fix(install): exit before helm secret generation in --helm-auto-gen-values mode

---

.github/workflows/go.yaml
.github/workflows/kind.yaml
.github/workflows/multicluster.yaml
.github/workflows/release.yaml
.golangci.yml
Makefile
connectivity/check/ipcache.go
install/azure.go
sysdump/sysdump_test.go

Update Go to 1.19

---

internal/cli/cmd/sysdump.go
sysdump/constants.go
sysdump/defaults.go
sysdump/sysdump.go

sysdump: add tetragon bugtool step

---

.github/workflows/go.yaml
.github/workflows/kind.yaml
.github/workflows/multicluster.yaml
.github/workflows/release.yaml
.golangci.yml
Dockerfile
Makefile

Update Go to 1.19.1, golangci-lint to 1.49.0

---

.github/workflows/gke.yaml
connectivity/manifests/allow-cluster-entity.yaml
connectivity/manifests/allow-host-entity.yaml
connectivity/manifests/deny-all-egress.yaml
connectivity/manifests/deny-all-entities.yaml
connectivity/manifests/deny-all-ingress.yaml
connectivity/suite.go

Couple of more connectivity tests, please refer to individual commit for more details.
I will remote temp commit after first round of review.

connectivity: Add more tests 

---

connectivity/check/action.go
connectivity/check/policy.go
connectivity/filters/filters.go
connectivity/suite.go

Please refer to individual commit for more details.
Fixes #1046

policy: Add support for drop direction and reason

---

sysdump/constants.go
sysdump/sysdump.go

Tested with a toy 3-nodes EKS cluster.

sysdump: Collect k8s leases

---

connectivity/suite.go

This commit is to have stricter validation on dropped traffic to confirm both direction (e.g. ingress vs egress) and reason (e.g. policy deny vs default deny).
Relates: #1095

test/connectivity: Update drop traffic direction and reason (cont)

---

README.md

Prepare for v0.12.5 release

---

README.md

Prepare for v0.12.6 release

---

install/autodetect.go
install/install.go
k8s/client.go

Please see the commit for more details.

kpr: Improve k8s API server endpoint detection to handle Kind

---

README.md

Prepare for v0.12.7 release

---

README.md

Prepare for v0.12.8 release

---

clustermesh/clustermesh.go

In v1.12 we renamed the --enable-host-reachable-services to the --bpf-lb-sock, and then changed the name of the flag in "cilium-cli clustermesh" cmd. This breaks the installations on < 1.12 clusters.
Make the derivation of the flag based on the Cilium vsn.
Reported-by: Jarno Rajahalme <jarno@isovalent.com>
Signed-off-by: Martynas Pumputis <m@lambda.lt>
Fix #1232

clustermesh: Fix --bpf-lb-sock on < 1.12

---

install/install.go

Error message for the user is corrected.

Fix Typo [valye -> value]

---

connectivity/check/deployment.go

Currently, don't show any error message (without debug mode) about why waiting for k8s resources failed. Depending on the k8s resources we are waiting for, we are using different probing methods and each of them should have a different cause of failure. For example, when we wait for the Service to be ready, we use DNS-based probing. In this case, there are some possible reasons that the DNS request fails (e.g., network connectivity issue, kube-DNS is not ready, no DNS entry). However, without the error, there's no clue why it is failing.
This commit puts the last error of the probing at the end of the timeout error message. It helps diagnose why waiting for k8s resources failed.

connectivity: Display last error after waiting k8s resources timeouts

---

install/autodetect.go

By default, the BPF-based masquerading is disabled. Enable the feature if the KPR=strict and a user haven't specified the helm's "bpf.masquerade" option.

install: Auto-enable BPF masquerade

---

go.mod
go.sum
vendor/github.com/cilium/cilium/AUTHORS
vendor/github.com/cilium/cilium/pkg/command/map_string.go
vendor/github.com/cilium/cilium/pkg/defaults/defaults.go
vendor/github.com/cilium/cilium/pkg/logging/logfields/logfields.go
vendor/github.com/cilium/cilium/pkg/option/config.go
vendor/modules.txt

Signed-off-by: Raphaël Pinson <raphael@isovalent.com>

Update cilium vendoring

---

install/autodetect.go

Until \[1\] has been resolved, we need to disable BPF masq.
\[1\]: https://github.com/cilium/cilium/issues/14350
Fixes: 31453a5469 ("install: Auto-enable BPF masquerade")
cc @qmonnet

install: Do not enable BPF masq if ipv6 is enabled

---

.github/dependabot.yml

See commits for details. Follows https://github.com/cilium/hubble/pull/836 which did similar changes in the Hubble CLI repo.

dependabot config updates

---

connectivity/tests/health.go

When the health check fails, the test keeps on retrying.
If the user tries to stop the test prematurely by sending a SIGINT signal,
the pod.K8sClient.ExecInPod function returns an error, as the context is canceled.
due to this, the test would get stuck in an infinite loop.
Now the context is checked for cancellation before continuing to the next loop
Fixes: #1314
Signed-off-by: K Dharmick Sai <dharmicksaik@gmail.com>

Check if context is cancelled before next iteration

---

.github/workflows/go.yaml
.golangci.yml
Makefile
k8s/client.go

Also enable some additional linters and fix a bug found by one of the linters. See commits for details.

Update golangci-lint to v1.51.1

---

.github/workflows/aks-azure-ipam.yaml
.github/workflows/aks-byocni.yaml
.github/workflows/eks-tunnel.yaml
.github/workflows/eks.yaml
.github/workflows/externalworkloads.yaml
.github/workflows/gke.yaml
.github/workflows/kind.yaml
.github/workflows/multicluster.yaml
defaults/defaults.go

Install and use Cilium v1.13.0 by default. See commits for details.

Use Cilium v1.13.0 by default 

---

connectivity/check/action.go
connectivity/check/context.go
connectivity/check/deployment.go
connectivity/check/features.go
connectivity/check/ipcache.go
connectivity/check/peer.go
connectivity/check/test.go
connectivity/check/utils.go
connectivity/suite.go
connectivity/tests/cidr.go
connectivity/tests/client.go
connectivity/tests/dummy.go
connectivity/tests/encryption.go
connectivity/tests/externalworkload.go
connectivity/tests/health.go
connectivity/tests/host.go
connectivity/tests/perfpod.go
connectivity/tests/pod.go
connectivity/tests/service.go
connectivity/tests/world.go

See commit msgs.
Successful run - https://github.com/cilium/cilium/actions/runs/4252182998/jobs/7395488307.
Fix #1139

connectivity: Add IPv6 tests

---

.github/workflows/go.yaml
.github/workflows/kind.yaml
.github/workflows/multicluster.yaml
.github/workflows/release.yaml
Makefile

Release notes: https://go.dev/doc/devel/release#go1.20.2

Update Go to 1.20.2

---

go.mod
go.sum
vendor/github.com/cilium/cilium/api/v1/models/policy_rule.go
vendor/github.com/cilium/cilium/api/v1/models/zz_generated.deepcopy.go
vendor/github.com/cilium/cilium/pkg/command/map_string.go
vendor/github.com/cilium/cilium/pkg/defaults/defaults.go
vendor/github.com/cilium/cilium/pkg/labels/arraylist.go
vendor/github.com/cilium/cilium/pkg/option/config.go
vendor/github.com/cilium/cilium/pkg/policy/api/rule.go
vendor/google.golang.org/protobuf/internal/encoding/text/decode_number.go
vendor/google.golang.org/protobuf/internal/version/version.go
vendor/modules.txt

Need https://github.com/cilium/cilium/pull/24470 to fix this error that happens during cilium connectivity test setup:
connectivity test failed: unmarshaling cilium runtime config json: json: cannot unmarshal array into Go struct field DaemonConfig.NodeEncryptionOptOutLabels of type labels.Selector

vendor: Pick up the latest cilium

---

.github/in-cluster-test-scripts/eks-tunnel.sh
.github/in-cluster-test-scripts/external-workloads-install.sh
.github/in-cluster-test-scripts/gke.sh
.github/in-cluster-test-scripts/multicluster.sh
.github/workflows/kind.yaml
install/install.go

Replace deprecated flags with --helm-set

---

.github/cilium-cli-test-job-chart/templates/job.yaml
.github/cilium-cli-test-job-chart/values.yaml
.github/in-cluster-test-scripts/gke.sh
.github/workflows/gke.yaml
.github/workflows/kind.yaml
hubble/hubble.go
internal/cli/cmd/hubble.go
internal/helm/helm.go

3 commits:
- implement hubble enable / disable commands
- add GKE test coverage for helm mode
- temporary commit to test GKE workflow change. to be removed before merging.

helm mode: Add hubble enable / disable commands

---

connectivity/check/delete.go
defaults/defaults.go
install/helm.go

Fixes: https://github.com/cilium/cilium-cli/pull/1498

Use --set-string for node affinity

---

README.md

Ref: https://github.com/cilium/cilium-cli/issues/1396

Add documentation for helm installation mode

---

README.md
RELEASE.md

Also add a step in the release process to check for dependabot alerts.

Prepare for v0.14.0 release

---

internal/cli/cmd/install.go

The PR #1550 got merged with small nit comments.
This adressed those in a seperate commit.

Address wording an style nits of #1550

---

.github/renovate.json5

Fixes: 930832e59ffe ("Add renovate configuration")
Fixes: #1592

renovate: fix invalid whitespace characters

---

k8s/client.go
sysdump/client.go
sysdump/constants.go
sysdump/sysdump.go
sysdump/sysdump_test.go

Now that Cilium implemented support for CiliumCIDRGroups, let's support dumping it in sysdump.
Fixes: https://github.com/cilium/cilium-cli/issues/1538

Add support for CiliumCIDRGroup CRD

---

internal/cli/cmd/bgp.go

Related to: https://github.com/cilium/cilium/pull/25691

bgp: minor fix to bgp command help output

---

README.md
RELEASE.md

The next release after v0.14.8 will be v0.15.0.

Prepare for v0.14.8 release

---

.github/workflows/eks-tunnel.yaml
.github/workflows/eks.yaml
README.md
install/uninstall.go
internal/cli/cmd/install.go
internal/utils/utils.go
internal/utils/utils_test.go

Use Helm mode by default

---

README.md
RELEASE.md

Prepare for v0.15.0 release

---

README.md

aac4fff48 changed the heading name.

Fix link in reference to helm mode

---

sysdump/constants.go
sysdump/sysdump.go

sysdump: Collect node init Pod logs and DaemonSet

---

.github/workflows/kind.yaml

kind: Upload all the sysdumps

---

.github/workflows/kind.yaml
connectivity/check/deployment.go
connectivity/tests/upgrade.go

Please refer to the individual commit messages for additional details about the specific changes.

Fix connectivity disruption tests for multi cluster scenario

---

sysdump/sysdump.go

fixes: https://github.com/cilium/cilium-cli/issues/1371

Expand warning about big sysdump

---

connectivity/check/deployment.go

Depends on https://github.com/cilium/cilium-cli/pull/1952
cc @jschwinger233

connectivity: Decrease test-conn-disrupt-client interval to 10ms

---

connectivity/check/policy.go
connectivity/check/secrets.go
connectivity/check/test.go

in order to allow hooks to use it

check: export ciliumLogs method

---

clustermesh/clustermesh.go
connectivity/tests/egressgateway.go
internal/utils/utils.go
utils/wait/wait.go

to make them available to hook extensions

utils: export WaitObserver methods into wait package

---

README.md
RELEASE.md

wait for https://github.com/cilium/cilium-cli/pull/2020

Prepare for v0.15.10 release

---

connectivity/check/context.go
connectivity/check/peer.go
connectivity/tests/egressgateway.go

just a few clean ups and an additional helper that will be used in the context of connectivity test hooks

check: turn CurlClientIPCommand into more generic CurlCommandWithOutput 

---

sysdump/sysdump.go
utils/features/features.go

Collect CiliumClusterwideEnvoyConfigs and CiliumEnvoyConfigs custom resources if and only if enable-envoy-config is set to "true".

sysdump: Check if enable-envoy-config is set

---

connectivity/tests/encryption.go

It's going to be enabled on Cilium >= 1.15 after https://github.com/cilium/cilium/pull/29000 has been merged.

connectivity: Detect WG encap on >= 1.15

---

connectivity/check/context.go
connectivity/check/test.go

Connectivity tests counter added to make it more user friendly.

Connectivity tests counter.

---

Dockerfile
Makefile

Ref. https://github.com/cilium/cilium-cli/pull/2223#discussion_r1447185822

Bump alpine images to 3.19

---

.github/workflows/go.yaml

Run the Go workflow when when a pull request is added to a merge queue.
Ref: #2252

Go workflow: Add merge_group trigger

---

README.md

Let's drop the word experimental, and simply call it "Cilium CLI".

README.md: Update the title

---

.github/workflows/eks-tunnel.yaml
.github/workflows/eks.yaml

Pass workflow examples:
- https://github.com/cilium/cilium-cli/actions/runs/7873661347/job/21481669941
- https://github.com/cilium/cilium-cli/actions/runs/7873661359/job/21481631164

AWS OIDC instead of access key.

---

.github/renovate.json5

Onboard action.yaml into the renovate configuration, so that it takes care of automatically updating the version of possible dependencies, such as actions/setup-go.

renovate: additionally manage updates for action.yaml

---

README.md

This is to address the below comment.
https://github.com/cilium/cilium-cli/pull/2285#issuecomment-1926303693

docs: Update version matrix

---

Makefile

fix: update ldflags for local-release

---

defaults/defaults.go
k8s/client.go
sysdump/client.go
sysdump/constants.go
sysdump/defaults.go
sysdump/sysdump.go
sysdump/sysdump_test.go

To improve debuggability of Hubble, capture the TLS related resources for Hubble's auto TLS setup.

sysdump: Capture hubble auto TLS related resources

---

connectivity/check/action.go

This will help with debugging connectivity issues.

Display stderr when ExecInPod action fails.

---

.github/workflows/images.yaml

See https://github.com/cilium/cilium/pull/33216.

gh/workflows: Fix display img digest step

---

connectivity/check/context.go

Sometimes it takes a while for all the nodes to get connected to Hubble Relay in the multicluster workflow [^1]. If Hubble is enabled, don't start running connectivity tests until all the nodes are connected to avoid flow validation failures.
[^1]: https://github.com/cilium/cilium-cli/actions/runs/9664927814/job/26660784590#step:21:1456
Fixes: #2518
Fixes: #2553

connectivity: Ensure Hubble Relay is connected to all the nodes

---

sysdump/sysdump.go

The commit fixes sysdump collection for Windows based clients.

sysdump: fix file separator

---

connectivity/check/junit.go

JUnit collector skip logic fixed.

junit: collector fix

---

.github/kind-config-1.yaml
.github/kind-config-2.yaml
.github/kind-config.yaml

Also update kubeadm.k8s.io API version from v1beta2 to v1beta3.
Ref: #2720

kind: Pick up the latest kindest/node image

---

.github/workflows/lock.yaml

Ref: https://github.com/cilium/design-cfps/pull/9

Lock cilium-cli repo

---

.github/workflows/gke.yaml

github: Increase hubble-event-queue-size

---

.github/workflows/multicluster.yaml

Multicluster workflow started hitting the same issue as #2806 [^1].
[^1]: https://github.com/cilium/cilium-cli/actions/runs/11133691166/job/30941326039?pr=2822#step:17:1261

multicluster: Increase hubble-event-queue-size

---

.github/renovate.json5
action.yaml

Follow up for https://github.com/cilium/cilium-cli/pull/2871

renovate: update Go version in action.yaml

---

.github/tools/cilium.sh
action.yaml

Example use-case: https://github.com/cilium/cilium/pull/37970

gh: add option to specify kubeconfig
