cilium/cilium-cli

- .gitignore
- Makefile
This allows building release binaries for the following platforms:
- darwin/amd64
- linux/386
- linux/amd64
- linux/arm
- linux/arm64
Unfortunately, Windows is not supported yet due to syslog usage by the cilium logger.
This PR is based on how it's done for the Hubble CLI.
NOTE: ~This PR depends on #62~
> add make targets to build release binaries for Linux and MacOS

- clustermesh/certs.go
- clustermesh/clustermesh.go
- hubble/hubble.go
- internal/cli/cmd/clustermesh.go
- internal/cli/cmd/hubble.go
The CA is typically created at install time. Allow creating it on the
fly if needed. We don't do this automatically as the common case will be
that the CA already exists as sharing between clusters is desirable. The
default behavior should thus be to fail if it does not exist.
> hubble/clustermesh: Add --create-ca flag to create CA if needeed

- README.md
Rather than linking the SVG file, link to the workflow results of the
individual tests.
> README.md: add links to GH action status badges

- internal/cli/cmd/install.go
- status/k8s.go
- status/k8s_test.go
- status/status.go
Everything is already set up to take a custom agent and/or operator
image and the Hubble relay image can already be specified as a CLI
options. Thus, wire up the `--agent-image` and `--operator-image` options
for the `install` sub-command. This makes it very easy to install a
custom locally built development image in a cluster, e.g.:
$ cilium install \
--agent-image quay.io/tklauser/cilium \
--operator-image quay.io/tklauser/operator-aws \
--version latest
The second commit contains a small cleanup to re-use the constants from the `defaults` package for the `DaemonSet`/`Deployment` names.
> Allow specifying agent and operator image via CLI options

- internal/cli/cmd/install.go
Commit a855451c7e7a ("internal/cli/cmd: allow specifying agent and
operator image via CLI parameters") broke the operator image
autodetection for AWS and Azure which leads to `operator-generic` being
deployed rather than `operator-{aws.azure}`.
This is due to the fact that `utils.BuildImagePath` will only set the
provided cloud-specific image path if the OperatorImage parameter is
empty. Fix this by making the default CLI option value empty, so the
autodetection will kick in as long as the option is not specified.
Fixes: a855451c7e7a ("internal/cli/cmd: allow specifying agent and operator image via CLI parameters")
> internal/cli/cmd: fix operator image autodetection

- internal/k8s/client.go
Clusters created using `eksctl create cluster--name foo` will have their
cluster name set to `foo.<region>.eksctl.io`. This will break cluster
name autodetection due to the fact that currently, dots are not allowed
in cluster names (see cilium/cilium-cli#71). Thus, replace dots by
hyphens for the purpose of the Cilium CLI.
This will allow to seamlessly use `cilium install` (i.e. without setting
`--cluster-name` explicitly) on `eksctl`-created clusters.
> internal/k8s: fix cluster name autodetection for eksctl created clusters

- install/install.go
This resulted in the pod quota for the operator to be also applied to
the agent DaemonSet.
> install: Fix typo in resource quota

- cmd/cilium/main.go
- internal/cli/cmd/cmd.go
Ever since I added completion for the cilium CLI to my default shell
config, I was bugged by this message when opening a new terminal
session and having no kubectl config:
Unable to create Kubernetes client: invalid configuration: no configuration has been provided, try setting KUBERNETES_
It turns out that initializing the kubernetes client is setup in the
root command as a persistent pre-run.
As we can see, for commands that do not require the client the be setup,
such as `help`, `completion` or `version`, it doesn't make sense to try
to setup the client. In fact, when setting up the client fails, it would
even prevent the command from running. This is particularly annoying
when trying to run "help".
This commit addresses this problem by treating the root command and the
`completion`, …
> cmd: only setup the kubernetes client for commands that require it

- Makefile
Go 1.16 adds macOS ARM64 support so let's build release binaries for Apple silicon.
> release: create release binaries for darwin/arm64 (aka Apple silicon)

- connectivity/test_world.go
Termination of the connection with a mutual RST is valid as well:
```
Feb 19 09:24:01.459: 10.0.1.46:41144 -> 172.217.4.142:443 from-endpoint FORWARDED (TCP Flags: ACK, RST)
Feb 19 09:24:01.459: 10.0.1.46:41144 -> 172.217.4.142:443 to-stack FORWARDED (TCP Flags: ACK, RST)
```
Fixes: #88
> connectivity: Relax flow requirement for world connection termination

- .github/workflows/aks.yaml
The cluster delete can take a long time sometimes so allow for it to
complete
> ci: aks: Relax timeout of 15m to 30m

- connectivity/check.go
- connectivity/filters/filters.go
- connectivity/test_host.go
- connectivity/test_pod.go
- connectivity/test_service.go
- connectivity/test_world.go
Matches on pod IPs instead of just pod names in case the pod name association is not reliable. Also describes flow filters to assist in troubleshooting
```
❌ SYN-ACK and(ip(dst=10.52.2.87),tcp(srcPort=443),tcpflags(syn,ack)) not found for pod cilium-test/client-6c46bff775-sq4mm
```
Related: #102
>  connectivity: Add liberal flow filter and descriptions

- .github/workflows/eks-tunnel.yaml
- .github/workflows/eks.yaml
Tests typically take ~25min to run but sometimes exceeds 30min. Give EKS
tests 45min to complete.
> ci: Give EKS tests 45 minutes to run

- connectivity/check/check.go
Using the busybox version is not compatible on OpenShift due to SELinux.
Fixes: #124
> check: Use standalone ping binary

- install/install.go
Instead of including the GKE node init on datapath GKE, include it on
flavor GKE as it is also needed if a user runs with
`--datapath-mode=tunnel` on GKE.
> install: Use GKE node init for flavor GKE

- .github/workflows/go.yml
- Makefile
Release notes: https://golang.org/doc/devel/release.html#go1.16.minor
> Bump Go to 1.16.2

- connectivity/tests/pod.go
The original code constructed the `curlCommand()` argument as the concatenated string `echo.Pod.Status.PodIP+":8080"` (i.e. pod IP + port 8080).
This works for IPv4, but does not satisfy the IPv6 case in which `curl` requires that the host address is enclosed in square brackets (e.g. `[2001:db8::abcd]:8080`). In a v6-first-dual-stack or v6-only environment, this causes false-negative test results like the following (addresses have been replaced):
```
---------------------------------------------------------------------------------------------------------------------
🔌 [pod-to-pod] Testing cilium-test/client-58dfdc5f6-fkgxg -> cilium-test/echo-other-node-588bf78fbb-jfbbd...
--------------------------------------------------------------------------------------------------------------------- …
```
> Fix pod-to-pod test for IPv6 deployments

- defaults/defaults.go
- hubble/hubble.go
- install/install.go
- internal/k8s/client.go
It has become trivial to enable and disable hubble with ``cilium hubble
enable``.  Disable it by default in the install to minimize the memory
footprint of the default install.
> install: Disable hubble by default

- clustermesh/certs.go
- clustermesh/clustermesh.go
- defaults/defaults.go
- install/autodetect.go
- internal/cli/cmd/clustermesh.go
- internal/k8s/client.go
- status/k8s.go
Various changes to allow external workloads to be used when installing Cilium with the Cilium CLI tool:
- Relax clustermesh validation on "enable"
- Change default service type to NodePort on port 32379
- Set etcd client Common Names to the corresponding user names
- Add external-workload certs
- Auto-detect datapath mode for Kind
These changes are required to run the updated GSG at https://github.com/cilium/cilium/pull/15320.
> VM support fixes

- .github/workflows/aks.yaml
- .github/workflows/eks-tunnel.yaml
- .github/workflows/eks.yaml
- .github/workflows/kind.yaml
- .github/workflows/multicluster.yaml
By default shell scripts in jobs.<job_id>.steps[*].run have fail-fast
behavior, potentially leading to commands in the cleanup step not being
executed. In the worst case this could lead to cloud resources not being
cleaned up, e.g. when `cilium status` fails with non-zero exit status,
the remaining commands will not be run.
Fix this by specifying `shell: bash {0}` for the cleanup step, which
will opt out of the fail-fast behavior.
For details see:
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
For an example see https://github.com/cilium/cilium-cli/runs/2205848981?check_suite_focus=true, where `cilium status` exited with non-zero status due to clustermesh errors, leading to the successive steps in cleanup (i.e. …
> CI: disable fail-fast behavior in cleanup step

- .github/gcp-vm-startup.sh
- .github/workflows/externalworkloads.yaml
This uses a GKE cluster with a GCP VM instance as an external workload.
For now it verifies basic connectivity according to the external
workloads GSG, see
https://docs.cilium.io/en/latest/gettingstarted/external-workloads
> CI: add coverage for external workloads on GKE/GCP

- clustermesh/clustermesh.go
Insetad of duplicating the check, move it into the
(*accessInformation).validate method.
> clustermesh: move access information validation into method

- .github/workflows/aks.yaml
- .github/workflows/eks-tunnel.yaml
- .github/workflows/eks.yaml
- .github/workflows/externalworkloads.yaml
- .github/workflows/gke.yaml
- .github/workflows/kind.yaml
- .github/workflows/multicluster.yaml
The Cilium CLI binary is currently always re-built during `make install`
because the command is executed with `sudo` and thus the build cache of
the root user is used. But the earlier `make` command populating the
cache was run as a normal user.
Fix this by only running `sudo make install` which will also build the
binary due to the respective Makefile target dependency.
This reduces the GitHub actions jobs by about ~50s.
> CI: combine build and install in a single step

- connectivity/filters/filters.go
- connectivity/tests/host.go
The pod-to-host test fails in IPv6 (or v6-first-dualstack) clusters when Hubble is enabled, because the test checks for ICMP(v4) codes 8 and 0 (echo request, echo reply) but the logged flows have ICMPv6 codes 128 (echo) and 129 (reply).
Add a filter for ICMPv6 mimicking the existing ICMPv4 filter, and use `filters.Or()` to make the pod-to-host test IP-version-agnostic.
> connectivity: Add filter for ICMPv6, match ICMPv6 in pod-to-host test

- clustermesh/clustermesh.go
Add the search domains for '\<namespace\>.svc.cluster.local',
'svc.cluster.local', and 'cluster.local' in addition to the kube DNS
server to the VM's DNS configuration. This allows VM to use names
local to its namespace without specifying the fully qualified name.
\<namespace\> is derived from VMs cilium state at runtime so that
the install script works for VMs in different namespaces.
Signed-off-by: Jarno Rajahalme <jarno@covalent.io>
> clustermesh: Add search domains to VM support DNS config

- .github/workflows/aks.yaml
- .github/workflows/eks-tunnel.yaml
- .github/workflows/eks.yaml
- .github/workflows/gke.yaml
- .github/workflows/kind.yaml
- .github/workflows/multicluster.yaml
- hubble/hubble.go
- hubble/relay.go
- internal/cli/cmd/hubble.go
Simplify the local forwarding of the relay port and allow users to run
the command `cilium hubble port-forward`
```
cilium hubble port-forward
Forwarding from 0.0.0.0:4245 -> 4245
Forwarding from [::]:4245 -> 4245
```
> hubble: Add cilium hubble port-forward command

- install/install.go
- install/upgrade.go
- internal/cli/cmd/cmd.go
- internal/cli/cmd/install.go
- internal/k8s/client.go
Adds a new "cilium upgrade" command that sets image tags on all required
container images. The command can later be extended to also apply the
required diff to move between minor releases.
```
cilium upgrade
🚀 Upgrading cilium-operator to version quay.io/cilium/operator-generic:v1.9.5...
🚀 Upgrading cilium to version quay.io/cilium/cilium:v1.9.5...
⌛ Waiting for Cilium to be upgraded...
```
> Install: Upgrade/downgrade support for micro releases

- install/bgp.go
- install/install.go
Following the Helm changes in https://github.com/cilium/cilium/pull/15340, update the CLI accordingly.
See commit msgs.
- install: Add update ability for services/status in Operator
- install: Update Agent and Operator resources for BGP
> BGP support

- defaults/defaults.go
- hubble/hubble.go
- hubble/ui.go
- internal/cli/cmd/hubble.go
Adds the command ``cilium hubble enable --ui``.
> hubble: Add option to deploy UI

- .github/workflows/kind.yaml
- README.md
- install/autodetect.go
- install/install.go
- internal/cli/cmd/install.go
This modifies the `--encryption` flag to a string such that the user can pick a encryption mode, i.e. allowing the user to choose between IPsec or Wireguard.
Enabling Wireguard is basically equivalent to `cilium install --config enable-wireguard=true --config enable-l7-proxy=false`.
Open questions:
- Wireguard in Cilium currently does not work with the L7 proxy. We automatically disable the L7 proxy here if Wireguard is enabled. This might not be needed in future versions of Cilium, I'm not sure what the best approach here would be.
- Old versions of Cilium (e.g. 1.9) do not have support for Wireguard. This means that because the agent is unaware of the `enable-wireguard` ConfigMap option that no encryption will be enabled. Again, I'm not sure what the best approach here should be. …
> install: Add `--encryption=[ipsec|wireguard]` flag

- .github/workflows/aks.yaml
- .github/workflows/eks-tunnel.yaml
- .github/workflows/eks.yaml
- .github/workflows/externalworkloads.yaml
- .github/workflows/gke.yaml
- .github/workflows/kind.yaml
- .github/workflows/multicluster.yaml
- connectivity/check/check.go
- connectivity/suite.go
- connectivity/tests/externalworkload.go
- connectivity/tests/service.go
Test ping connectivity from all pods to external workloads.
"Screenshot" of successful `cilium connectivity test` run with Hubble enabled (note the last test `pod-to-external-workload`):
```
tklauser@orbital:~ % cilium connectivity test
⌛ [gke_cilium-dev_europe-west6-a_test-tklauser-15653] Waiting for deployments [client echo-same-node] to become ready...
⌛ [gke_cilium-dev_europe-west6-a_test-tklauser-15653] Waiting for deployments [echo-other-node] to become ready...
⌛ [gke_cilium-dev_europe-west6-a_test-tklauser-15653] Waiting for CiliumEndpoint for pod cilium-test/client-77bd7f48dd-xmkrk to appear...
⌛ [gke_cilium-dev_europe-west6-a_test-tklauser-15653] Waiting for CiliumEndpoint for pod cilium-test/echo-other-node-86774f89b9-w2v2c to appear...
⌛ …
```
> Add test for pod to external workload connectivity

- connectivity/check/check.go
- internal/cli/cmd/connectivity.go
Treat each --test string as a regular expression matching a substring
in the test name rather than prefix. This makes it simpler to include
or exclude tests based on regular expression matches.
The '!' syntax is retained, so '!' in the beginning of a string
excludes matching tests.
For example, to only test tests that match "world", but not "FQDN":
$ cilium connectivity test --test 'world,!FQDN'
(bash requires single quotes to retain '!')
To only test "pod" tests with an "egress" policy:
$ cilium connectivity test --test 'pod.*egress'
> test: Change `--test` args to regexp matches

- config/config.go
- internal/cli/cmd/config.go
After setting config map changes, Cilium pods need to be restarted for the changes to take effect.
Currently, this is a manual step. Add a new flag to restart the pods by default. 
Tested the changes on a local kind cluster.
> Add restart flag to config set and delete commands

- connectivity/check/check.go
PR #158 accidentally removed the SkipOnAggregation flag for SYN-ACK
flow validation, causing flow validation errors when flow aggregation
is enabled. Fix by adding it back.
Fixes: #158
> check: Skip SYN-ACK validation when flow aggregation is on (again)

- connectivity/check/check.go
- connectivity/check/policy.go
- connectivity/manifests/client-egress-to-fqdns-google.yaml
- defaults/defaults.go
- internal/k8s/client.go
Make policy tests easier to debug by:
1. Use strict decoder for policy YAMLs. Wihtout this any errors in
policy YAMLs are silently ignored, which may lead to confusing test
outcomes.
2. Print out the applied policy in verbose mode. The printout is in
JSON as it was easier to generate.
3. Dump out the Cilium agent logs for the relevant time duration
whenever policy apply or delete fails.
4. Skip running the test traffic if policy apply fails. There is no
point in running the tests if the required policy cannot be applied.
5. Do not try to delete policies if the policy apply failed. Note that
if policy apply succeeds, but Cilium agent still fails to apply the
policy we still have to delete the policy. In this case waiting for
the policy delete to complete in all Cilium agents may time out, …
> test: Dump Cilium logs when policy apply times out

- .github/workflows/images.yaml
This got left out of initial images workflow file, but is required for
builds to pass on gh actions running on master branch.
> ci: build and push master image

- clustermesh/certs.go
- clustermesh/clustermesh.go
- defaults/defaults.go
- hubble/relay.go
- install/certs.go
- install/install.go
- internal/certs/certs.go
- internal/k8s/helpers.go
This PR ensure that all the Secrets containing a TLS keypair are of `kubernetes.io/tls` type. This brings consistency with respect to how we generate certificates [with certgen](https://github.com/cilium/certgen/blob/d9f612a4775d85632acfa9653cade50e1cd2af50/internal/generate/generate.go#L147) and [Helm](https://github.com/cilium/cilium/blob/de8b14eb7816b773ec757ef0847dcfff56d507d2/install/kubernetes/cilium/templates/hubble-server-secret.yaml#L10).
Besides honoring the required `tls.key` and `tls.crt` keys, we also consistently add `ca.crt` to theses Secrets (see https://github.com/cilium/cilium/pull/15443 for context).
Finally, use the newly added `ca.crt` for both Hubble and Relay. This allow compatibility with [cert-manager](https://cert-manager.io/).
After this PR we could consider a …
> add ca.crt to TLS Secrets

- install/azure.go
Remove the --name argument from the `az ad sp create-for-rbac` command
used to create a new service principal as:
* it's not required (if not set the CLI will generate a new one)
* specifying a --name increases the risk of the command to fail in case
a sp with the same name already exists and the user doesn't have
permissions to patch it.
> install: aks: drop --name from service principal creation command

- .github/workflows/multicluster.yaml
- connectivity/check/check.go
- connectivity/check/policy.go
- connectivity/manifests/echo-ingress-from-other-client.yaml
- connectivity/suite.go
- hubble/hubble.go
- hubble/relay.go
- hubble/ui.go
- install/certs.go
- install/install.go
- install/uninstall.go
- internal/cli/cmd/connectivity.go
- internal/cli/cmd/hubble.go
- internal/cli/cmd/install.go
Add ingress policy testing that validates multi-cluster ingress policy enforcement when `cilium connectivity test` is run with `--multi-cluster` option.
Introductory commits add smaller fixes for:
- Avoid creating a 2nd k8s client when not needed
- Enable policy-only test regardless of the `--test` flag options
- Eliminate unnecessary bool member
- Track Cilium pods as PodContexts, apply policies in all clusters
- adds support for ingress TCP flow validation,
- lists Cilium pods only once,
- applies policies in all clusters,
- adds a new policy test case allowing ingress to echo only from one of the clients
- In multi-cluster case `echo-other-node` is located in the destination cluster, so this tests multi-cluster policy enforcement
- Add --pause-on-fail (-p) flag to `cilium connectivity …
> Multicluster policy test fixes

- .github/workflows/aks.yaml
- .github/workflows/eks-tunnel.yaml
- .github/workflows/eks.yaml
- .github/workflows/externalworkloads.yaml
- .github/workflows/gke.yaml
- .github/workflows/go.yml
- .github/workflows/images.yaml
- .github/workflows/kind.yaml
- .github/workflows/multicluster.yaml
When updating a pull request, workflows associated with the previous version continue to run. A way to prevent that and cancel outdated workflows is to use concurrency groups.
This commit handles workflows triggered by pull requests and pushes. We define each concurrency group such that they are unique to the pull request (via PR number) if triggered by event pull_request or to the commit (via SHA) if triggered by event push.
Related: https://github.com/cilium/cilium/pull/16199.
> .github: Cancel outdated PR and push workflows

- CODEOWNERS
This commit adds a rough first version of a CODEOWNERS file to allow us to extend Cilium's review workflow to cilium/cilium-cli.
Not everything is distributed among teams yet, please provide feedback :pray: 
Note: I'm a bit reluctant to assign all of `connectivity/` to @cilium/ci-structure, but unsure what other team(s) could take it.
@cilium/maintainers @cilium/azure @cilium/ci-structure @cilium/contributing @cilium/cli @cilium/hubble @cilium/vendor See new responsibilities. Please speak up if it doesn't look right.
> CODEOWNERS: Initial version

- install/azure.go
- install/install.go
- internal/cli/cmd/install.go
In some cases, e.g. when working with the `cilium-dev` subscription,
leading, Cilium installation fails with the derived subscription ID:
```
$ cilium install --version 1.9.5 --azure-resource-group "${NAME}" --azure-tenant-id $(echo ${AZURE_SERVICE_PRINCIPAL} | jq -r '.tenant') --azure-client-id "${APP_ID}" --azure-client-secret $(echo ${AZURE_SERVICE_PRINCIPAL} | jq -r '.password')
🔮 Auto-detected Kubernetes kind: AKS
✨ Running "AKS" validation checks
✅ Detected az binary
🔮 Auto-detected cluster name: tklauser-test-12960
🔮 Auto-detected IPAM mode: azure
🔮 Auto-detected datapath mode: azure
✅ Using manually configured principal for cilium operator with App ID <redacted> and tenant ID <redacted>
✅ Derived Azure subscription id <redacted>
Error: Unable to install Cilium: unable to execute …
```
> install: allow to set Azure subscription ID

- install/certs.go
- install/encryption.go
- install/install.go
- internal/cli/cmd/install.go
When the `cilium install` command fails, all Kubernetes object already
created by the installer are not automatically deleted. This causes
subsequent installation attempts to fail as some objects already exist:
$ cilium install
🔮 Auto-detected Kubernetes kind: GKE
🔮 Auto-detected cluster name: gke-cilium-dev-europe-west4-a-jibi-cluster
🔮 Auto-detected IPAM mode: kubernetes
🔮 Auto-detected datapath mode: gke
✅ Detected GKE native routing CIDR: 10.32.0.0/14
🚀 Creating Resource quotas...
Error: Unable to install Cilium:  resourcequotas "cilium-resource-quota" already exists
This commit introduces additional logic to delete, in case the
installation fails, all the objects created during the installation
process:
$ cilium install --config install-no-conntrack-iptables-rules=true
..
↩️ Rolling …
> install: rollback installation on failure

- Makefile
If the `golangci-lint` is installed and is the version that is expected, use it for the `check` target, otherwise use the docker container version. This should ease the pain inflicted to MacOS users who suffer from docker being slow to run on their platform.
> make: use local golangci-lint binary to run static checks when available

- .github/workflows/kind.yaml
The Kind workflow was the only one issuing `kubectl wait`
commands. The problem with these after e.g., enabling hubble, is that
kubectl wait can wait for the old instances of the restarted Cilium
pods to become ready, which will fail as these pods will never become
ready. Rely on `cilium status --wait` instead.
> github: Remove `kubectl wait` commands from Kind workflow

- connectivity/manifests/client-egress-to-cidr-1111.yaml
- connectivity/suite.go
- connectivity/tests/cidr.go
- internal/cli/cmd/connectivity.go
This PR contains:
- Scenario `PodToCIDR` for HTTP towards 1.1.1.1 and 1.0.0.1
- CNP `client-egress-to-cidr` containing a `toCIDRSet` for positive and negative egress test coverage
- Some CLI fixes for the `-test` argument
cc @b3a-dev
> connectivity: toCIDR(Set) Scenario and policy coverage

- .github/workflows/aks.yaml
- .github/workflows/eks-tunnel.yaml
- .github/workflows/eks.yaml
- .github/workflows/externalworkloads.yaml
- .github/workflows/gke.yaml
- .github/workflows/kind.yaml
- .github/workflows/multicluster.yaml
This pull request changes the triggers of all tests that spin up clusters to only run on pull requests and every 6h. That matches what is done at https://github.com/cilium/cilium and probably enough to catch potential regressions.
We are limited to 20 concurrent GitHub jobs for the entire Cilium organization so we should avoid running long workflows unless strictly necessary.
> .github: Stop running tests for every push to master

- .github/workflows/release.yaml
This prevents the github-action plugin repository owner from potentially
being able to tamper with data that is being uploaded.
Suggested-by: André Martins <andre@cilium.io>
Signed-off-by: Robin Hahling <robin.hahling@gw-computing.net>
> release: pin skx/github-action-publish-binaries to a specific sha

- .github/workflows/aks.yaml
- .github/workflows/externalworkloads.yaml
- .github/workflows/gke.yaml
- .github/workflows/multicluster.yaml
With `gcloud` and `az`, when deleting a cluster, we can pass a flag to instruct the CLI to return as soon as the query has been sent, without waiting for completion. That is already the default behavior in `eksctl`'s case.
> .github: Speed up cluster cleanups

- .golangci.yml
- clustermesh/certs.go
- clustermesh/clustermesh.go
- config/config.go
- connectivity/check/peer.go
- connectivity/check/policy.go
- connectivity/suite.go
- defaults/defaults.go
- install/autodetect.go
- install/install.go
- internal/cli/cmd/cmd.go
- internal/cli/cmd/connectivity.go
- internal/cli/cmd/install.go
- internal/cli/cmd/status.go
- internal/k8s/client.go
- status/k8s.go
- status/k8s_test.go
- status/status.go
- sysdump/defaults.go
It came to my attention that `golangci-lint` was enabled in 'new' mode, which ignores all existing linter errors present in the codebase. This PR addresses that issue.
Also allowed exported consts without docstrings, as well as dynamic errors. Sentinels are really not required everywhere.
> Address all outstanding linter errors

- install/install.go
It's currently possible to enable the no CT Iptables rules together with
Iptables masquerading, which results in Iptables failing to masquerade
traffic.
With this commit, when this setup is detected, we return an error.
> install: require BPF masq to enable --install-no-conntrack-iptables-rules

- install/autodetect.go
Fix: https://github.com/cilium/cilium-cli/issues/179
Datapath model only printed if auto-detected: https://github.com/cilium/cilium-cli/blob/c098e6d3878b6e29646ffb019cc45dec509a109b/install/autodetect.go#L156
> feat: print out user datapath model

- CODEOWNERS
> CODEOWNERS: Assign `connectivity/` to cilium/policy

- .github/workflows/aks.yaml
- .github/workflows/eks-tunnel.yaml
- .github/workflows/eks.yaml
- .github/workflows/externalworkloads.yaml
- .github/workflows/gke.yaml
- .github/workflows/kind.yaml
- .github/workflows/multicluster.yaml
There's currently a single concurrency group per workflow, `workflow_name-scheduled`, because of a regression in d9957fb ("ci: change all in-cluster test runs to pull_request_target"). This commit started using `github.event.pull_request_target` for the concurrency group, but that variable doesn't exist. As a consequence, scheduled workflows may cancel workflows triggered by pull requests and the other way around.
This pull request also fixes commit f998cca (".github: Stop running tests for every push to master") in which triggers were updated without updating the corresponding concurrency group. That mistake was without consequences, but left unnecessary code.
Fixes: https://github.com/cilium/cilium-cli/pull/212.
Fixes: https://github.com/cilium/cilium-cli/pull/244.
> .github: Fix concurrency groups

- CODEOWNERS
Update code owners for @cilium/ci-structure to include scripts and manifests in `.github/`.
> CODEOWNERS: Update for cilium/ci-structure

- .github/workflows/externalworkloads.yaml
Cilium install in external workloads CI VM times out. Add timestamps
to agent logs to learn more about the timeline.
> github: Add --timestamps to cilium vm logs

- .github/workflows/go.yml
- .golangci.yml
Instead of instantiating a separate job checking out its own copy of the
code, move the module vendoring check to the build job which already has
the code checked out.
Also move the static checks and the module vendoring check before the
build and tests steps.
> .github/workflows: move Go module vendoring check to build checks

- CODEOWNERS
The new github-sec team will include more contributors than just the maintainers, to help scale reviews.
> CODEOWNERS: Give maintainer's code to github-sec team

- .github/cilium-cli-test-job-chart/templates/job.yaml
- .github/in-cluster-test-scripts/multicluster.sh
- .github/workflows/multicluster.yaml
This reverts commit dec9f4fd47cd27f7b40bfee7c88820908d98f61a.
Native routing CIDR in Cilium config in the multicluster setup must
cover all the clusters. Otherwise cross-cluster traffic will be
masqueraded to the source node and ingress policy enforcement in the
destination cluster will drop allowed traffic.
"10.0.0.0/9" is an educated guess that currently works. We probably
should compute the longest possible common prefix from the actual
cluster CIDRs.
Note that since the workflow trigger is `pull_request_target` this will only
take effect once merged to master. This was tested with `pull_request`
trigger prior to pushing this PR.
Fixes: #286
> Revert "workflows: fix missing CIDRs in multicluster install script"

- connectivity/check/action.go
- connectivity/check/check.go
Retry should be done when Retry() return nil, not when it fails.
Set the warning interval so that we get at least one log for
retries. The default was 10 seconds which was equal to the whole flow
retry timeout, so we never saw any logs for retries.
Fixes: #158
> test: Fix flow validation retries

- .github/in-cluster-test-scripts/external-workloads-install.sh
- clustermesh/clustermesh.go
- internal/cli/cmd/clustermesh.go
External workload installs have been mostly "timing out" in CI. Address this on two fronts:
- Add support for and use Cilium agent debug option in external workload install in CI
- Add retries to Cilium agent install in the external workloads, defaulting to 4 times.
> clustermesh: Add debug and retries to external workload install

- connectivity/check/action.go
- connectivity/check/logging.go
Running tests interactively with the default sparse output is a bit
more interesting with some progress indication.  Add a single '.'
character for each executed action when logging is being buffered.
> test: Add progress indicator when buffering logs

- .github/workflows/gke.yaml
We do `kubectl wait` for 15 minutes, and we don't get sysdump if the
workflow gets cancelled.
Ref: https://github.com/cilium/cilium-cli/runs/2816183763?check_suite_focus=true
> gke: Bump up gke timeout to 30 minutes

- connectivity/check/action.go
previous to this commit an error would be returned
with no flows if a Deadline context was provided
to the target method.
so follow the same logic as a Cancel context being passed
in, the switch statement is updated to also return flows
if a Deadline is exceeded.
in this new case all flows received before the Deadline
will be returned.
Signed-off-by: ldelossa <louis.delos@isovalent.com>
> getFlows: support deadline flow returns

- hubble/relay.go
- hubble/ui.go
- install/azure.go
- install/gke.go
- install/install.go
- install/kind.go
- install/minikube.go
- internal/utils/exec.go
- internal/utils/exec_test.go
When a command fails to execute, its args are shown in the slice syntax
which makes it cumbersome to copy&paste said command for further
analysis, e.g.
Error: Unable to install Cilium:  unable to execute "az [aks show --resource-group foo-test-12960 --name foo-test-12960]": exit status 3
Change the command args to be printed as a space separated string, so
they can be easily copy&pasted from the error message:
Error: Unable to install Cilium: unable to execute "az aks show --resource-group foo-test-12960 --name foo-test-12960": exit status 3
Also consistently log the stdout/stderr of the invoked command on error.
> Log output and print command as string on error when invoking external commands

- CODEOWNERS
Most of the code under /connectivity doesn't require knowledge about
the policy engine. Re-assign it to @cilium/cli so that the review
responsibility is a bit more distributed.
> CODEOWNERS: Assign /connectivity to @cilium/cli

- .github/workflows/aks.yaml
- .github/workflows/eks-tunnel.yaml
- .github/workflows/eks.yaml
- .github/workflows/externalworkloads.yaml
- .github/workflows/gke.yaml
- .github/workflows/multicluster.yaml
adds the necessary if guards to all schededuled CICD
jobs to stop them from running on forks.
Signed-off-by: ldelossa <louis.delos@isovalent.com>
> cicd: guard scheduled jobs from running on forks

- install/minikube.go
We accidentally broke `minikube version` exec in #226.
> install: fix minikube exec command

- hubble/hubble.go
- internal/cli/cmd/hubble.go
- internal/k8s/client.go
- internal/utils/utils.go
Hubble Relay and UI do not function properly if they are not managed by
Cilium. This commit modifies `cilium hubble enable` command to wait for
Cilium pods to become ready after the restart before deploying them.
Fixes #334
> hubble: Wait for Cilium to start before deploying relay/ui

- connectivity/check/action.go
- connectivity/check/check.go
- connectivity/check/deployment.go
- Only consider ICMP drops for ICMP test
- Show all matched flows on failure
- Add HTTP visibility annotation to `echo-other-node` deployment and DNS visibility annotations to `client` pods. This provides for richer flow validation even without policies being applied
- Fix DNS flow validation
- Expand flow results properly in Merge()
> Flow validation fixes

- install/install.go
- internal/cli/cmd/install.go
When a CNI binary plugin is not available, kubelet will use the next one
to setup thc container's networking. Due this behavior, cilium-cli
should wait until cilium-agent containers are up and running to
guarantee that Cilium's CNI binary and configuration are deployed in the
host. Thenceforth cilium-cli can safely restart the pods managed by other
CNI plugins which will cause kubernetes to schedule a new pod and that pod
will be managed by Cilium.
> install: wait until Cilium DS is up and running before restarting pods

- install/autodetect.go
- internal/cli/cmd/install.go
I got bitten trying `cilium install --version 1.10.0-rc1` (notice the missing `v` prefix). `cilium install --help` wasn't helpful about the expected "format" of the `--version` flag.
I've considered checking and adding the `v` prefix to `version` in `utils.BuildImagePath` when it was missing, but ultimately elected against it in order to support using non-version tags (e.g. `stable`). Maybe we could try to do something smart like checking against `^\d+\.\d+\.d+` and adding the `v` prefix if it matches, happy to hear thoughts about this.
> handle default image and versions at the flag level

- internal/cli/cmd/install.go
This reverts commit 03bbc81da1c161b045ed195d0f62c362d142d1b6.
fqOperatorImage() sets the default image based on k.params.DatapathMode
so that utils.BuildImagePath() uses the correct default operator image.
With the commit being reverted, however, the install command never uses
the default operator image because k.params.OperatorImage is always set
to quay.io/cilium/operator-generic.
Ref: https://github.com/cilium/cilium-cli/blob/03bbc81da1c161b045ed195d0f62c362d142d1b6/install/install.go#L1115
> Revert "install: set the default images at the cli flag level"

- connectivity/check/deployment.go
this PR partially reverts https://github.com/cilium/cilium-cli/pull/277. there is no issue in the PR itself, but looks like there is a potential cilium bug with nodeport when used with http visibility annotation in eks. 
i'll follow up with more details about the nodeport issue in https://github.com/cilium/cilium-cli/issues/355
all the recent failures seem to be hitting the same issue: https://github.com/cilium/cilium-cli/actions/workflows/eks.yaml?query=event%3Aschedule
> Partially Revert #277

- .github/workflows/go.yml
Before this patch, git diff was used to ensure that Go modules were properly vendored. While it could catch a failure to update a vendored module, it would not fail when a module was not vendored (untracked).
This patch uses git status instead of git diff, effectively catching untracked vendored modules as well.
> ci: fix the go vendoring check

- .github/workflows/eks.yaml
- install/aws.go
- install/install.go
- install/uninstall.go
Instead of deleting the `aws-node` DaemonSet, which is permanent, we can be gentler and just evict its pods by setting a node selector that won't ever be matched (unless someone wants it to by explicitly setting the required label on a node).
This allows `cilium uninstall` to gracefully revert the `aws-node` `DaemonSet` to its previous state, as it might contain customizations that would otherwise be lost.
> install: don't delete the 'aws-node' DaemonSet

- .github/workflows/eks-tunnel.yaml
- .github/workflows/eks.yaml
- .github/workflows/externalworkloads.yaml
- .github/workflows/gke.yaml
- .github/workflows/multicluster.yaml
Timestamps are very useful when investigating a unknown CI failure. An
example where timestamps would yield us more information is for example
when a job runs into a timeout, such as e.g.
https://github.com/cilium/cilium-cli/runs/2904654177 where we suspect
that it might have run a bit longer than usual, but it's hard to tell.
Signed-off-by: Sebastian Wicki <sebastian@isovalent.com>
> workflows: Add `--timestamps` to `kubectl logs`

- internal/cli/cmd/status.go
- status/k8s.go
- status/status.go
This is an attempt to fix cilium/cilium#16636 - in the linked issue, `cilium status --wait` did continue even though there were still Hubble related warnings as the server was still initializing:
```
Run cilium status --wait
/¯¯\
/¯¯\__/¯¯\    Cilium:         1 warnings
\__/¯¯\__/    Operator:       OK
/¯¯\__/¯¯\    Hubble:         1 warnings
\__/¯¯\__/    ClusterMesh:    disabled
\__/
DaemonSet         cilium             Desired: 2, Ready: 2/2, Available: 2/2
Deployment        cilium-operator    Desired: 1, Ready: 1/1, Available: 1/1
Deployment        hubble-relay       Unavailable: 1/0
Containers:       cilium             Running: 2
cilium-operator    Running: 1
hubble-relay       
Image versions    cilium             quay.io/cilium/cilium-ci:7f20b3abd6837913f0deff225c301bcc11d3da3f: 2 …
```
> status: Do not ignore warnings by default

- clustermesh/clustermesh.go
- internal/cli/cmd/clustermesh.go
`(*K8sClusterMesh).Status` is only called from `newCmdClusterMeshStatus`
which sets `log bool` to `true`. Remove the parameter, also from the called
methods where appropriate.
> clustermesh: remove always true `(*K8sClusterMesh).Status log bool` parameter

- .github/in-cluster-test-scripts/external-workloads-install.sh
- README.md
Currently the external workloads test doesn't use Hubble. Enable it
during installation, which will help to debug failures happening during
the test.
> .github: enable Hubble relay in external workloads test

- .github/workflows/multicluster.yaml
Switching to environment variable declared at the top, rather than declared in the step and pushed as environment variable afterwards.
PR for testing workflow changes: #378
> workflows: refactor firewall rule name in multicluster test

- connectivity/check/action.go
- connectivity/check/check.go
- connectivity/check/context.go
- connectivity/check/logging.go
- connectivity/tests/cidr.go
- connectivity/tests/client.go
- connectivity/tests/externalworkload.go
- connectivity/tests/host.go
- connectivity/tests/pod.go
- connectivity/tests/service.go
- connectivity/tests/world.go
[@ti-mo]
This PR swaps out polling the Hubble ring buffer for flow streaming, which does not risk losing out on flows in between polls. On high-traffic clusters, the Hubble ring might get completely flushed out by the time a second poll comes in. Many workarounds for this have been merged in past weeks, but it was a bit of a losing battle.
This approach doesn't execute as quickly (since Hubble Relay buffers flows to re-order them) but we might be able to improve things over time there. We might be able to get away with completely disabling event re-ordering, but it's currently not possible to do without redeploying Hubble, which the connectivity test suite can't do.
Worth noting: the Hubble flow filter is now configured to only capture traffic related to the Pod executing the test. This …
> Stream flows from Hubble instead of repeatedly polling ring buffer

- install/uninstall.go
Wait for the test namespace to be terminated when the `--wait` flag is
specified to avoid the situation where the next connectivity check fails
to deploy resources because the test namespace is in Terminating state.
Ref: #370
> uninstall: Wait for the test namespace to be terminated

- CODEOWNERS
> Set the default code owner to @cilium/cli

- internal/k8s/client.go
- sysdump/client.go
- sysdump/constants.go
- sysdump/sysdump.go
Adds support for collecting EKS-specific data — namely the `kube-system/aws-node` `DaemonSet`, if present, and any `eniconfigs` and `securitygrouppolicies` that may be present as well. Useful when Cilium is running in chaining mode. Also includes some cleaning-up bits.
> sysdump: support collecting eks-specific data

- clustermesh/clustermesh.go
- connectivity/check/deployment.go
- install/install.go
- internal/k8s/client.go
From the method name alone one might assume it to return a `bool` rather
than an `error`. Rename the method to avoid this confusion.
This is also in line with the `CheckDaemonSetStatus` method which serves
the same purpose for `DaemonSet`s.
> install: rename `DeploymentIsReady` to `CheckDeploymentStatus`

- .github/workflows/externalworkloads.yaml
We are sometimes hitting the following failure when creating the GCP VM:
```
ERROR: (gcloud.compute.instances.create) Could not fetch resource:
- The resource 'projects/***/regions/us-west2/subnetworks/default' is not ready
```
From GCP documentation, this comes from simultaneous resource operations: https://cloud.google.com/compute/docs/troubleshooting/troubleshooting-vm-creation
Since the GKE cluster creation is asynchronous, I suspect it is conflicting with the GCP VM creation. Reversing setup order.
PR for testing workflow changes: #377
> workflows: invert external workloads setup

- README.md
- connectivity/manifests/client-egress-to-fqdns-cilium-io.yaml
- connectivity/suite.go
- connectivity/tests/world.go
Use [jenkins.]cilium.io for FQDN tests to reduce external dependencies.
Ref: #367
> check: Replace [www.]google.com with [jenkins.]cilium.io

- connectivity/check/action.go
- connectivity/check/context.go
- connectivity/check/logging.go
- connectivity/check/test.go
- connectivity/tests/dummy.go
This proved a bit difficult to use in practice. With output of successful test runs now being hidden in CI, things need to fail to pop up. We cannot have things failing and throwing warnings without anyone noticing.
Failed finalizers will now cause an error. Finalizers are not supposed to fail, at least not silently.
Errors polling the Hubble buffer now also fail the test, but this behaviour is already being removed in the open Hubble streaming PR. (#319)
Note: `ConnectivityTest` still has `Warn(f)`, but it's purely cosmetical and not integrated into the rest of the test suite.
This is an alternative proposal to #327.
> connectivity: remove Warn(f) from Test and Action

- clustermesh/clustermesh.go
- hubble/hubble.go
- install/install.go
- install/uninstall.go
- internal/cli/cmd/clustermesh.go
This PR fixes a fairly minor aesthetic issue when running some `cilium` sub-commands; there is no explicit confirmation that an operation finished successfully. In some cases, one may safely assume a successful operation in the absence of any error messages, but I think this makes it more obvious, and gives the opportunity to indicate a next step, especially for the more common operations like `install`.
I perused the `cilium` help output and identified a few candidates where a message like this might be helpful. I left some out because I felt it wasn't necessary (those that shell out to `kubectl port-forward` for example) but if a reviewer feels this list is incomplete, I'm happy to add to it. Same applies to any call to actions I may have missed an opportunity to include.
I also fixed a …
> Add helpful success message to select subcommands

- clustermesh/clustermesh.go
Fixes: #384
Fixes: c171080ef434 ("clustermesh: Wait for deployment to be ready")
> clustermesh: only wait for apiserver deployment if `--wait` is specified

- install/azure.go
Without using the `k.azExec` helper, the user may have the az binary
configured to output to a different format other than `json`, which will
cause unmarshalling errors.
Signed-off-by: Chris Tarazi <chris@isovalent.com>
> install: Fix incorrect use of az command

- .github/workflows/kind.yaml
- Unneeded since we enable relay righ after anyway, which already requires waiting for status to be ready afterwards.
- Since by default we auto-rollback on `cilium install` failure once the hitting the wait timeout, this also clashes with the post-test information gathering step in case of error during `cilium install`.
- Consistent with other workflows.
> workflows: do not wait when installing on Kind

- connectivity/check/action.go
- connectivity/check/deployment.go
- connectivity/check/policy.go
- internal/k8s/exec.go
- internal/utils/ctrlcreader.go
Add TTY to ExecInPod() to cancel command execution on timeout. Add a
new ExecInPodWithTTY() to allow the caller to proceed in parallel and
stream stdin and stdout. util.SyncBuffer can safely be used with
streamed stdout, while utils.CtrlCReader can be used as stdio that
sends a CTRL-C CTRL-D sequence when closed, which should tell the
remote execution to stop.
Based on local testing using TTY has negligible effect on test
execution speed.
> k8s: Use TTY to cancel execution

- .github/workflows/eks-tunnel.yaml
- .github/workflows/eks.yaml
- README.md
The EKS workflows suddenly started failing with:
Error: couldn't create node group filter from command line options: --spot is only valid with managed nodegroups (--managed)
On Jul 2 at around 15 CEST
(https://github.com/cilium/cilium-cli/actions/runs/992727965). The
release of eksctl 0.55.0 coincides with this time frame. As we pin the
EKS workflows to the latest eksctl release, it is likely that this
caused the failures.
Pin the eksctl to 0.54.0 for now which doesn't seem to exhibit this
behavior.
Ref: https://github.com/weaveworks/eksctl/issues/3929
> .github/workflows: use eksctl 0.54.0

- .github/workflows/multicluster.yaml
This changes the multicluster CI action to run cilium-sysdump in both clusters.
Follow-up according to https://github.com/cilium/cilium/pull/16712#issuecomment-872369863
> ci/multicluster: Run sysdump in both clusters

- .github/in-cluster-test-scripts/eks-uninstall.sh
- .github/workflows/eks-tunnel.yaml
- .github/workflows/eks.yaml
In 619f9d5a7b799e3a43ec6af42ac7a3f3e1d83c8d, we improved the way the CLI handles the `aws-node` DaemonSet by using a node selector to evict its pods, allowing us to simply remove the selector on uninstall for a transparent user experience.
We build upon the existing workflow testing:
- Move up `aws-node` number of pods scheduled check right after install and node group have been created, which should be the earliest point at which we can verify if patching the node selector worked.
- Add an additional test at the end to uninstall Cilium and check that backtracking worked on the node selector patching.
- Add same testing to the `eks-tunnel` workflow. Because why not.
This is a follow-up to #208.
> workflows: enhance `aws-node` DaemonSet testing

- clustermesh/clustermesh.go
- hubble/hubble.go
- hubble/relay.go
- install/install.go
- internal/cli/cmd/hubble.go
- internal/k8s/client.go
This PR auto-detects the Relay image version when invoking `cilium hubble enable`.
It uses the exact same mechanism as `cilium clustermesh enable`, as both
`clustermesh-apiserver` and `hubble-relay` share the version number with Cilium.
With this change, users who install a non-default Cilium version via
`cilium install --version v1.x.y` will not have to pass
`--relay-version` to `cilium hubble enable` anymore, as the recommended
version is auto-detected.
> hubble: Auto-detect Relay version 

- clustermesh/clustermesh.go
- internal/cli/cmd/clustermesh.go
Add --config option to pass command line parameters to
clustermesh-apiserver. Useful for turning on --debug, etc.
> clustermesh: Support --config option

- .github/workflows/aks.yaml
- .github/workflows/eks-tunnel.yaml
- .github/workflows/eks.yaml
- .github/workflows/externalworkloads.yaml
- .github/workflows/gke.yaml
- .github/workflows/kind.yaml
- .github/workflows/multicluster.yaml
- internal/cli/cmd/sysdump.go
- sysdump/sysdump.go
We are deprecating python cilium-sysdump.zip soon.
—
(@bmcustodio) This PR also contains a fix for sysdump itself: since sysdump tasks can submit subtasks, it may happen for small values of `--worker-count` that at some point all worker goroutines are stuck at `Submit` calls. This addresses that by setting the actual number of worker goroutines to the minimum necessary to `Submit` and still being able to continue processing work.
> actions: Use cilium sysdump

- internal/k8s/client.go
When a DaemonSet or Deployment is updated, it might take a while for the
status field to reflect the status of the updated version. If we check
the status too soon, there is a high chance that we are checking an
outdated status.
Therefore, check the observedGeneration field first, before reading out
the status flag. This ensures that the reported status actually refers
to the most recent desired state.
Recommended reading: https://alenkacz.medium.com/-250728868792
FWIW: I'm not sure we actually have hit this problem in practice. I just noticed it while debugging something else.
> k8s: Check observedGeneration in status

- internal/cli/cmd/version.go
Before this patch:
```
cilium-cli: v0.5-dev@pr/kaworu/version-report-cilium-version-08338b2 compiled with go1.16.2 on linux/amd64
```
After:
```
cilium-cli: v0.5-dev@pr/kaworu/version-report-cilium-version-08338b2 (v1.9.4 images) compiled with go1.16.2 on linux/amd64
```
> version: report the cilium images version

- .github/workflows/eks-tunnel.yaml
- .github/workflows/eks.yaml
Commit 59785a9f9c7c (".github/workflows: use eksctl 0.54.0") pinnned
eksctl to v0.54.0 to work around an issue in eksctl v0.55.0. That issue
was fixed upstream and v0.56.0 released, so revert back to using the
latest eksctl version.
Ref: weaveworks/eksctl#3929
> .github/workflows: use latest eksctl version

- go.mod
- install/install.go
- install/install_test.go
- internal/cli/cmd/install.go
- vendor/modules.txt
The --version flag doesn't always maps to a Cilium version. For example,
Cilium CI jobs use commit SHAs as image tags. This flag allows you to
explicitly provide the "base" Cilium version being installed so that the
install command can configure Cilium accordingly.
> install: Add a hidden --base-version flag

- .github/workflows/aks.yaml
- .github/workflows/eks-tunnel.yaml
- .github/workflows/eks.yaml
- .github/workflows/externalworkloads.yaml
- .github/workflows/gke.yaml
- .github/workflows/kind.yaml
- .github/workflows/multicluster.yaml
Otherwise it's difficult to figure out why the connectivity check
timed out.
Ref: https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#job-status-check-functions
> Run "Post-test information gathering" step on cancellation

- Makefile
This allows users to overwrite the GO environment variable while still
using CGO_ENABLED=0. This for example is useful when testing
pre-releases of the Go toolchain, e.g. `make GO=go1.17rc1`.
Follows cilium/hubble#560
> Makefile: introduce GO_BUILD variable

- .github/in-cluster-test-scripts/eks-tunnel.sh
- .github/in-cluster-test-scripts/eks.sh
- .github/in-cluster-test-scripts/external-workloads.sh
- .github/in-cluster-test-scripts/gke.sh
- .github/in-cluster-test-scripts/multicluster.sh
- .github/workflows/eks-tunnel.yaml
- .github/workflows/eks.yaml
- .github/workflows/externalworkloads.yaml
- .github/workflows/gke.yaml
- .github/workflows/multicluster.yaml
The post-test information gathering steps were previously self-contained and became split between the actual workflow step and in-cluster jobs logs in #212.
In parallel, `sysdump` became a subcommand of the CLI and we switched to using it in post-test information gathering in #405.
However, we explicitly do not want to run PR-built `cilium` in the context of a `pull_request_target`-triggered privileged workflow, as it would allow an attacker to leak the repository's secrets.
Our proposal is to use the latest stable version of the CLI in the post-test information gathering step. This is acceptable as the purpose of this step is retrieving information, not testing the actual `cilium` commands run in the step -- this is done as part of the in-cluster jobs.
Should a workflow developer …
> workflows: use latest stable CLI in post-test information gathering

- sysdump/sysdump.go
Previously we only collected regular container logs, but missed the init
container logs. Gather these as well, they can be useful for debugging.
> sysdump: Collect also init container logs

- .github/workflows/aks.yaml
- .github/workflows/eks-tunnel.yaml
- .github/workflows/eks.yaml
- .github/workflows/externalworkloads.yaml
- .github/workflows/gke.yaml
- .github/workflows/multicluster.yaml
- defaults/defaults.go
As recommended to users, cilium-cli should also set the clusters with
taints. This guarantees that Cilium is properly configured and
application pods can start successfully.
> .github: create clusters with taints

- .github/in-cluster-test-scripts/eks-tunnel.sh
- .github/in-cluster-test-scripts/eks.sh
- .github/in-cluster-test-scripts/gke.sh
- .github/in-cluster-test-scripts/multicluster.sh
- .github/workflows/aks.yaml
- .github/workflows/kind.yaml
Since we start a background process for port-forwarding Relay, we must check if it actually succeeded or failed before allowing workflows to continue.
We also standardize a 10s allowance time for port-forward to start.
This is a follow-up to the discussion here: https://github.com/cilium/cilium-cli/pull/336#discussion_r659661872
> workflows: check status of Relay port-forward

- connectivity/check/action.go
- connectivity/check/policy.go
- connectivity/check/test.go
- connectivity/manifests/client-egress-l7-http.yaml
- connectivity/manifests/client-egress-only-dns.yaml
- connectivity/manifests/client-egress-to-fqdns-cilium-io.yaml
- connectivity/manifests/echo-ingress-l7-http.yaml
- connectivity/suite.go
- connectivity/tests/world.go
- internal/cli/cmd/connectivity.go
Best reviewed per commit.
- Added test `client-egress-l7` for HTTP filtering with and without `toFQDNs`. Only client Pod 'other' is allowed to generate HTTP traffic.
- Some fixups to the yaml parser and error reporting.
- Run PodToWorld calls to google.com from all client Pods.
- Execute `connectivity.Run()` inside its own goroutine.
> connectivity: egress HTTP and policy w/ toFQDNs

- .github/workflows/aks.yaml
- .github/workflows/eks-tunnel.yaml
- .github/workflows/eks.yaml
- .github/workflows/externalworkloads.yaml
- .github/workflows/gke.yaml
- .github/workflows/multicluster.yaml
This should help clarify that any changes to workflow files or workflow scripts should be tested from a PR using the `pull_request` trigger before merging.
> workflows: add warning/explanation for testing workflow changes

- .github/workflows/eks-tunnel.yaml
- .github/workflows/eks.yaml
- .github/workflows/externalworkloads.yaml
- .github/workflows/gke.yaml
- .github/workflows/multicluster.yaml
Verify the checksum of the downloaded stable CLI tarball in the
post-test information gathering stage.
Also make the curl invocation less verbose and remove ineffective
newlines from log messages while at it.
> .github/workflows: verify checksum when installing latest stable CLI

- .github/in-cluster-test-scripts/eks-tunnel.sh
Following merge of #251, testing on EKS in tunnel mode is now reliably broken due to an issue in upstream: cilium/cilium#16975
This type of failure was already happening before #251, but the PR made it very evident as before we were only running checks from a few random pods (which would sometimes work) and are now running checks from all pods, drastically increasing the chance of hitting at least one failure.
Since the test setup is not to blame and this is an actual issue with Cilium in tunnel mode, we disable the failing tests until upstream issue is fixed.
> workflows: add test exceptions to EKS tunnel workflow

- .github/workflows/aks.yaml
- .github/workflows/eks-tunnel.yaml
- .github/workflows/eks.yaml
- .github/workflows/externalworkloads.yaml
- .github/workflows/gke.yaml
- .github/workflows/multicluster.yaml
`kubectl wait --for=condition=complete --timeout=X` behaviour is a bit counterintuitive: it waits until either the job succeeds or timeout is hit. When the job fails, it does not stop waiting: it will continue waiting until timeout is hit.
For watching for failures, `--for=condition=failed` should be used. However, this will likewise wait until either the job fails or timeout is hit, and will not stop waiting if the job succeeds.
`kubectl wait` unfortunately does not allow waiting for multiple conditions. To work around this, we set up two concurrent background waits for both conditions, and actively wait for the first one to end.
This will ensure we do not wait for the whole allocated timeout everytime there is an error during the in-cluster script execution.
> workflows: fix in-cluster job kubectl wait

- .github/in-cluster-test-scripts/eks-tunnel.sh
Turns out I can't `bash`. I had tested `--test` in a test workflow but without the comments, which I added after for documentation...
Fixes 1bf9ca7edfbfa89e0a116888c79ea87a68a65333
> workflows: fix test exceptions to EKS tunnel workflow

- .github/workflows/externalworkloads.yaml
Seems like `ubuntu-2010` got phased out and replaced by `ubuntu-2104`.
Switching to LTS image `ubuntu-2004-lts`.
> workflows: fix external workloads GCP VM image

- .github/workflows/kind.yaml
- internal/cli/cmd/sysdump.go
- sysdump/constants.go
- sysdump/defaults.go
- sysdump/sysdump.go
Optionally collect hubble flows as a part of sysdump. This PR adds two
new flags to the sysdump subcommand:
--hubble-flows-timeout
Timeout for the flow collection task. Default to 5 seconds.
--hubble-flows-count
Specifies the --last flag to pass to hubble observe command. Default
to zero, which disables the flow collection altogether. Note that the
actual number of flows that get collected might be different from the
value specified by this flag.
The output file can then be passed to hubble observe command, for example:
cat hubble-flows-cilium-nq247-20210729-220228.json | hubble observe
> sysdump: Collect hubble flows

- .github/workflows/aks.yaml
- .github/workflows/eks-tunnel.yaml
- .github/workflows/eks.yaml
- .github/workflows/externalworkloads.yaml
- .github/workflows/gke.yaml
- .github/workflows/multicluster.yaml
Doing this has two advantages:
- Behavior is similar to what we currently have on `cilium/cilium` and what we had on `cilium/cilium-cli` before #212, with the logs to the various `cilium` commands displayed immediately on execution.
- When a job fails, the failing step is automatically expanded in GitHub Actions workflow run view. This will avoid the need to manually open the post-test gathering step to know why a job failed.
> workflows: display logs in job execution step

- .github/workflows/aks.yaml
- .github/workflows/eks-tunnel.yaml
- .github/workflows/eks.yaml
- .github/workflows/externalworkloads.yaml
- .github/workflows/gke.yaml
- .github/workflows/multicluster.yaml
In #471, we refactored in-cluster jobs log retrieval to be displayed immediately in the same step as the one waiting for job execution to end.
Unfortunately, this only works when the job succeeds, as if the job does not then a non-0 exit code is received and the step immediately stops due to fail-fast being enabled by default in workflows.
Since we are manually handling exit codes, we disable fail-fast behaviour.
Also, we fix exit codes not being properly handled for EKS uninstall steps.
Fixes: e20c76976fde976e52603608810c1c034bf2c016
> workflows: fix logs not being displayed on failure

- .github/workflows/externalworkloads.yaml
Increase the retry count from 3 to 10. I have seen 3 consecutive
failures a couple of times 😐
Ref: https://github.com/cilium/cilium-cli/actions/runs/1113449756
> external workload: Increase the VM creation retry count

- connectivity/check/deployment.go
Add error to the debug output for ipcache check failures. This should
help solve #361.
> test: Add error detail to ipcache check failures

- Makefile
- RELEASE.md
- internal/cli/cmd/version.go
Simplify the release process a bit
- Get rid of VERSION file and use `git describe --tags --always`.
- Update stable.txt after the release is published to avoid the
situation where Cilium CI tries to fetch a version that hasn't
been released.
Ref: https://git-scm.com/docs/git-describe#_examples
> Simplify the release process a bit

- internal/cli/cmd/sysdump.go
We've been using the sysdump command for a while in both cilium and
cilium-cli CI workflows and it's been stable.
> sysdump: Remove the Hidden flag

- .github/workflows/go.yml
- internal/cli/cmd/sysdump.go
The change in PR #481 wasn't properly formatted, leading to a
golangci-lint failure on master:
https://github.com/cilium/cilium-cli/runs/3310670546
Fix it by running `goimports -w internal/cli/cmd/sysdump.go`.
Also fix the `golangci-lint` GH action configuration to disable the `only-new-issues` which seems to lead to static checker failures correctly failing tests on PRs. See #484 for an example run.
> internal/cli/cmd: fix formatting linter issue

- connectivity/check/deployment.go
Validate resolved service IP when waiting for service to become
available.
This will help avoid test flakes where kube-dns is returning a stale
IP of a service that was just removed, e.g., when running test with
`--force-deploy`.
Fixes: https://github.com/cilium/cilium/issues/16867
> test: Validate Service IP

- internal/cli/cmd/cmd.go
- internal/cli/cmd/version.go
Show the running version of cilium
Fixes #131
> Add support for displaying the running Cilium version

- install/install.go
- install/install_test.go
- internal/cli/cmd/install.go
Always set the base version to the current default version and rework
the parsing in `(*K8sInstaller).getCiliumVersion` to fall back to the base
version in case of a non-parseable version. This avoids the confusing log
message, e.g. when using `cilium install --version latest`:
Unable to parse the provided version latest, assuming it's =1.10.0
Also reword the log message to hopefully be a bit less confusing.
Fixes #491
> install: set base version to current default version

- connectivity/check/check.go
- connectivity/check/deployment.go
- internal/cli/cmd/connectivity.go
Add `--skip-ip-cache-check` flag with the default set to true. This is
meant to be a temporary flag while we investigate what's causing the flake.
Ref: #361
> Add a flag to disable the ipcache check

- connectivity/check/action.go
DNS exchange happens first, it's useful to have it validated even if
the actual test traffic fails to validate.
Retry flow matching again if all flow requirements can not be
met. Start the new round from the flow following the previous first
match. This effectively retries flow matching from different L4
connections, as the ephemeral source port found from the first match
is fixed for the remaining requirements. By skipping the previous
first match the match can succeed on a different L4 connection.
For example, if successful DNS reply from proxy is required, it may be
on a different UDP or TCP port than the first DNS resolution exchange
that may have failed.
This capability was inadvertently removed in https://github.com/cilium/cilium-cli/pull/319.
Merge flow validation results for each …
> Fix flow validation breakage

- connectivity/check/deployment.go
- internal/cli/cmd/connectivity.go
Follow-up for #503 to address
https://github.com/cilium/cilium-cli/pull/503#discussion_r699117235
Also add a comment so we don't forget to re-enable the check again once
issue #361 is resolved.
> internal/cli/cmd: mark `--skip-ip-cache-check` as hidden

- connectivity/check/action.go
- connectivity/check/test.go
- Move pause from test to action so that new no test traffic will be generated after the failing action
- Suppress logs for 0 flows received
> Test failure output improvements

- connectivity/check/action.go
- connectivity/check/peer.go
- connectivity/check/policy.go
- connectivity/filters/filters.go
- connectivity/suite.go
- connectivity/tests/common.go
- connectivity/tests/service.go
- connectivity/tests/world.go
Add support for validating test command exit code. This is useful for
separating different kind of error conditions, like HTTP errors
vs. connect or DNS timeouts.
L3/L4 policy drops cause curl timeouts (exit code 28). It looks like
we do not yet have any tests that actually get drops from the HTTP
proxy, which would be classified as an HTTP error (exit code 22).
Expose URL path to policy expectation logic. This helps returning
expected test outcomes when an HTTP policy filters by path.
Add filter for L7 drops.
Add new action to tests "pod-to-world" scenario where the target is
"google.com/index.html". Without policies this should work, but in
"to-fqdns" test case this is not allowed by the egress policy.
> test: validate exit code and add HTTP drop testing

- clustermesh/clustermesh.go
- status/k8s.go
- status/k8s_test.go
- status/status.go
Fix #495 
Add managed endpoint count to status command
Signed-off-by: zhaojizhuang <571130360@qq.com>
> Add managed endpoint count to status command

- connectivity/check/test.go
- install/uninstall.go
Previously, the CNPs created during the connectivity test referenced `cilium-test` in `matchLabels` as opposed to the user-specified namespace. This commit addresses that by looking up potential matches and doing the proper replacement.
> connectivity: use the right test namespace in cnps

- .github/workflows/go.yml
Make sure the windows build is tested on PRs as well.
Also change the build commands to build `cmd/cilium` explicitly.
Fixes: fbf0c3392c01 ("make: build Windows binary for release")
> .github/workflows: build windows binaries in cross-build stage

- connectivity/check/deployment.go
- connectivity/check/policy.go
- defaults/defaults.go
- hubble/relay.go
- install/install.go
- internal/cli/cmd/sysdump.go
- internal/k8s/client.go
- sysdump/constants.go
- sysdump/defaults.go
- sysdump/sysdump.go
Please check individual commits for details.
> sysdump: collect 'clustermesh-apiserver' + improvements

- connectivity/manifests/client-egress-l7-http.yaml
- connectivity/manifests/client-egress-to-fqdns-one-one-one-one.yaml
- connectivity/suite.go
- connectivity/tests/world.go
Tentative fix for #367.
We have two main hypothesis around why connections to external domains are flaky:
- The external domain itself is unreliable.
- The external domain works fine, but CoreDNS is unreliable.
`cilium.io` is hosted on single non-HA EC2 instance, which is definitely the most robus thing out there. We propose switching to
`one.one.one.one` as a quick fix to check if that helps with the reliability.
If yes, we will evaluate moving to a HA system that we control ourselves (e.g. a DNS zone hosted at a major provider).
If not, we will investigate the CoreDNS hypothesis.
> Switch pod to world testing from `cilium.io` to `one.one.one.one`

- Makefile
See individual commits for details.
Noticed while trying to create a new `v0.9.0` release, see the failed build at https://github.com/cilium/cilium-cli/runs/3526736152?check_suite_focus=true
> Fix `make release` target

- Makefile
- RELEASE.md
* Fix the `git tag` invocation in `RELEASE.md` to expand the release version in the tag message
* Actually build windows release binaries
> More release process fixes

- .github/ISSUE_TEMPLATE/bug_template.md
- .github/ISSUE_TEMPLATE/failing_test_template.md
- .github/ISSUE_TEMPLATE/feature_template.md
- SECURITY.md
Labels automatically added via issue templates have been adjusted from their original name to match the names from `cilium/cilium`.
> Add issue templates and security policy

- connectivity/check/deployment.go
The node placement for `client2` is not currently fixed such that a given test (e.g., `client-egress-l7/pod-to-pod/curl-3`) may be covering different packet paths on distinct runs (e.g., `pod->local pod` or `pod->remote pod`). This nondeterminism can be a bit confusing when debugging as a failure on a specific packet path may appear under various names.
This pull request fixes the placement of `client2` to the same node as `client`, via an affinity rule.
> test: Always deploy `client2` on same node as `client`

- .golangci.yml
- connectivity/check/action.go
- connectivity/tests/cidr.go
- connectivity/tests/client.go
- connectivity/tests/externalworkload.go
- connectivity/tests/host.go
- connectivity/tests/pod.go
- connectivity/tests/service.go
- connectivity/tests/world.go
- status/k8s.go
- status/status.go
The first three commits fix various issues found by the additional linters, the last commit enables these linters and configures them accordingly.
See individual commit messages for details.
> Enable additional linters in golangci-lint configuration

- clustermesh/clustermesh.go
- hubble/relay.go
- install/install.go
Follow https://github.com/cilium/cilium/pull/17367:
It seems that these volumes were wrongly given permission 420 instead of
0400, giving write permission to the group. In all instances, the actual
volumeMounts were set to readonly so this change should have no effect
but better be more cautious about permissions for secrets.
Reported-by: Robin Hahling <robin.hahling@gw-computing.net>
Signed-off-by: Tobias Klauser <tobias@cilium.io>
> Ensure defaultMode=0400 for projected volumes containing secrets

- connectivity/check/deployment.go
Use the provided port name, not the service name for ServicePort.
Before:
```
ports:
- name: echo-other-node
nodePort: 31244
port: 8080
protocol: TCP
targetPort: 8080
```
After:
```
ports:
- name: http
nodePort: 31244
port: 8080
protocol: TCP
targetPort: 8080
```
> connectivity/check: use correct ServicePort name

- .github/workflows/multicluster.yaml
The multicluster workflow uses `go run` but doesn't explicitly install a
specific Go version. Thus, in some cases an older Go version might be
used which leads to failures such as:
```
vendor/k8s.io/client-go/plugin/pkg/client/auth/exec/metrics.go:21:2: cannot find package "." in:
/home/runner/work/cilium-cli/cilium-cli/vendor/io/fs
```
Fixes #554
> .github/workflows: install Go for `go run` in multicluster job

- .github/dependabot.yml
We update these dependencies manually all at once.
> .github: let dependabot ignore k8s deps

- internal/cli/cmd/sysdump.go
- sysdump/sysdump.go
This adds an optional flag which allows users to specify additional pod label selectors, which will be used to collect collect logs of additional pods matching that selector in the Cilium namespace.
The flag allows for multiple selectors, e.g. `--extra-label-selectors key=value --extra-label-selectors foo=bar,baz=bat` will select any pods with the `key=value` label OR any pods with both the `foo=bar` AND `baz=bat` labels.
Example usage:
```console
cilium sysdump --extra-label-selectors k8s-app=kube-dns
```
> cmd: Add --extra-label-selectors log collector

- internal/k8s/client.go
- sysdump/client.go
- sysdump/constants.go
- sysdump/sysdump.go
- sysdump/tasks.go
> sysdump: collect CiliumEgressNATPolicy and CiliumLocalRedirectPolicy resources

- connectivity/check/context.go
- connectivity/suite.go
The first commit ensures tests are executed in the order they are registered. The second commit implements a mitigation for https://github.com/cilium/cilium-cli/issues/367. See commits for details.
I filed https://github.com/cilium/cilium/issues/17459 to keep track of this bug in Cilium.
Fixes: https://github.com/cilium/cilium-cli/issues/367.
> test: Reorder tests to mitigate DNS resolution flake

- RELEASE.md
The `brew bump-formula-pr` command expects the version without `v`
prefix. Strip it from `$RELEASE` for that command.
> RELEASE.md: fix version in brew command

- README.md
- cmd/cilium/main.go
- internal/logging/logging.go
The cfssl library logs to stdout by default, leading to confusing
messages during various `cilium` commands, e.g.
```
$ cilium install
🔮 Auto-detected Kubernetes kind: kind
✨ Running "kind" validation checks
✅ Detected kind version "0.11.1"
ℹ️  using Cilium version "v1.10.4"
🔮 Auto-detected cluster name: kind-chart-testing
🔮 Auto-detected IPAM mode: kubernetes
🔮 Auto-detected datapath mode: tunnel
🔮 Custom datapath mode: tunnel
🔑 Generating CA...
2021/09/23 13:05:01 [INFO] generate received request
2021/09/23 13:05:01 [INFO] received CSR
2021/09/23 13:05:01 [INFO] generating key: ecdsa-256
2021/09/23 13:05:01 [INFO] encoded CSR
2021/09/23 13:05:01 [INFO] signed certificate with serial number 287136694468458141817041413205774711456458631957
2021/09/23 13:05:01 [INFO] generate received …
```
> Disable cfssl log messages

- .github/in-cluster-test-scripts/aks.sh
- .github/in-cluster-test-scripts/eks-tunnel.sh
- .github/in-cluster-test-scripts/eks.sh
- .github/in-cluster-test-scripts/external-workloads-install.sh
- .github/in-cluster-test-scripts/gke.sh
- .github/in-cluster-test-scripts/multicluster.sh
- .github/workflows/kind.yaml
- clustermesh/clustermesh.go
- hubble/hubble.go
- install/install.go
- install/upgrade.go
- internal/cli/cmd/hubble.go
- internal/cli/cmd/status.go
- status/k8s.go
- status/k8s_test.go
- status/status.go
Like on install and upgrade, use a `K8sStatusCollector` to wait for Cilium
to be fully ready before deploying Hubble Relay. Moreover, report the
status in case Cilium didn't become ready within the given timeout.
The first commit refactors some common code in preparation for the second commit, which implements the actual functionality. The third commit changes `cilium hubble enable` to - by default - wait for the Hubble deployments to be ready (this behavior can be disabled using `--wait=false` as with other commands). The fourth commit drops the now superfluous `cilium status --wait` commands after `cilium hubble enable` from CI.
See individual commit messages for details.
Fixes #164
Fixes #389
> Wait correctly for Cilium to be ready before deploying Hubble Relay

- internal/k8s/client.go
The fact that `v2alpha1` types are currently not added to the scheme may
cause errors during, for instance, sysdump execution. In particular,
`CiliumEgressNATPolicy` resources may be skipped altogether.
> client: add 'v2alpha1' types to scheme

- status/k8s.go
The error returned by `(*K8sStatusCollector).status` is always nil, so it
can be omitted.
> status: remove always nil `(*K8sStatusCollector).status` error return

- .github/workflows/go.yaml
- .github/workflows/kind.yaml
- .github/workflows/multicluster.yaml
- .github/workflows/release.yaml
- Makefile
While at it also update golangci-lint to 1.43.0.
> Update Go to 1.17.3

- install/install.go
In commit bf2c1f99, we switched `kube-proxy-replacement` to disabled by default. We didn't change the default setting for BPF masquerading, even though it requires `kube-proxy-replacement` to be enabled. As a result, default installation result in a warning when BPF masquerading is forcefully disabled.
This pull request disables BPF masquerading by default to fix it. We could enable BPF masquerading when `kube-proxy-replacement` is enabled by the user, but it seems more confusing than anything.
Fixes: https://github.com/cilium/cilium-cli/pull/136.
> install: Disable BPF masquerading by default

- .github/kind-config-1.yaml
- .github/kind-config-2.yaml
- .github/kind-config.yaml
Bump kindest/node to v1.19.11 (latest for k8s 1.19) to support testing
on arm64, as arm64 native images have are available with these versions:
v1.14.10
v1.15.12
v1.16.15
v1.17.17
v1.18.19
v1.19.11
v1.20.7
v1.21.1 - v1.21.2
v1.22.0 - v1.22.4
> kind: Bump kindest/node image to support testing on arm64

- .github/dependabot.yml
To properly update Cilium and Hubble, the replace directives need to be updated as well, something the bot can't do.
> .github: let dependabot ignore Cilium and Hubble dependencies

- clustermesh/certs.go
- hubble/hubble.go
- install/certs.go
- internal/certs/certs.go
- internal/cli/cmd/clustermesh.go
- internal/cli/cmd/hubble.go
Per the [Setting Up Hubble Observability](https://docs.cilium.io/en/stable/gettingstarted/hubble_setup/#hubble-setup) and the [Setting Up Clustermesh](https://docs.cilium.io/en/stable/gettingstarted/clustermesh/clustermesh/#clustermesh) documentation users should expect the `cilium hubble enable` and `cilium clustermesh enable` commands to work as described without having to pass the `--create-ca` flag. 
This PR:
* Splits the `client.GetSecrets` function out of the `LoadCAFromK8s` function in `internal/certs/certs.go` into a new `GetCASecret` function.
* This simplifies `LoadCAFromK8s` by making it only load the CA and not both get the secret data from K8s and load the CA.
* This also simplifies checking whether the CA exists.
* Updates `StoreCAInK8s` to return the pointer for the secret …
> Cilium CA: Autogenerate Cilium CA if it is missing

- install/autodetect.go
- install/upgrade.go
Use the correct operator image for `cilium upgrade` on AKS or EKS. Also fix a duplicate log message and a log message typo.
See commit messages for details
Fixes #407
> upgrade: determine correct operator image on AKS/EKS

- internal/cli/cmd/hubble.go
Commit 33d86603f56d ("hubble: deprecate and hide `cilium-ready-timeout`
flag") deprecated the `cilium-ready-timeout` flag for cilium-cli v0.9.3
which was released in the meantime. Remove it now for the upcoming
v0.9.4 release.
> hubble: remove deprecated `cilium-ready-timeout` flag

- defaults/defaults.go
- internal/cli/cmd/install.go
Install Cilium 1.11.0 by default.
> Update Cilium to 1.11.0

- internal/k8s/client.go
- internal/utils/utils.go
When cilium is installed with 'cilium install --version="-ci:1234"'
this version string is added to the standard image names. For the
Cilium agent this becomes "quay.io/cilium/cilium-ci:1234". Detect this
when decoding version from a running Cilium pod by finding the part
after the dash in the image reference, so that the detected version
becomes "-ci:1234". This allows hubble to be enabled without passing
--hubble-version parameter explicitly in this case.
> version: Detect special running Cilium versions

- internal/k8s/copy.go
- internal/k8s/exec.go
- internal/k8s/pipe.go
- internal/k8s/pipe_test.go
- sysdump/client.go
- sysdump/constants.go
- sysdump/sysdump.go
- sysdump/sysdump_test.go
This PR tries to address the below points mentioned in #616 
- Compress bugtool output before transfer
- Add resume capability if there is any transfer error
Please refer to individual commit for more details
Testing was done as per below
<details>
<summary>Make sure that the existing functionalities still working</summary>
```
$ ls -lrth cilium-sysdump-20211224-183*
-rw-rw-r-- 1 tammach tammach 7.7M Dec 24 18:34 cilium-sysdump-20211224-183404.zip --> from master branch
-rw-rw-r-- 1 tammach tammach 7.7M Dec 24 18:34 cilium-sysdump-20211224-183417.zip --> from this branch
```
</details>
<details>
<summary>Testing with a very large file (~10GB before compressed, 50MB after compressed)</summary>
```
dd if=/dev/zero of=filename bs=1 count=0 seek=50G
tar -czvf …
```
> bugtool: Compress and copy with resume

- internal/k8s/copy.go
- internal/k8s/pipe.go
- internal/k8s/pipe_test.go
To incorporate review comments in #671 
Sanity check was done locally with kind cluster to make sure there is no silly mistake :)
<details>
<summary>Sanity check</summary>
```
$ ./cilium sysdump         
🔍 Collecting Kubernetes nodes
🔍 Collect Kubernetes nodes
🔍 Collect Kubernetes version
🔍 Collecting Kubernetes pods
...
🔍 Collecting 'cilium-bugtool' output from Cilium pods
🔍 Collecting logs from Hubble pods
🔍 Collecting logs from Hubble Relay pods
🔍 Collecting platform-specific data
🔍 Collecting Hubble flows from Cilium pods
⚠️ The following tasks failed, the sysdump may be incomplete:
⚠️ [10] Collecting Cilium egress NAT policies: failed to collect Cilium egress NAT policies: the server could not find the requested resource (get ciliumegressnatpolicies.cilium.io)
⚠️ [11] Collecting …
```
> Incorporate review comments

- internal/cli/cmd/sysdump.go
- internal/k8s/client.go
- sysdump/client.go
- sysdump/constants.go
- sysdump/sysdump.go
- sysdump/sysdump_test.go
This commit is to support fetching DaemonSet based on labels, which
is requireds in case of any installation having custom name for
Cilium DaemonSet. Default value for this label selector will be
same as Cilium pod label selector.
Signed-off-by: Tam Mach <sayboras@yahoo.com>
Testing was done locally with kind cluster + cilium install, please find below details. 
<details>
<summary>Default run to make sure nothing breaks</summary>
```
$ ./cilium sysdump
🔍 Collecting Kubernetes nodes
🔍 Collect Kubernetes nodes
🔍 Collect Kubernetes version
🔍 Collecting Kubernetes pods
🔍 Collecting Kubernetes services
🔍 Collecting Cilium network policies
🔍 Collecting Kubernetes namespaces
🔍 Collecting Kubernetes pods summary
🔍 Collecting Kubernetes events
🔍 Collecting Kubernetes network policies
🔍 Collecting …
```
> sysdump: Support fetching DaemonSet with custom name

- .github/workflows/go.yaml
- .github/workflows/kind.yaml
- .github/workflows/multicluster.yaml
- .github/workflows/release.yaml
- Makefile
- README.md
Also update the `make release` target to use alpine 3.15.
> Update Go to 1.17.6

- connectivity/check/context.go
grpc.DialContext(..., grpc.WithInsecure()) is deprecated in favor of
grpc.DialContext(..., grpc.WithTransportCredentials(insecure.NewCredentials())
as of grpc v1.43.0, see [1]. Update to the later method.
[1] https://pkg.go.dev/google.golang.org/grpc@v1.43.0#WithInsecure
This will allow #663 to move forward.
> connectivity/check: use insecure.NewCredentials instead of WithInsecure

- .github/in-cluster-test-scripts/external-workloads-install.sh
- .github/in-cluster-test-scripts/gke.sh
- .github/in-cluster-test-scripts/multicluster.sh
- internal/cli/cmd/install.go
The --native-routing-cidr CLI option was deprecated for release v0.10.0
in commit f38b29f30d6d ("install: replace --native-routing-cidr by
--ipv4-native-routing-cidr"). Remove it now for the upcoming release.
Note that the Cilium ConfigMap option of the same name is still used
with the value passed in the --ipv4-native-routing-cidr option when
installing Cilium 1.10.
> install: remove deprecated --native-routing-cidr option

- RELEASE.md
The last few releases already have been created using the auto-generated
releases, see e.g. https://github.com/cilium/cilium-cli/releases/tag/v0.10.1
Switch the release process to use these by default and drop the
requirement for the separate github.com/cilium/release tool, as we don't
classify release notes into misc, minor, major and ci anyway.
> RELEASE.md: use GitHub auto-generated release notes

- clustermesh/certs.go
- hubble/hubble.go
- install/certs.go
- internal/certs/certs.go
Before this patch, "_Found CA in secret cilium-ca_" would be logged when:
1. The cilium-cli loaded an already exiting secret and,
2. The `cilium-ca` secret was not found and the cilium-cli created it.
This patch log a creation message in the latter case, aiming to avoid the confusing situation where the cilium-cli would hint that an already existing secret was re-used when it was actually created instead.
On a fresh kind cluster, notice the "🔑 Found CA in secret cilium-ca" message:
```console
% kind create cluster --config ~/kind/three-nodes.yaml --name alex
Creating cluster "alex" ...
✓ Ensuring node image (kindest/node:v1.21.1) 🖼
✓ Preparing nodes 📦 📦 📦
✓ Writing configuration 📜
✓ Starting control-plane 🕹️
✓ Installing StorageClass 💾
✓ Joining worker nodes 🚜
Set kubectl context to …
```
> cilium-ca: fix the cilium-ca creation log line

- clustermesh/clustermesh.go
- hubble/relay.go
- hubble/relay_test.go
- hubble/ui.go
- install/install.go
- internal/utils/utils.go
- internal/utils/utils_test.go
Fixes #692.
Signed-off-by: Tom Payne <tom@isovalent.com>
> internal/utils: fix parsing of user versions which include image path suffix

- connectivity/manifests/client-egress-only-dns.yaml
- connectivity/manifests/client-egress-to-echo.yaml
- connectivity/manifests/client-egress-to-entities-world.yaml
A few policy tests explicitly allow egress to CoreDNS, using an ancient
label selector that can't necessarily be relied on. Interestingly, some
of the tests (such as client-egress-to-fqdns-one-one-one-one), already had
network policies that included a label selector for k8s-app=coredns
in addition to k8s-app=kube-dns, but not all.
resolves #697
> connectivity: include k8s-app=coredns matchLabels

- .github/workflows/aks.yaml
- .github/workflows/eks-tunnel.yaml
- .github/workflows/eks.yaml
- .github/workflows/externalworkloads.yaml
- .github/workflows/gke.yaml
- .github/workflows/multicluster.yaml
- install/install.go
- install/node_init.go
Porting https://github.com/cilium/cilium/pull/18486 to the CLI.
> Prevent unmanaged pods in GKE's containerd flavors (cilium/cilium#18486)

- .github/workflows/aks.yaml
- install/azure.go
When installing Cilium in an AKS cluster, the Cilium Operator requires an Azure Service Principal with sufficient privileges to the Azure API for the IPAM allocator to be able to work.
The CLI allows users to provide a Service Principal themselves via `install` command flags, and otherwise tries to automatically create a new Service Principal with minimal privileges using the `az ad sp create-for-rbac` command (documentation: https://docs.microsoft.com/en-us/cli/azure/ad/sp?view=azure-cli-latest#az-ad-sp-create-for-rbac).
AKS CLI installations with automatically created Service Principals are now unsuccessful with the operator failing due to permissions errors:
```
level=warning msg="Unable to synchronize Azure virtualnetworks list" error="network.VirtualNetworksClient#ListAll: Failure …
```
> azure: add Contributor privileges to new Service Principals

- go.mod
- go.sum
- hubble/ui.go
- vendor/github.com/pkg/browser/browser_netbsd.go
- vendor/github.com/pkg/browser/browser_unsupported.go
- vendor/modules.txt
On some platforms (e.g. Linux), opening the browser using
`cilium hubble ui` might clutter stdout/stderr with messages
from the browser process due to `pkg/browser.OpenURL` logging them to
`os.Stdout`/`os.Stderr` by default. Avoid this by discarding the browser
process' stdout/stderr.
> hubble: don't log to stdout/stderr when opening browser

- internal/cli/cmd/sysdump.go
- sysdump/defaults.go
- sysdump/sysdump.go
- sysdump/sysdump_test.go
Store the messages logged by `cilium sysdump` in the
`cilium-sysdump.log` file in the sysdump itself. This allows to analyze
potential issues with `cilium sysdump` itself without having to ask
users to retrieve a new sysdump.
Fixes #351
> sysdump: include own log messages in sysdump

- sysdump/sysdump.go
Fixes: f9b2356377ad ("sysdump: include own log messages in sysdump")
> sysdump: check (*Collector).setupLogging error

- connectivity/suite.go
This was causing a timeout during the resolution of services to go unnoticed as it was never logged.
cc @christarazi @tklauser 
Fixes: https://github.com/cilium/cilium-cli/pull/720.
> connectivity: Don't ignore errors during setup & validation

- .github/workflows/aks.yaml
The AKS workflow, like the external workload workflow, loads a shell script to execute via a Helm chart twice: first for installing Cilium, then for the connectivity test itself.
The Helm chart takes in additional parameters to specify which version of the CLI should be loaded, and these were missing on the test part of the AKS workflow, resulting in the CLI being loaded off `latest` and not from the PR itself.
Fixes: f6cc7c6c00b7dbd25119f094c2db62f2b1b68b5f
> workflows: fix AKS workflow not using the right CLI pod

- install/node_init.go
Turns out that in GKE's `cos` images the `containerd` binary is still present even though `/etc/containerd/config.toml` is not. Hence, the kubelet wrapper would still be installed for these images according to the current check, even though it's not necessary. What's worse, starting the kubelet would fail because the `sed` command targeting the aforementioned file would fail.
This PR changes the check to rely on the presence of the `--container-runtime-endpoint` flag in the kubelet, which is probably a more reliable way of detecting `*_containerd` flavours and only applying the fix in these cases.
> Fix 'node-init' in GKE's 'cos' images.

- connectivity/check/check.go
- connectivity/tests/perfpod.go
- internal/cli/cmd/connectivity.go
CRR can quickly burn through `nf_conntrack_max` if the user passes too
many `--perf-samples` or an extended `--perf-duration`.
Adding `--perf-crr` to allow the user to run the CRR test, but it will
be a single sample of 30s.
closes #749 
Signed-off-by: Joe Talerico <rook@isovalent.com>
> Make CRR standalone workload

- .github/workflows/aks.yaml
We believe this might fix the issues we've seen where the operator reports it is missing permissions:
```
level=warning msg="Unable to synchronize Azure virtualnetworks list" error="network.VirtualNetworksClient#ListAll: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code=\"AuthorizationFailed\" Message=\"The client 'd09fb531-793a-40fc-b934-7af73ca60e32' with object id 'd09fb531-793a-40fc-b934-7af73ca60e32' does not have authorization to perform action 'Microsoft.Network/virtualNetworks/read' over scope '/subscriptions/22716d91-fb67-4a07-ac5f-d36ea49d6167' or the scope is invalid. If access was recently granted, please refresh your credentials.\"" subsys=azure
level=fatal msg="Unable to start azure allocator" …
```
> ci: update `az` to 2.30.0

- .github/workflows/kind.yaml
Making the workflow look more closely to what we do in cilium/cilium,
where we kill the port-forward before uninstalling.
Signed-off-by: Joe Talerico <rook@isovalent.com>
> Moving pkill to cleanup

- .github/workflows/go.yaml
- Makefile
Version 1.45 brings support for Go 1.18 so our hack can be removed.
> ci: bump golangci-lint to v1.45.0

- clustermesh/clustermesh.go
- install/autodetect.go
- install/install.go
- install/uninstall.go
- install/upgrade.go
- internal/k8s/client.go
- sysdump/client.go
- sysdump/sysdump.go
- sysdump/sysdump_test.go
The first commit removes an unnecessary always-nil error return when auto-detecting the cluster flavor. The second commit add support for auto-detecting K3s clusters. Example `cilium install` output:
```
$ cilium install
🔮 Auto-detected Kubernetes kind: K3s
ℹ️  using Cilium version "v1.11.2"
🔮 Auto-detected cluster name: default
🔮 Auto-detected IPAM mode: cluster-pool
ℹ️  helm template --namespace kube-system cilium cilium/cilium --version 1.11.2 --set cluster.name=default,ipam.mode=cluster-pool,kubeProxyReplacement=disabled,operator.replicas=1,serviceAccounts.cilium.name=cilium,serviceAccounts.operator.name=cilium-operator
🔑 Created CA in secret cilium-ca
🔑 Generating certificates for Hubble...
🚀 Creating Service accounts...
🚀 Creating Cluster roles...
🚀 Creating ConfigMap for Cilium …
```
> Autodetect K3s cluster flavor

- .github/in-cluster-test-scripts/aks-install.sh
- .github/in-cluster-test-scripts/eks-tunnel.sh
- .github/in-cluster-test-scripts/eks.sh
- .github/in-cluster-test-scripts/external-workloads-install.sh
- .github/in-cluster-test-scripts/gke.sh
- .github/in-cluster-test-scripts/multicluster.sh
- .github/workflows/kind.yaml
- README.md
- go.mod
- install/helm.go
- install/install.go
- internal/cli/cmd/install.go
Follow up of https://github.com/cilium/cilium-cli/pull/717
The PR is deprecating flags with `MarkDeprecate` method and giving priority to helm flags in case both CLI and helm flags are used. If all what people care is about `MarkDeprecate` then we can discuss that afterwards leave the flag prioritization on this PR.
> Deprecate old CLI flags

- .github/in-cluster-test-scripts/aks-install.sh
- .github/in-cluster-test-scripts/eks-tunnel.sh
- .github/in-cluster-test-scripts/eks.sh
- .github/in-cluster-test-scripts/external-workloads-install.sh
- .github/in-cluster-test-scripts/gke.sh
- .github/in-cluster-test-scripts/multicluster.sh
- .github/workflows/kind.yaml
There are certain locations in cilium-cli code that depend on the value
of certain flags that can be overwritten by helm-flags. This commit
reverts the flags that were changed on GH workflows. Users will still be
able to overwrite the cilium-cli flags with helm-values and since the
flags are not being deprecated we can still keep them in cilium-cli.
> .github: partially revert flag changes

- defaults/defaults.go
- hubble/hubble.go
- hubble/relay.go
- hubble/relay_test.go
- hubble/ui.go
- install/helm.go
- install/install.go
- internal/certs/certs.go
- internal/cli/cmd/hubble.go
- internal/helm/helm.go
- k8s/client.go
Besides switched to a helm-based installation. This PR also enables TLS for hubble. Previously, cilium-cli had the TLS disabled for hubble-ui
> Add helm-based installation for hubble integration

- internal/cli/cmd/sysdump.go
- sysdump/sysdump.go
Small pull request to allow passing in `--cilium-operator-namespace` to support use cases where the `cilium-operator` runs in a different namespace than the `cilium-agent`.
> sysdump - Add --cilium-operator-namespace option

- hubble/hubble.go
- hubble/relay.go
If Cilium image is set to a tag that can't be represented as a semver we
will fallback to the base version set by --base-version available as a
flag to the hubble enable command.
> hubble: fix deployment of hubble with unreleased Cilium versions

- connectivity/check/logging.go
The fire emoji does not stand out in logs. Replace it with one that
does.
Signed-off-by: Tom Payne <tom@isovalent.com>
> connectivity: Make fatal errors more visible

- k8s/client.go
- sysdump/client.go
- sysdump/constants.go
- sysdump/sysdump.go
- sysdump/sysdump_test.go
Adds the collection of Kubernetes Endpoints to the `sysdump` command as requested in https://github.com/cilium/cilium-cli/issues/520
Signed-off-by: Thorsten Pfister <thorsten.pfister@form3.tech>
Tested with a local dummy cluster which lead to the additional creation of a `k8s-endpoints-20220414-124930.yaml` file in the sysdump archive with the following truncated content:
```yaml
apiVersion: v1
items:
- metadata:
creationTimestamp: "2022-04-14T10:45:01Z"
labels:
endpointslice.kubernetes.io/skip-mirror: "true"
...
<snip>
...
kind: EndpointsList
metadata:
resourceVersion: "838"
```
Fixes #520
> feat: collect Kubernetes Endpoints in sysdump

- internal/helm/helm.go
Before it would show something like:
```
extraConfig=map[monitor-aggregation:none]
```
now it shows the correct format:
```
extraConfig.monitor-aggregation=none
```
> helm: fix helm template output for extraConfig options

- install/install.go
If the Peer Service file is present it should be installed.
Signed-off-by: Nate Sweet <nathanjsweet@pm.me>
> install: Add Peer Service on Install

- install/helm.go
Fixes: 77a7d30dc1c0 ("generate configmap from helm")
> install: add encryption.enabled when encryption wireguard is used

- internal/cli/cmd/sysdump.go
- sysdump/constants.go
- sysdump/defaults.go
- sysdump/sysdump.go
- sysdump/sysdump_test.go
If we run `gops` standalone inside the container the output marks which process runs the agent by appending a `*` next to the binary name:
```
25863 0     gops          unknown Go version /usr/bin/gops
25852 25847 cilium        unknown Go version /usr/bin/cilium
10    1     cilium-agent* unknown Go version /usr/bin/cilium-agent
1     0     custom-binary        go1.16.3           /usr/local/bin/custom-binary
```
Opted to parse this output. An alternative is to implement what @nathanjsweet committed in https://github.com/cilium/cilium-sysdump/commit/688a81430a71e155e4bbc516e9bd17f8479f6129. I think the downside with that approach is that not all container images will have `cat` inside them (e.g., `cilium-operator` which is based on `FROM scratch` + `gops` + `ca-certificates` + the operator …
> Add option to automatically detect the pid of the gops agent

- sysdump/sysdump.go
In our environments we deploy multiple Cilium agent deamonsets because of memory pressure. We have hosts where the `cilium-agent` is consuming an order of magnitude compared to other low-workload hosts where `cilium-agent` is coasting related to memory usage. If we run the `sysdump` command it will collect just the 1st deamonset that it detects leaving the rest out.
I decided to write to file the full `DaemonSetList` rather than separate files per deamonset.
Signed-off-by: Vlad Ungureanu <ungureanuvladvictor@gmil.com>
> Extract all deamonsets of Cilium

- install/uninstall.go
If test pods deletion takes longer than that of (cni)
cilium pods, test pods are stuck in the "terminating"
state. This ends up failing CI jobs in the clean-up stage.
Hence, wait until test pods are deleted before moving
onto the CNI related clean-up.
Signed-off-by: Aditi Ghag <aditi@cilium.io>
> install: Wait for test pods to be cleaned up

- RELEASE.md
LAST_RELEASE environment variable is no longer used.
> Clean up RELEASE.md

- install/helm.go
- internal/utils/utils.go
- internal/utils/utils_test.go
- k8s/client.go
Set image tag when overriding images, as otherwise "latest" will be used
by k8s.
Use operator.useDigest instead of operator.digest, which does not exist.
Only set image.tag if not overriding images.
Pass SHAs and "latest" through --version validation, so that a SHA can be
used as --version as intended.
Detect running Cilium version as "latest" if image has no tag, rather
than erroring out. This may happen if image tag is not specified for a
pod.
> Version tag handling fixes

- install/uninstall.go
Avoid repeating the same log message upon test namespace deletion.
Noticed while debugging AKS failure on https://github.com/cilium/cilium/pull/19665
Fixes: b3d0e95f29bc ("install: Wait for test pods to be cleaned up")
> install: don't repeat log message when waiting for test namespace to be deleted

- internal/cli/cmd/sysdump.go
- sysdump/constants.go
- sysdump/defaults.go
- sysdump/sysdump.go
I added 2 options to the sysdump command:
- `cni-config-directory` which defaults to `/etc/cni/net.d/`. In most of our systems we do not use this default path and thought it would be useful to allow users to specify if they have a custom path
- `cni-configmap-name` which defaults to `cni-configuration`. Opted to expose this because we allow this to be configured via Helm as well. In the code I opted to not error out and just log at debug if the configmap is not present.
Also I looked at using the backing implementation of `kubectl cp` to extract the files from the machines but it seemed more overhead to deal with tgz archives.
Fixes https://github.com/cilium/cilium-cli/issues/769
Fixes https://github.com/cilium/cilium-cli/issues/766
Signed-off-by: Vlad Ungureanu …
> Add support to collect CNI config files from the system

- connectivity/check/check.go
- connectivity/check/context.go
- connectivity/check/deployment.go
- connectivity/tests/perfpod.go
- internal/cli/cmd/connectivity.go
Adds a new CLI argument `--host-net` to the `--perf` test suite, which acts a toggle for choosing whether or not pods are deployed into the node's network namespace. This involves leveraging the `HostNetwork` option in the pod spec.
The goal of this change is to allow us to run a host networking scenario performance test.
> Add host networking scenario for performance tests

- internal/cli/cmd/status.go
- status/k8s.go
- status/status.go
`cilium status` takes on our cluster over a minute to execute. This can even be longer in some circumstances.
The status fetching is fully synchronous, if one pod is not ready anymore at the time of the exec this also adds unnecessary time.
Generally speaking the bigger the cluster the longer it takes.
Make the  processing of the agents async.
Tested on a cluster with around 150 nodes.
> improve status performance

- connectivity/check/deployment.go
This PR does the following:
- Check that DNS works before trying to wait for the service, because the service wait function relies on nslookup.
- If service wait fails, make logs print only namespace and name of the service, not dump of the entire object.
Fixes: https://github.com/cilium/cilium-cli/issues/716
> Perform DNS check earlier in the tests

- internal/cli/cmd/sysdump.go
- sysdump/sysdump.go
- sysdump/sysdump_test.go
It would be handy to have the cilium-cli version and flags used to
capture the sysdump in cilium-sysdump.log.
Sample outputs:
- No flags:
% ./cilium sysdump
🔍 Collecting sysdump with cilium-cli version: v0.11.5-18-gd3a523a1, args: [sysdump]
- With some flags:
% ./cilium sysdump --hubble-flows-count 10 --hubble-flows-timeout 5s
🔍 Collecting sysdump with cilium-cli version: v0.11.5-18-gd3a523a1, args: [sysdump --hubble-flows-count 10 --hubble-flows-timeout 5s]
> sysdump: Log cilium-cli version and arguments

- .github/cilium-cli-test-job-chart/templates/job.yaml
- .github/cilium-cli-test-job-chart/values.yaml
- .github/in-cluster-test-scripts/aks-install.sh
- .github/in-cluster-test-scripts/eks-tunnel.sh
- .github/in-cluster-test-scripts/eks.sh
- .github/in-cluster-test-scripts/external-workloads-install.sh
- .github/in-cluster-test-scripts/gke.sh
- .github/in-cluster-test-scripts/multicluster.sh
- .github/workflows/aks.yaml
- .github/workflows/eks-tunnel.yaml
- .github/workflows/eks.yaml
- .github/workflows/externalworkloads.yaml
- .github/workflows/gke.yaml
- .github/workflows/kind.yaml
- .github/workflows/multicluster.yaml
Currently, the workflows will always install the Cilium version
specified in defaults.Version which is currently set to 1.11.4.
To ensure compatibility of changes in cilium-cli we might want to run CI
with a different Cilium version, e.g. an rc release. This change allows
specifying cilium_version in the workflows to test against a different
version.
> .github: explicitly set Cilium version in workflows

- .github/workflows/externalworkloads.yaml
Follow https://github.com/cilium/cilium/pull/19483
Only use the first configured DNS server (the global one) in the
test. Also add nslookup debug and retry options in case they are needed
for further debugging and troubleshooting.
This fixes external workload CI test on master that failed like this:
```
Server:		169.254.169.254
Address:	169.254.169.254#53
** server can't find clustermesh-apiserver.kube-system.svc.cluster.local: NXDOMAIN
```
Here an incorrect nameserver is being used by nslookup. This
169.254.169.254 is configured (now) in GKE as a nameserver for some
local names. Don't know why nslookup sometimes chooses it if no server
address is given as a parameter.
> ci: make external workload only use global DNS server in test

- .github/workflows/externalworkloads.yaml
This was missed in commit c345ba2cdb51 ("ci: run `cilium service list
get` with `sudo` in external workloads ping test").
> ci: run `cilium status` with `sudo` in external workloads post-test phase

- sysdump/constants.go
- sysdump/sysdump.go
Extend the hubble observe command to capture debug output and the stderr
as a logfile.
While we're at it, improve the log messages to distinguish different
errors that may occur while gathering hubble observe data.
> sysdump: Collect hubble observe --debug and stderr

- Makefile
I use "make tags" instinctively in Cilium repos to generate databases
for navigating the codebase. Add some simple make targets here to
facilitate this workflow.
> Add ctags/cscope target

- README.md
These were accidentially included in commit 3ab53c02aa85 ("Update Go to
1.17.6") instead of being submitted in their own comment.
Fix them up so they work for any supported $GOOS/$GOARCH.
> README.md: fix binary installation instructions

- go.mod
- install/install.go
- internal/cli/cmd/install.go
- internal/helm/helm.go
When this flag is passed to "cilium install" command, it prints out all
the available versions and exits without actually installing Cilium.
Help message:
--list-versions                        List all the available versions without actually installing
Sample output:
% ./cilium install --list-versions
v1.12.0-rc2
v1.12.0-rc1
v1.12.0-rc0
v1.11.5 (default)
v1.11.4
v1.11.3
...
> install: Add --list-versions flag

- .github/workflows/gke.yaml
- .github/workflows/multicluster.yaml
> Note: this is a CLI backport of a similar change already made a while ago on the main `cilium/cilium` repository: https://github.com/cilium/cilium/commit/04147264308ee06f4c13fa105716efbec798e07f
We sometimes hit this issue in the CI for runs involving GKE clusters:
```
ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=This operation will exceed max secondary ranges per subnetwork (30) for subnet "default", consider reusing existing secondary ranges or use a different subnetwork.
```
As per the documentation, we can have the `gcloud` CLI create a new subnet when creating a new GKE cluster with `--create-subnetwork`. When passed `""`, it creates a new subnet with a default name and size. The goal here is to make sure that clusters don't conflict with each others …
> ci: create a new subnetwork for each new GKE cluster

- .github/in-cluster-test-scripts/eks.sh
- .github/workflows/eks-tunnel.yaml
- .github/workflows/eks.yaml
- Dockerfile
Fixing issue with invalid apiVersion
```
Error: Kubernetes cluster unreachable: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"
```
Testing was done with temp commit, successful runs are available below
CNI: https://github.com/cilium/cilium-cli/runs/6726007799?check_suite_focus=true
Tunnel: https://github.com/cilium/cilium-cli/runs/6726008680?check_suite_focus=true
> gha: Couple of changes to fix EKS failures

- connectivity/check/check.go
- connectivity/check/context.go
- connectivity/suite.go
- hubble/hubble.go
- hubble/relay.go
- hubble/relay_test.go
- hubble/ui.go
- internal/cli/cmd/connectivity.go
- internal/cli/cmd/hubble.go
- internal/cli/cmd/install.go
- internal/helm/helm.go
- internal/utils/utils.go
- internal/utils/utils_test.go
- k8s/client.go
might be easier to review commit by commit:
- add a wrapper function to read cilium-cli-helm-values secret and parse its data.
- remove --base-version from connectivity command.
- remove --base-version from hubble command.
- remove base version parameter from ParseCiliumVersion function.
> Remove --base-version flag from connectivity and hubble subcommands

- .github/in-cluster-test-scripts/aks-install.sh
- .github/workflows/aks.yaml
- install/autodetect.go
- install/azure.go
- install/helm.go
- install/install.go
- install/upgrade.go
- internal/cli/cmd/install.go
Add a new datapath mode for AKS clusters created using the new BYOCNI capabilities. This datapath mode is mutually exclusive with the older Azure datapath mode, as Azure IPAM is not available when using BYOCNI.
A similar datapath mode is going to be added to the main Helm chart so that enabling Cilium for AKS BYOCNI clusters is as simple as setting `aksbyocni.enabled=true` in the Helm values, in a similar fashion to what is done for the older Azure integration via `azure.enabled=true.
However, since this new integration has not yet landed in stable releases, we temporarily manually configure the same ConfigMap options as the new `aksbyocni` mode does, so that it works transparently.
See main PR on `cilium/cilium` for more context and details: https://github.com/cilium/cilium/pull/19379
> add support for AKS BYOCNI

- RELEASE.md
As done for the v0.11.8 release. Includes the following changes:
- Releases are cut from `v0.10` and `master` branches, not just `master`.
- Create a preparation PR (`README.md` and `stable.txt` update) before
tagging the release.
- Example command to set `COMMIT_SHA` to latest `master`.
> RELEASE.md: update to reflect current release process

- .github/workflows/gke.yaml
- .github/workflows/multicluster.yaml
backport #896
[ upstream commit 4aa573b366f9f7537e6fa125eb2a459f78470c91 ]
> Note: this is a CLI backport of a similar change already made a while
> ago on the main `cilium/cilium` repository:
> https://github.com/cilium/cilium/commit/04147264308ee06f4c13fa105716efbec798e07f
We sometimes hit this issue in the CI for runs involving GKE clusters:
```
ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=This operation will exceed max secondary ranges per subnetwork (30) for subnet "default", consider reusing existing secondary ranges or use a different subnetwork.
```
As per the documentation, we can have the `gcloud` CLI create a new
subnet when creating a new GKE cluster with `--create-subnetwork`. When
passed `""`, it creates a new subnet with a default name and …
> v0.10: ci: create a new subnetwork for each new GKE cluster

- go.mod
- go.sum
- k8s/client.go
- k8s/client_test.go
- vendor/github.com/distribution/distribution/LICENSE
- vendor/github.com/distribution/distribution/reference/helpers.go
- vendor/github.com/distribution/distribution/reference/normalize.go
- vendor/github.com/distribution/distribution/reference/reference.go
- vendor/github.com/distribution/distribution/reference/regexp.go
- vendor/modules.txt
The current mechanism to detect the image version of the Cilium has a
problem that it misinterpret the image name with registry's port number
(e.g. localhost:5000/cilium/cilium:latest). This is because it splits
the image string with strings.SplitN(s, 2) which result is wrongly
splitted slice ["localhost", "5000/cilium/cilium:latest"]. The version
estimation fails in this case.
Obviously, writing our own OCI image parser is painful. Instead, we can
rely on the official parser. In this commit, we rewrite the image
version estimation with the parser in
github.com/distribution/distribution. It also adds unit test to make
sure some major cases work.
Signed-off-by: Yutaro Hayakawa <yutaro.hayakawa@isovalent.com>
> Use OCI container reference parser to extract Cilium's version

- .github/in-cluster-test-scripts/eks-tunnel.sh
- .github/in-cluster-test-scripts/eks.sh
Workaround for #918
On EKS we occasionally see flakes where port-forwarding fails after
enabling Hubble Relay. Adding an explicit `cilium status --wait` works
around these.
Add a comment so we don't forget to remove the workaround once #918 is
resolved.
> ci: explicitly wait for cilium status after enabling Hubble relay

- install/install.go
We introduced support for BYOCNI with the `aks-byocni` datapath mode in 2e1d3b5d375e7028ffcf7900bbb155f97f58aec1, and properly guarded the previously existing Service Principal creation to only be done when using Azure IPAM (`azure` datapath mode), however we forgot to do the same for the newly-introduced AKS secrets in the Cilium 1.12 Helm chart.
This went undetected during the initial implementation as the Helm chart used was either the stable 1.11.5 or the development version 1.11.90 when directly using the Helm chart from upstream `master` branch, in both cases skipping the existing 1.12 check for creating AKS secrets.
Now, after the 1.12 branch was properly created and the development version bumped to 1.12.90, this does not work anymore, and explains why the AKS BYOCNI CI in …
> azure: fix BYOCNI install with Cilium >= 1.12

- connectivity/check/action.go
- connectivity/filters/filters.go
Make flow validation more robust when multiple TCP connections may be seen in Hubble output, as in the case of L7 LB by:
- Avoid duplicate port filters (only a cosmetic change)
- Settle wildcarded ephemeral port and destination IP on the first SYN only
- Otherwise multiple L4 connections during the test will not be properly matched
- Move HTTP flow validation to a separate requirement
- FIN requirement is removed from the HTTP connection, as Envoy may keep the connection open
- The same connection may match both L3/L4 and HTTP requirement as before
> Prepare flow validation for L7 LB support

- connectivity/check/deployment.go
The old hash didn't have arm64 version, this commit is to use another
hash having both amd64 and arm64 arch.
Related: https://github.com/cilium/cilium/pull/20421#discussion_r916131359
Suggested-by: Chance Zibolski <chance.zibolski@gmail.com>
> connectivity: Update coredns image for arm64

- .github/in-cluster-test-scripts/aks.sh
It seems #918 occasionally occurs on AKS as well, e.g.
https://github.com/cilium/cilium-cli/runs/7243578074?check_suite_focus=true
Apply the same workaround as already added for EKS in commit
a0faf2510f6b ("ci: explicitly wait for cilium status after enabling
Hubble relay")
> ci: explicitly wait for cilium status after enabling Hubble relay on AKS

- .github/workflows/aks-azure-ipam.yaml
- .github/workflows/aks-byocni.yaml
Our previous credentials expired (apparently by default Azure secrets are only valid for 12 months), so we take this opportunity to switch to the more modern and secure OIDC authentication as described in documentation:
- https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect
- https://github.com/azure/login#github-action-for-azure-login
> ci: switch to OIDC authentication for az CLI

- k8s/client.go
- sysdump/client.go
- sysdump/constants.go
- sysdump/k8sutils.go
- sysdump/sysdump.go
- sysdump/sysdump_test.go
When we try and run cilium-bugtool in the agent container, it fails if that container is not running (e.g. because it's in CrashLoopBackoff). So, if that's not running, fall back to an EphemeralContainer or, if that fails, create another pod for exec purposes.
Fixes: #871
> sysdump: run bugtool even when cilium agent is not running

- connectivity/check/check.go
- connectivity/check/context.go
- internal/cli/cmd/connectivity.go
We currently operate cilium with a different daemonset name than the `defaults.AgentDaemonSetName` is set to. This PR adds support for passing in `--agent-daemonset-name` so that the connectivity tests can still identify the daemonset.
> [connectivity tests] Support custom agent daemonset name

- connectivity/check/check.go
- connectivity/check/deployment.go
- defaults/defaults.go
- internal/cli/cmd/connectivity.go
https://github.com/cilium/cilium-cli/pull/854 added support for having private images however, this image is hardcoded currently. 
This PR adds support for passing in `--dns-test-server-image` allowing folks to use the connectivity tests without having to connect to any third party registry. I also updated the image to be explicitly from docker.io follow the format of the other images.
> [connectivity tests] Support private CoreDNS image location

- .github/in-cluster-test-scripts/external-workloads-install.sh
- .github/in-cluster-test-scripts/gke.sh
- .github/in-cluster-test-scripts/multicluster.sh
We're occasionally encountering #918 on GKE too, e.g.
https://github.com/cilium/cilium-cli/runs/7421447399?check_suite_focus=true
Apply the same workaround as already added for EKS in commit
a0faf2510f6b ("ci: explicitly wait for cilium status after enabling
Hubble relay") and for AKS in commit 7176ce532267 ("ci: explicitly wait
for cilium status after enabling Hubble relay on AKS").
> ci: explicitly wait for cilium status after enabling Hubble relay on GKE

- connectivity/check/check.go
- connectivity/suite.go
- internal/cli/cmd/connectivity.go
The connectivity tests run depend on the Cilium version detected. In
some cases (e.g. when run against Isovalent Cilium Enterprise) the
Cilium version is not detected correctly and the connectivity tests fall
back to assuming the latest Cilium version. These tests may fail if the
actual Cilium version is too old.
This commit adds an --assume-cilium-version flag to cilium connectivity
test to allow the version to be set explicitly, rather than falling back
to the latest by default. This is useful for CI when running the
connectivity tests against older versions of Cilium.
Signed-off-by: Tom Payne <tom@isovalent.com>
> connectivity: Add --assume-cilium-version flag

- clustermesh/clustermesh.go
This commit is to make sure that cluster-id is numeric and within range
of 1-255.
https://docs.cilium.io/en/stable/gettingstarted/clustermesh/clustermesh/#gs-clustermesh
> Each cluster must be assigned a unique human-readable name as well as a numeric cluster ID (1-255)
Fixes: #143
> clustermesh: Validate cluster-id value as per requirement

- connectivity/check/context.go
- connectivity/suite.go
This commit changes the version detection away from the version state
stored during `cilium install`, and instead relies on the actual version
reported by `cilium version` in the Cilium pods. This fixes an issue
where `cilium connectivity test` could not be used if Cilium was not
installed via CLI (e.g. via Helm).
The version of all Cilium pods is parsed, and only the minimum version
is used. This ensures that we can use the lowest common denominator in
terms of features.
> connectivity: Detect version from cilium pods

- connectivity/check/deployment.go
When https://github.com/yahoo/k8s-namespace-guard is setup and the connectivity tests are run with `--force-deploy`, this loop gets stuck waiting for the namespace to be deleted. This is because it takes a while for the pods to get removed after the deployment is gone but, the namespace-guard has already rejected the original deletion request. 
In my testing, the simplest fix is to just add the deletion here which does work once the pods are gone. The logic just above this already takes care of issuing the delete request for objects that the namespace-guard cares about, there's simply a race between those commands and line 646.
> [connectivity] Retry deleting namespace while waiting

- RELEASE.md
Update stable.txt only after the new version was tagged and released.
Otherwise, there is a small time window where stable.txt would point to
an inexistent version.
Ref. https://github.com/cilium/cilium-cli/pull/983#issuecomment-1189148903
> RELEASE.md: bump version in stable.txt after release

- connectivity/manifests/client-egress-only-dns.yaml
- connectivity/manifests/client-egress-to-echo.yaml
- connectivity/manifests/client-egress-to-entities-world.yaml
- connectivity/manifests/client-egress-to-fqdns-one-one-one-one.yaml
When node-local dns is deployed along with local
redirect policy [1], the DNS traffic is redirected
to node-local dns cache pods. Hence, allow such DNS
traffic in the connectivity test policy yamls.
[1] https://docs.cilium.io/en/latest/gettingstarted/local-redirect-policy/#node-local-dns-cache
Reported-by: Julien Boulanger <julien.boulanger@fr.clara.net>
Signed-off-by: Aditi Ghag <aditi@cilium.io>
> connectivity: Add node-local-dns match labels

- defaults/defaults.go
- install/install.go
- install/upgrade.go
- internal/cli/cmd/install.go
We forgot to upgrade this particular DaemonSet if present.
Fixes: #689
> upgrade: also bump clustermesh-apiserver

- connectivity/check/context.go
It is unused since commit 22e5ec96560b ("connectivity: Remove
--base-version flag").
> connectivity: remove unused (*ConnectivityTest).FetchCiliumPodImageTag

- internal/helm/helm.go
Some types were not being printed when generated helm template command.
For example:
```
ipam:
mode: cluster-pool
operator:
clusterPoolIPv4PodCIDRList:
- "10.244.0.0/16"
- "10.245.0.0/16"
```
Now, when running cilium install the helm template command for those
values will be correctly presented:
```
helm template [...] --set ipam.operator.clusterPoolIPv4PodCIDRList[0]=10.244.0.0/16,ipam.operator.clusterPoolIPv4PodCIDRList[1]=10.244.0.1/16 [...]
```
> internal: add missing types when generating helm template command

- connectivity/check/check.go
- connectivity/check/context.go
- connectivity/check/logging.go
- internal/cli/cmd/connectivity.go
This will help us to correlate cmd execution with hubble flows (e.g., when debugging the Conformance GKE flake).
> connectivity: Add -t to prefix log msg with timestamp

- .gitignore
- go.mod
- sysdump/sysdump.go
- sysdump/sysdump_test.go
When running sysdump, if kvstore is detected then various kvstore paths are added to the dump.
This is intended to be used by the debug-ability tools to help diagnose issues.
Signed-off-by: Tom Hadlaw <tom.hadlaw@isovalent.com>
> sysdump: Add kvstore data to dumps.

- .github/dependabot.yml
It's unlikely that these will cause merge conflicts. The cilium/cilium
repo also uses the same limit without any issues so far.
> .github: update dependabot open PR limit for GH actions

- .github/workflows/kind.yaml
- connectivity/check/action.go
- connectivity/check/check.go
- connectivity/check/deployment.go
- connectivity/check/features.go
- connectivity/check/scenario.go
- connectivity/check/test.go
- connectivity/suite.go
- connectivity/tests/host.go
- connectivity/tests/service.go
This PR adds an additional scenario to the `no-policies` test which checks connectivity to pods with a HostPort. HostPort support in Cilium can be achieved either via CNI chaining with the portmap plugin, or via Kube Proxy Replacement. I have validated this PR with both setups.
There are some changes needed to the overall code, such as support for conditional scenarios and support for alternative destination addresses in flow validation (needed for KPR HostPort). The newly introduced scenario is only run if the HostPort feature is detected.
*Review per commit*
> connectivity: Add test for HostPort support

- connectivity/check/features.go
- connectivity/manifests/echo-ingress-icmp.yaml
- connectivity/suite.go
This commit is to add new connectivity test (e.g. client-ingress-icmp)
with allowed ICMP policy.
---
As highlighted below, CI is still with cilium 1.11, so testing was done locally with minikube cilium 1.12.0
> connectivity: Add ICMP policy test from client to client

- connectivity/check/features.go
Previously, we have been relying on the Cilium ConfigMap to detect the
presence of features. Relying on the ConfigMap has however some
downsides, as one has to know the default value of a certain feature if
the option is absent from the ConfigMap. To make things worse, this
default value is also version dependent in some cases.
This PR therefore instead tries to extract the feature status from the
agent-runtime-config.json, which is a JSON representation of the
`option.Config` struct used in Cilium Agent. It contains the actual
values determined at run-time, which is more robust than the ConfigMap
equivalent.
The agent-runtime-config.json is present since Cilium v1.10 and has been
backported to v1.8.10 and v1.9.7. See the PR for more details:
https://github.com/cilium/cilium/pull/16017
A …
> connectivity: Use agent-runtime-config.json for feature detection

- connectivity/check/check.go
- connectivity/check/context.go
- connectivity/check/deployment.go
- connectivity/check/features.go
- connectivity/check/test.go
- connectivity/suite.go
- connectivity/tests/service.go
- install/helm.go
- install/install.go
- internal/cli/cmd/connectivity.go
- internal/cli/cmd/install.go
- k8s/client.go
This PR:
- Extends `cilium install` to accept `--nodes-without-cilium` to denote nodes on which Cilium should not be installed.
- Adds `FeatureNodeWithoutCilium` to test for such nodes.
- Adds `outside-to-nodeport` as an example test case of the DP conformance suite.
See individual commit msgs for more details.
Ref: https://github.com/cilium/cilium/issues/20606
> Add stub for datapath connectivity tests

- connectivity/check/features.go
The terminology and friends were deprecated in v1.12, and they will be
removed in v1.13: https://github.com/cilium/cilium/pull/20369.
Use "Socket LB" everywhere instead.
> connectivity: Get rid of host reachable svc

- sysdump/sysdump.go
- Trim the filename list string before splitting. If there is a trailing
newline character, the last element in the filename becomes an empty
string.
- Wrap the error to add some extra contexts on what failed.
Ref: https://github.com/cilium/cilium-cli/pull/827
> sysdump: Trim ls output

- .github/workflows/loki.yaml
Use michi-covalent/push-to-loki to push workflow run results to Loki
to make it easier to monitor the overall health of the CI. My ultimate
goal is to get rid of Slack notifications.
Ref: https://github.com/michi-covalent/push-to-loki
> Push workflow run results to Loki

- .github/dependabot.yml
- Dockerfile
Also don't use `ARG` in the `FROM` instruction. Dependabot doesn't
handle it right now.
Ref: https://github.com/dependabot/dependabot-core/issues/2057
> dependabot: Monitor Dockerfile

- .github/workflows/aks-azure-ipam.yaml
- .github/workflows/aks-byocni.yaml
- .github/workflows/eks-tunnel.yaml
- .github/workflows/eks.yaml
- .github/workflows/externalworkloads.yaml
- .github/workflows/gke.yaml
- .github/workflows/go.yaml
- .github/workflows/images.yaml
- .github/workflows/kind.yaml
- .github/workflows/multicluster.yaml
- .github/workflows/release.yaml
We don't actively monitor the Slack channel, and we now send workflow
run results to Loki so I propose we stop sending Slack notifications.
> ci: Remove Slack notifications

- install/autodetect.go
- install/install.go
- k8s/client.go
Previously, Cilium-CLI won’t enable kube-proxy by default automatically if no kube-proxy has been installed in the cluster. This patch will detect kube-proxy installation in the cluster automatically and it’ll set the helm value kubeProxyReplacement=strict if there were no kube-proxy.
Fixes: #1004
> Enable kube-proxy replacement if no kube-proxy is detected in a cluster

- .github/workflows/externalworkloads.yaml
The workflow started timing out occassionally after more tests were
added in https://github.com/cilium/cilium-cli/pull/1028 and thus test run times increased.
Ref. https://github.com/cilium/cilium-cli/pull/1063#issuecomment-1228637644
> ci: bump external workloads workflow timeouts

- clustermesh/clustermesh.go
- defaults/defaults.go
Fixing the `cilium clustermesh status` command when Cilium is installed using Helm.
Changes clustermesh secret names to be consistent with secret names generated by Helm. Loads external workload secrets only when needed, preventing the `clustermesh status` command to fail external load secrets are not defined.
> Clustermesh secrets helm inconsistency fix

- clustermesh/clustermesh.go
- hubble/hubble.go
- install/install.go
- status/k8s.go
- status/k8s_test.go
If the agent container isn't running, we still tried to do a "kubectl exec", which is guaranteed to fail. Rather, let's generate a more useful error message.
This will now report something like this:
`unable to retrieve cilium status: container cilium-agent is in
CrashLoopBackOff, exited with code 0, try 'kubectl -n kube-system logs
-c cilium-agent cilium-wls67'`
Fixes: #1026
> Status: generate a more meaningful message if agent not running

- .github/workflows/externalworkloads.yaml
- .github/workflows/gke.yaml
- .github/workflows/multicluster.yaml
service_account_key in the google-github-actions/setup-gcloud action is
deprecated, see [1], [2]. Switch to the suggested
google-github-actions/auth action instead.
[1] https://github.com/cilium/cilium-cli/actions/runs/2998471345
[2] https://github.com/google-github-actions/setup-gcloud#authorization
> ci: switch to google-github-actions/auth for GKE based workflows

- .github/in-cluster-test-scripts/eks-tunnel.sh
- connectivity/check/features.go
- connectivity/suite.go
- connectivity/tests/health.go
This ports the test test/k8s/health.go from the cilium repository
for validating the connectivity between the cilium-agent instances
and checking that the cilium-health command and health endpoints work
correctly.
> connectivity: Add test for cilium-health

- connectivity/suite.go
- connectivity/tests/world.go
In order to increase our FQDN policy coverage in the connectivity tests,
add test logic to assert against a disallowed FQDN.
This is in service of the goal to replace the Ginkgo test suite (as much
as possible) from the main Cilium tree:
https://github.com/cilium/cilium/blob/master/test/k8s/fqdn.go
Signed-off-by: Chris Tarazi <chris@isovalent.com>
> Expand FQDN connectivity tests to assert policy denies for disallowed FQDN

- internal/helm/helm.go
Currently, the cilium charts are embedded inside cilium cli binary,
which will require a new cilium/charts bump in go.mod and then a new
release for cilium-cli. It's making sense to do so if some other code
changes are required to make installation working for new char version,
but most of the time, only go.mod upgrade is required.
This commit is to add the capability to install new chart version without
the need of releasing or installing new cilium-cli.
The changes are tested on top of commit 4fc8b226 (i.e. v1.13.0-rc0 is not
supported). 
```
$ ./cilium install --version 1.14.0   
chart "cilium" version "1.14.0" not found in https://helm.cilium.io repository
$ ./cilium install --version 1.13.0-rc0
🔮 Auto-detected Kubernetes kind: minikube
✨ …
```
> helm: Add support for remote chart version

- defaults/defaults.go
Update alpine-curl to v1.5.0, json-mock to v1.3.2 and coredns to v1.9.4.
> defaults: update connectivity test image versions

- connectivity/manifests/allow-all-egress.yaml
- connectivity/manifests/allow-all-except-world-pre-v1.11.yaml
- connectivity/manifests/allow-all-except-world.yaml
- connectivity/manifests/allow-all-ingress.yaml
- connectivity/manifests/client-egress-l7-http-method.yaml
- connectivity/manifests/client-egress-l7-http-named-port.yaml
- connectivity/manifests/client-egress-l7-http.yaml
- connectivity/manifests/client-egress-only-dns.yaml
- connectivity/manifests/client-egress-to-cidr-1111-deny.yaml
- connectivity/manifests/client-egress-to-cidr-1111.yaml
- connectivity/manifests/client-egress-to-echo-deny.yaml
- connectivity/manifests/client-egress-to-echo-expression-deny.yaml
- connectivity/manifests/client-egress-to-echo-expression.yaml
- connectivity/manifests/client-egress-to-echo-named-port-deny.yaml
- connectivity/manifests/client-egress-to-echo-service-account-deny.yaml
- connectivity/manifests/client-egress-to-echo-service-account.yaml
- connectivity/manifests/client-egress-to-echo.yaml
- connectivity/manifests/client-egress-to-entities-world.yaml
- connectivity/manifests/client-egress-to-fqdns-one-one-one-one.yaml
- connectivity/manifests/client-ingress-from-client2.yaml
- connectivity/manifests/echo-ingress-from-other-client-deny.yaml
- connectivity/manifests/echo-ingress-from-other-client.yaml
- connectivity/manifests/echo-ingress-icmp-deny.yaml
- connectivity/manifests/echo-ingress-icmp.yaml
- connectivity/manifests/echo-ingress-l7-http-named-port.yaml
- connectivity/manifests/echo-ingress-l7-http.yaml
As the connectivity test can be from another namespace, which is passed by --test-namespace CLI flag, we should not have any hard coded namespace in all related policy manifests.
Fixes: #1109
> test/connectivity: Remove explicit namespace in policy manifest

- config/config.go
- hubble/hubble.go
Pass the context from the caller where available instead of instantiating a background context.
> config, hubble: plumb context where available

- connectivity/check/test.go
This is to make sure that we can dynamically replace the value of pod namespace label (e.g. io.kubernetes.pod.namespace) to the value passed in CLI flag (e.g. --test-namespace).
Related: #1112
> test/connectivity: Add any prefix for pod namespace label

- connectivity/check/deployment.go
This commit reorganizes ConnectivityTest.deploy and ConnectivityTest.validateDeployment to ensure that when the `--perf` flag is given from the user, only performance-related deployments are created and validated. Prior, all resources within the connectivity test are created and validated, even though they aren't used by the performance tests. This change should lead to faster startup times for performance tests.
This commit also adjusts how perf-related deployments are returned from `ConnectivityTest.deploymentList`. Prior, client deployments were returned in `srcList` and server deployments were returned in `dstList`, implying that `srcList` and `dstList` represent deployments belonging to clients and servers respectively. After review, this is an incorrect assumption that was made, as …
> test/connectivity: Add early return when deploying perf resources

- .github/workflows/kind.yaml
This is to make sure that we have the coverage of running tests in a namespace other than cilium-test.
Relates: https://github.com/cilium/cilium-cli/issues/1109#issuecomment-1260777569
> test/connectivity: Run connectivity test in non-default namespace

- hubble/hubble.go
- internal/cli/cmd/hubble.go
- internal/cli/cmd/install.go
cilium uninstall calls K8sHubble.Disable to delete resources created by Hubble. We don't need to update cilium-config and restart Cilium to actually disable Hubble since we are deleting Cilium right after.
Fixes: #255
> Don't restart Cilium on cilium uninstall

- internal/cli/cmd/sysdump.go
- sysdump/client.go
- sysdump/defaults.go
- sysdump/sysdump.go
- sysdump/sysdump_test.go
Unless specified by '--cilium-namespace', sysdump will now attempt to auto detect which namespace has a Cilium installation from a list of default namespaces.
This will make the default path coverage most Cilium installations. Installs outside of these namespaces will presumably the result of more custom installations and can be overridden per-usual with --cilium-namespace.
Signed-off-by: Tom Hadlaw <tom.hadlaw@isovalent.com>
> sysdump: auto detect namespace from list of defaults.

- .github/workflows/externalworkloads.yaml
- .github/workflows/gke.yaml
- .github/workflows/multicluster.yaml
Cluster creation is failing with the latest CLI. Let's pin to an older version that's known to work until we update these workflows to be compatible with the latest CLI.
Ref: https://cloud.google.com/sdk/docs/release-notes#40500_2022-10-04
> Pin gcloud CLI version

- hubble/hubble.go
- install/helm.go
- install/install.go
- internal/cli/cmd/install.go
- internal/helm/helm.go
- k8s/client.go
This is an attempt to fix https://github.com/cilium/cilium-cli/issues/1107 by introducing two ways to set `.Capabilities.APIVersions` in helm while rendering Cilium templates:
* Query the api-server to find all known needed api-resources in a cluster for verifying cilium templates, passing them to `.Capabilities.APIVersions`.
* Let a user manually set the list by using the `--api-versions` CLI argument.
I've also adjusted the code that prints out the `helm template` command to include any equivalent `--api-versions` args when setting `.Capabilities.APIVersions` using one of the above methods.
To do this, I changed following functions/interfaces:
1. `hubble/hubble.go: k8sHubble.genManifests`: Adjust for breaking changes in internal/helm.go
2. `install/helm.go: …
> install: Add ability to auto-fill or manually set .Capabilities.APIVersions in helm

- defaults/defaults.go
cilium/json-mock:v1.3.2 fails to run on arm64:
$ docker run -it quay.io/cilium/json-mock:v1.3.2@sha256:bc6c46c74efadb135bc996c2467cece6989302371ef4e3f068361460abaf39be
exec /bin/bash: exec format error
The new build (v1.3.3) runs fine.
> defaults: Update cilium/json-mock to v1.3.3

- defaults/defaults.go
Bump the network-perf image to enable arm64 in accordance with https://github.com/cilium/image-tools/pull/196.
Verified with https://github.com/nickolaev/vagrant-parallels-m1-k8s-cilium
Closes #1193.
Signed-off-by: Nikolay Nikolaev <nicknickolaev@gmail.com>
> Enable network-perf for arm64

- connectivity/check/action.go
When connections to hubble fail, there currently isn't enough information to debug the issue after-the-fact. So, add in a few more debug lines to try and get to the bottom of the problem.
Also, bump the connection timeout from 10 to 30 seconds.
> test/connectivity: Add a bit more logging around Hubble connections

- install/autodetect.go
- install/helm.go
- install/install.go
- internal/cli/cmd/install.go
The current implementation tries to replace  the kube-proxy for k3s and doesn't honor the value set for kube-proxy replacement by users. This PR fixes those issues.
Fixes: cilium#1004
Signed-off-by: shankeerthan-kasilingam <shankeerthan1995@gmail.com>
> Improvements for kube-proxy detection and replacement

- connectivity/check/action.go
I realized after merging that there was a goroutine leak added in commit 7644dcc362. Need to move the `wg.Done()` to a defer to ensure it always is called.
Fixes: 7644dcc362
> test/connectivity: fix goroutine leak

- .github/workflows/kind.yaml
- internal/cli/cmd/install.go
It is going to removed in the Cilium v1.13. See
https://github.com/cilium/cilium/pull/22083.
> Get rid of kube-proxy-replacement=probe

- clustermesh/clustermesh.go
Rename to `--bpf-lb-sock`, as `--enable-host-reachable-services` was removed in https://github.com/cilium/cilium/pull/22083.
> clustermesh: Rename host-reachable-svc opt

- connectivity/tests/cidr.go
Since Cloudflare's server redirects all HTTP connections to HTTPS, requests against TCP/80 may be rate-limited and be the cause of our frequent flakes. Martynas suggested we try to request over TCP/443. Worth a shot!
> connectivity: Send request to 1.1.1.1 over TCP/443 instead of TCP/80

- install/install.go
- install/rbac.go
- internal/utils/yaml.go
Rather than having to release cilium-cli for every new object, parse multiple roles and rolebindings from a single manifest file.
> install: allow for multiple roles and rolebindings per file

- clustermesh/clustermesh.go
- config/config.go
- connectivity/check/check.go
- connectivity/check/context.go
- connectivity/check/delete.go
- connectivity/check/features.go
- connectivity/tests/service.go
- defaults/defaults.go
- hubble/hubble.go
- install/helm.go
- install/install.go
- install/uninstall.go
- internal/cli/cmd/connectivity.go
- internal/utils/json.go
- k8s/client.go
- status/k8s.go
- status/k8s_test.go
Add a `--delete-cilium-pod-on-nodes` flag to `cilium connectivity test` which will delete the Cilium pods from the specified nodes before running tests. On the specified nodes this will keep only the datapath plumbed, but no Cilium agent running.
This is implemented similar to the existing `cilium install --nodes-without-cilium` flag which will set up pod's nodeAffinity such that Cilium pods won't be scheduled on nodes with label `cilium.io/no-schedule`.
This serves to migrate the "chaos tests" currently part of Cilium in-tree tests to cilium-cli.
> Allow to delete cilium pods before connectivity tests

- k8s/client.go
- sysdump/client.go
- sysdump/constants.go
- sysdump/sysdump.go
- sysdump/sysdump_test.go
Cilium `v1.12` introduced CEGP as alternative way of configuring EgressGW policies. Collect them in the sysdump.
Signed-off-by: Julian Wiedmann <jwi@isovalent.com>
> sysdump: collect CiliumEgressGatewayPolicies

- connectivity/check/action.go
- connectivity/check/check.go
- connectivity/check/context.go
- internal/cli/cmd/connectivity.go
- internal/cli/cmd/sysdump.go
which allows to collect, whenever a test fails, a more significant
sysdump before the CLI cleans up any state.
To allow the same level of configurability, the "connectivity test"
command now supports the same flags used by the "sysdump" command.
These flags are all prefixed by "--sysdump-".
> connectivity: add --collect-sysdump-on-failure flag 

- connectivity/check/action.go
- connectivity/check/context.go
- connectivity/check/test.go
With this change, when --collect-sysdump-on-failure is set, the CLI will collect a sysdump also for the case where the test setup logic encounters an error.
> connectivity: collect sysdump also on test setup failure

- status/k8s.go
Since CEPs are cleaned up for Completed Pods, these pods should not be considered for total Cluster Pods count.
Fixes: #1235
Signed-off-by: flxman <felix.farjsjo@gmail.com>
> status: Exclude non-running pods from total Cluster Pods count

- .github/workflows/eks-tunnel.yaml
- .github/workflows/eks.yaml
- connectivity/check/context.go
- install/uninstall.go
- internal/cli/cmd/install.go
This should help to work around an issue we're seeing in cilium/cilium CI where deleting the cilium-test namespace times out, see https://github.com/cilium/cilium/issues/22368
> connectivity, install: delete pods before deleting namespace

- connectivity/check/logging.go
- connectivity/check/test.go
Before (notice the timestamp logs at end of line of the progress indicators `.` instead of at the start of line):
```
[2022-11-28T13:10:25+01:00] 🏃 Running tests...
[2022-11-28T13:10:25+01:00]
[2022-11-28T13:10:25+01:00] [=] Test [no-policies]
....................................[2022-11-28T13:10:32+01:00]
[2022-11-28T13:10:32+01:00] [=] Test [allow-all-except-world]
..............[2022-11-28T13:10:38+01:00]
[2022-11-28T13:10:38+01:00] [=] Test [client-ingress]
..[2022-11-28T13:10:43+01:00]
[2022-11-28T13:10:43+01:00] [=] Test [all-ingress-deny]
........[2022-11-28T13:11:10+01:00]
```
After:
```
[2022-11-28T13:44:00+01:00] 🏃 Running tests...
[2022-11-28T13:44:00+01:00] [=] Test [no-policies]
[2022-11-28T13:44:00+01:00] ....................................
[2022-11-28T13:44:06+01:00] [=] …
```
> connectivity/check: fix logging in non-verbose mode with timestamps

- .github/workflows/release.yaml
- Makefile
In local environments we usually want to keep the current behavior (i.e. release artifacts owned by the uid/gid of the user invoking `make release`). However in GitHub actions, the command recently started failing with:
addgroup: gid '123' in use
(see https://github.com/cilium/cilium-cli/actions/runs/3572725726/jobs/6006032172)
In GitHub actions, the ownership of the release artifacts shouldn't matter since they're ephemeral anyway. We can now use the following command in the release action:
RELEASE_UID=0 RELEASE_GID=0 RELEASER_USER= RELEASER_GROUP= make
> ci, make: allow to build release as root user

- .github/workflows/release.yaml
- Makefile
Follows https://github.com/cilium/hubble/pull/821
The release build should run with the same numeric user and group id as the caller of the Makefile. This solves two problems:
1. The generated artefacts should be owned by the user who invoked the Makefile
2. `go build -buildvcs=true` (the default since Go 1.18) invokes git, and git requires that the .git folder is owned by the user invoking it.
Previously, we achieved this by creating a new user and group inside the container with the wanted uid/gid. The problem with that approach is it fails if the uid/gid is already taken (such as e.g. gid 123, which seems to be used by the GitHub runner as of recently). Therefore, instead of trying to create a new user, this commit now uses `setpriv` from util-linux to force the `make` process (and all …
> Makefile: Fix potential uid/gid collision by using setpriv

- clustermesh/clustermesh.go
- install/install.go
- internal/cli/cmd/clustermesh.go
This fixes the following error in the external workload workflow in cilium/cilium CI:
Error: Unable to create external workload install script: No Major.Minor.Patch elements found
See https://github.com/cilium/cilium/pull/22441#issuecomment-1332086537
For https://github.com/cilium/cilium/issues/22451
Fixes: dcfb77269f48 ("clustermesh: Fix --bpf-lb-sock on < 1.12")
> clustermesh: use Cilium version extracted from helm secret if available

- status/k8s.go
After some testing after merging #1236 I realized that CEPs are created already for Pods in Pending phase (which makes total sense). Due to this, these pods should be included in the total Cluster Pod count so that `cilium status` shows correct output. Without this fix, if you have 2 pods stuck in Pending, `cilium status` will output e.g. 131/129 pods managed by cilium. 
Signed-off-by: flxman <felix.farjsjo@gmail.com>
> status: Include pending pods in total Cluster Pods count

- .github/workflows/images.yaml
The same instructions are run in the previous step already.
> .github/workflows: remove duplicate CI Image release digest step

- .github/workflows/externalworkloads.yaml
- .github/workflows/gke.yaml
- .github/workflows/multicluster.yaml
When a workflow cancels, the clean-up job cannot delete clusters in the provisioning state. With this commit, the clean-up job will wait for no operation on clusters before deleting the resources.
Fixes: #940
> workflows: add wait for no operation for cleaning up GKE

- connectivity/suite.go
To mitigate the effects of bug
https://github.com/cilium/cilium/issues/17459, commit 7f84818 ("test: Run tests with UDP proxy redirections last") reordered the tests such that those with proxy redirections are executed last.
Commit 8c772b76d ("connectivity: Add policy test for name ports") however partially undid that, causing a new flake in CI. This commit moves those new L7 ingress tests to the end of the connectivity tests.
Related: https://github.com/cilium/cilium/issues/22529
Fixes: https://github.com/cilium/cilium-cli/pull/1028
cc @sayboras
> connectivity: Reorder L7 ingress connectivity tests

- .github/workflows/eks.yaml
We've been hitting the timeout in the master CI recently, probably because the connectivity tests are now longer:
- https://github.com/cilium/cilium-cli/actions/runs/3606335838/jobs/6077572819
- https://github.com/cilium/cilium-cli/actions/runs/3599598273/jobs/6063381447
- https://github.com/cilium/cilium-cli/actions/runs/3595665407/jobs/6055434191
Time to bump it.
> workflows: Bump timeout for EKS workflow

- .github/in-cluster-test-scripts/aks.sh
- .github/in-cluster-test-scripts/eks-tunnel.sh
- .github/in-cluster-test-scripts/eks.sh
- .github/in-cluster-test-scripts/external-workloads.sh
- .github/in-cluster-test-scripts/gke.sh
- .github/in-cluster-test-scripts/multicluster.sh
- .github/workflows/kind.yaml
A new `-collect-sysdump-on-failure` option was recently introduced in the cilium connectivity test command by Jibi to collect a sysdump every time a connectivity test case fails, immediately after the failure. That ensures we get the state as it was at the time of the failure and not as it is only at the end of the full workflows.
This flag was tested on the cilium/cilium AKS workflows and this commit now extends it to all workflows in cilium/cilium-cli.
> workflows: Collect sysdump immediately after test failures

- .github/workflows/externalworkloads.yaml
We [sometimes reach the 30min timeout](https://github.com/cilium/cilium-cli/actions/runs/3580207167) on the External Workload workflow. This commit bumps the timeout to 45min.
> workflows: Bump timeout for External Workload workflow

- .github/get-kubeconfig.sh
Merge latest changes from upstream
https://github.com/gravitational/teleport/blob/76d6dc82151c2ba977a119e69038a2f5bf6e8ef7/examples/k8s-auth/get-kubeconfig.sh for k8s 1.24 compatibility.
Fixes #1273
> .github: update get-kubeconfig.sh for k8s 1.24

- .github/workflows/aks-azure-ipam.yaml
- .github/workflows/aks-byocni.yaml
- .github/workflows/eks-tunnel.yaml
- .github/workflows/eks.yaml
- .github/workflows/externalworkloads.yaml
- .github/workflows/gke.yaml
- .github/workflows/kind.yaml
- .github/workflows/multicluster.yaml
https://github.com/cilium/cilium-cli/pull/1272 updated the default stable version installed by the Cilium from v1.12.2 to v1.12.4, but the CI is still using v1.12.2.
This pull request updates the CI.
Passing tests:
Fixes: https://github.com/cilium/cilium-cli/issues/1278.
> workflows: Test with Cilium v1.12.4

- sysdump/sysdump.go
Sample output:
🔍 Collecting sysdump with cilium-cli version: v0.12.11-13-g10617f1b, args: [sysdump]
🔮 Detected Cilium installation in namespace "kube-system"
🔍 Collecting Kubernetes nodes
> sysdump: Log detected Cilium namespace

- connectivity/check/context.go
- connectivity/check/features.go
- connectivity/suite.go
- connectivity/tests/encryption.go
- k8s/client.go
Please see commit msgs.
Example run - https://github.com/cilium/cilium/actions/runs/3573711857/jobs/6008107171.
> connectivity: Add encryption tests

- .github/dependabot.yml
- README.md
With the upcoming Cilium v1.13 release, Cilium v1.10 will no longer be maintained per the Cilium release policy [1]. cilium-cli v0.10 is only maintained for Cilium v1.10 compatibility, so mark it as unmaintained too.
[1] https://docs.cilium.io/en/v1.12/contributing/release/organization/
> README, dependabot: mark v0.10 branch as unmaintained

- sysdump/sysdump.go
- sysdump/sysdump_test.go
See commits for details.
I'll note that if we implemented https://github.com/cilium/cilium-cli/issues/1083 and failed CI on any warning, this sort of regression wouldn't happen.
Fixes: https://github.com/cilium/cilium-cli/issues/1289
Fixes: https://github.com/cilium/cilium-cli/pull/1132
cc @tommyp1ckles
> sysdump: Fix empty namespace error

- .github/workflows/aks-azure-ipam.yaml
- .github/workflows/aks-byocni.yaml
- .github/workflows/eks-tunnel.yaml
- .github/workflows/eks.yaml
- .github/workflows/externalworkloads.yaml
- .github/workflows/gke.yaml
- .github/workflows/go.yaml
- .github/workflows/kind.yaml
- .github/workflows/loki.yaml
- .github/workflows/multicluster.yaml
- .github/workflows/release.yaml
Currently, we use ubuntu-latest runners which currently points to
ubuntu-20.04, but will point to ubuntu-22.04 soon [1]
[1] https://github.com/actions/runner-images/issues/6399
In order to avoid future surprises and proactives check compatibility of
our workflows, pin the version to ubuntu-22.04 already.
> .github: pin ubuntu runners to 22.04

- connectivity/check/features.go
It's "disabled, not "Disabled".
Fixes: 976cf82fd ("connectivity: Add feature to detect tunneling mode")
Reported-by: Tobias Klauser <tobias@cilium.io>
Signed-off-by: Martynas Pumputis <m@lambda.lt>
> connectivity: Fix tunnel feature detection

- .github/workflows/aks-azure-ipam.yaml
- .github/workflows/aks-byocni.yaml
- .github/workflows/eks-tunnel.yaml
- .github/workflows/eks.yaml
- .github/workflows/externalworkloads.yaml
- .github/workflows/gke.yaml
- .github/workflows/images.yaml
- .github/workflows/multicluster.yaml
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Converted using:
sed -i \
'/::set-output/ {
s/::set-output name=/"/;
s/::/=/;
s/$/" >> $GITHUB_OUTPUT/;
}' \
.github/workflows/*.yaml
> .github: replace deprecated set-output commands

- connectivity/tests/encryption.go
- internal/utils/ctrlcreader.go
- k8s/client.go
- k8s/copy.go
- k8s/exec.go
This is a partial revert of commit 30310b18 ("connectivity, k8s, internal/utils: drop ExecInPodWithTTY and CtrlCReader").
Unfortunately, using the same context as StreamWithContext() to indicate a cancellation of a program running via Exec doesn't work as expected. From quick experimentation, it only closes a connection which doesn't necessarily send SIGTERM to a remote program. As a result, the tcpdump kept dangling in the encryption tests.
Bring back the ctrlreader, and use a separate context for it.
Signed-off-by: Martynas Pumputis <m@lambda.lt>
> k8s: Bring back TTY to Exec

- connectivity/tests/encryption.go
This commit fixes two issues:
* grep's "-P" is not available on busybox.
* In the direct routing mode, "ip r g $DST_POD_IP from $SRC_POD_IP" fails with "RTNETLINK answers: Network unreachable".
Fixes: 998ef8ab15e ("connectivity: Add encryption test")
Signed-off-by: Martynas Pumputis <m@lambda.lt>
> connectivity: Fix iface derivation in encrypt tests

- connectivity/check/check.go
- connectivity/check/context.go
- connectivity/tests/cidr.go
- connectivity/tests/client.go
- connectivity/tests/common.go
- connectivity/tests/encryption.go
- connectivity/tests/externalworkload.go
- connectivity/tests/host.go
- connectivity/tests/pod.go
- connectivity/tests/service.go
- connectivity/tests/world.go
- defaults/defaults.go
- internal/cli/cmd/connectivity.go
See commits for details.
The first two commits are preparatory refactoring, the third commit contains the implementation. Verbatim copy of the commit message:
connectivity: allow to specify connect and request timeout
These are used to set curl --max-time and --connect-timeout, and ping -w
and -W, respectively. The default values are 20s for --request-timeout
and 5s for --connect-timeout.
Example usage:
$ cilium connectivity test --request-timeout 5s --connect-timeout 2s
> connectivity: allow to specify maximum request and connect timeout

- hubble/relay.go
- hubble/ui.go
Avoid exposing Hubble Relay and UI to the network, restrict to localhost. After the patch:
```console
% ./cilium hubble port-forward
% ss -l -t 'sport = :4245'
State           Recv-Q          Send-Q                    Local Address:Port                     Peer Address:Port          Process
LISTEN          0               4096                          127.0.0.1:4245                          0.0.0.0:*
LISTEN          0               4096                              [::1]:4245                             [::]:*
```
and
```console
% ./cilium hubble ui port-forward
% ss -l -t 'sport = :12000'
State           Recv-Q          Send-Q                   Local Address:Port                        Peer Address:Port         Process
LISTEN          0               4096 …
```
> hubble: port-forward only to localhost

- clustermesh/clustermesh.go
- install/autodetect.go
- install/azure.go
- install/install.go
Some logs have 1 space after ℹ️ , causing mis-alignments in the logs (eg. `ℹ️Cilium will fully replace all functionalities of kube-proxy`):
This PR standardize the logs to 2 spaces after ℹ️ 
Signed-off-by: Benjamin Gentil <benjamin.gentil@infomaniak.com>
> all: fix spacing with ℹ️  logs

- internal/cli/cmd/version.go
This is similar to what kubectl offers (i.e. kubectl version --client). One benefit is to have faster response time if the current kubernetes context is not valid or no cilium installed.
Thanks to Shane O'Donnell for suggestion.
Testing was done locally as per below
```bash
$ ./cilium version --client       
cilium-cli: v0.12.8 compiled with go1.19.4 on linux/amd64
cilium image (default): v1.12.2
cilium image (stable): v1.12.5
$ ./cilium version --client=true 
cilium-cli: v0.12.8 compiled with go1.19.4 on linux/amd64
cilium image (default): v1.12.2
cilium image (stable): v1.12.5
$ ./cilium version         
cilium-cli: v0.12.8 compiled with go1.19.4 on linux/amd64
cilium image (default): v1.12.2
cilium image (stable): v1.12.5
cilium image …
```
> cli: Support client only in version sub-command

- hubble/relay.go
- hubble/ui.go
Before this patch, cilium hubble port-forward and cilium hubble ui would fail when the host didn't have IPv6 enabled.
After this patch we have:
```console
% ./cilium hubble port-forward
% ss -l -t 'sport = :4245'
State           Recv-Q          Send-Q                    Local Address:Port                     Peer Address:Port          Process
LISTEN          0               4096                          127.0.0.1:4245                          0.0.0.0:*
```
and
```console
% ./cilium hubble ui
% ss -l -t 'sport = :12000'
State           Recv-Q          Send-Q                   Local Address:Port                        Peer Address:Port         Process
LISTEN          0               4096                         127.0.0.1:entextxid                        0.0.0.0:*
```
Fix #1093
> hubble: port-forward only on IPv4

- hubble/hubble.go
- hubble/ui.go
- internal/cli/cmd/hubble.go
Signed-off-by: zufardhiyaulhaq <zufardhiyaulhaq@gmail.com>
open new PR because https://github.com/cilium/cilium-cli/pull/1313 accidentally closed.
add the flag --open-browser, When --open-browser is supplied as false, cilium hubble ui will not open the browser. The default is true which means cilium hubble ui will always open a browser to view the UI. (default true)
```
(⎈ |home-lab-kubernetes-01:kube-system) [31/12/22 | 8:04:58]
cilium-cli $ ./cilium hubble ui --open-browser=false
ℹ️  Hubble UI is available on "http://localhost:12000"
^C
(⎈ |home-lab-kubernetes-01:kube-system) [31/12/22 | 8:05:28]
cilium-cli $ ./cilium hubble ui 
ℹ️  Opening "http://localhost:12000" in your browser...
^C
```
Fixes #1312
> introduce --open-browser flag on cilium hubble UI

- connectivity/check/check.go
- connectivity/manifests/client-egress-l7-http-named-port.yaml
- connectivity/manifests/client-egress-l7-http.yaml
- connectivity/manifests/client-egress-to-fqdns-one-one-one-one.yaml
- connectivity/suite.go
- connectivity/tests/world.go
- internal/cli/cmd/connectivity.go
- internal/utils/template.go
A configurable domain allows us to run the PodToWord test in an environment where external traffic only allowed for specific domains. This also gives us the ability to swap the domain in test environments to better handle flaky tests.
> Make pod to world test configurable

- internal/cli/cmd/sysdump.go
- k8s/copy.go
- sysdump/client.go
- sysdump/defaults.go
- sysdump/sysdump.go
- sysdump/sysdump_test.go
If a user wants to get bugtool output while they are on unreliable network, it makes sense to increase retry count to make their experience better.
> Increase copy retries

- README.md
Note: #1324 should be merged before this one, so the tag points to the preparation commit.
> Prepare for v0.12.12 release

- .github/workflows/go.yaml
- .github/workflows/kind.yaml
- .github/workflows/multicluster.yaml
- .github/workflows/release.yaml
- Makefile
> go1.19.5 (released 2023-01-10) includes fixes to the compiler, the
> linker, and the crypto/x509, net/http, sync/atomic, and syscall
> packages. See the Go 1.19.5 milestone on our issue tracker for
> details.
Release milestone:
https://github.com/golang/go/issues?q=milestone%3AGo1.19.5+label%3ACherryPickApproved
Also update the docker base image used for release build to alpine 3.17.
> Update Go to 1.19.5

- connectivity/check/deployment.go
This will provision IPv6 services on K8s clusters on which IPv6 is enabled. Small step towards
https://github.com/cilium/cilium-cli/issues/1139.
> connectivity: Set PreferDualStack for test services

- .gitignore
- connectivity/manifests/allow-all-except-world-pre-v1.11.yaml
- connectivity/manifests/allow-all-except-world.yaml
- connectivity/manifests/client-egress-only-dns.yaml
- connectivity/manifests/client-egress-to-echo.yaml
- connectivity/manifests/client-egress-to-entities-world.yaml
- connectivity/manifests/client-egress-to-fqdns-one-one-one-one.yaml
When node-local-dns is deployed with local IP, 
policies fail to verify that the connection goes to 
node-local-dns. This change allows such DNS 
traffics in the connectivity test policy yamls.
Signed-off-by: eminaktas <eminaktas34@gmail.com>
> fix(connectivity): Add node-local-dns entitiy match for local ip usage case

- internal/cli/cmd/sysdump.go
- sysdump/sysdump.go
As reported at https://github.com/cilium/cilium-cli/issues/1079 the global `--namespace` flag is not honored in `sysdump` command. 
This PR honors the global `--namespace` flag in `sysdump` commad by making `--namespace` flag equivalent to the `--cilium-namespace` flag.
If both flags are set, then the  `--namespace` global flag comes with priority.
Closes https://github.com/cilium/cilium-cli/issues/1079
Signed-off-by: ChrsMark <chrismarkou92@gmail.com>
> Honor global namespace flag in sysdump command

- connectivity/tests/health.go
In some environments it is possible to use ds cilium with multiple containers (e.g. kube-rbac-proxy) in these cases the health tests do not work correctly.
For example:
```
⚠️ cilium-health probe failed: "a container name must be specified for pod agent-gtrg7, choose one of: [check-linux-kernel mount-cgroup clean-cilium-state cilium-agent kube-rbac-proxy]", stdout: {" '\x00' '\x00'}, retrying...
```
> [connectivity] add container name for health tests

- status/status.go
Before this patch, after `cilium install` we get
% ./cilium config view | grep enable-hubble
enable-hubble                              true
But
% cilium status | grep Hubble:
Hubble:         disabled
Because `cilium status` reports whether Hubble Relay is deployed.
> status: rename Hubble status to Hubble Relay

- clustermesh/clustermesh.go
When clustermesh-apiserver Pod is deployed on the IPv6 single-stack cluster, etcd fails to startup with the error like this.
```
invalid value "https://127.0.0.1:2379,https://a:1:0:3::fc75:2379" for flag -listen-client-urls: URL address does not have the form "host:port": https://a:1:0:3::fc75:2379
```
This happens because we don't put brackets around the IPv6 address. Fix deployment template to correctly handle that.
Related: cilium/cilium#22962
Signed-off-by: Marco Iorio <marco.iorio@isovalent.com>
> clustermesh: Add missing brackets of etcd option

- connectivity/check/deployment.go
Follow-up of cilium/cilium#23298, adding the new clustermesh service.cilium.io/global annotation alongside the previous one.
Signed-off-by: Marco Iorio <marco.iorio@isovalent.com>
> clustermesh: adapt global service annotations

- go.mod
- go.sum
- vendor/github.com/cilium/hubble/pkg/printer/color.go
- vendor/github.com/cilium/hubble/pkg/printer/formatter.go
- vendor/github.com/cilium/hubble/pkg/printer/options.go
- vendor/github.com/cilium/hubble/pkg/printer/printer.go
- vendor/modules.txt
> go.mod, vendor: update github.com/cilium/hubble to v0.11.1

- .github/in-cluster-test-scripts/aks.sh
- .github/in-cluster-test-scripts/eks-tunnel.sh
- .github/in-cluster-test-scripts/eks.sh
- .github/in-cluster-test-scripts/external-workloads.sh
- .github/in-cluster-test-scripts/gke.sh
- .github/in-cluster-test-scripts/multicluster.sh
Follows https://github.com/cilium/cilium/pull/23103, quoting its commit message:
> With the configurable --external-target flag we are configuring different targets per cloud provider. Targets were chosen to be the least hops from the clusters. They were determined by experimenting with connection times from cloud providers. Splitting targets also has the advantage of not overloading a single target.
/cc @brlbil
> ci: use cloud provider specific external target for pod-to-world tests

- clustermesh/clustermesh.go
- internal/cli/cmd/clustermesh.go
- internal/cli/cmd/status.go
- status/k8s.go
- status/status.go
- feat: add json output for clustermesh status
- feat: add json output for status
- feat: downcase json export fields for status
- feat: downcase json export fields for clustermesh status
Fixes: #956
> Add JSON status (fix #956)

- internal/helm/helm.go
We did all the work to support this, but somehow I missed an important little detail. Namely, that it doesn't work at all.
So, *correctly* support parsing when a single file generates multiple values in Helm.
Fixes: https://github.com/cilium/cilium/issues/23315
> install: fix support for multi-object files

- connectivity/manifests/echo-ingress-icmp-deny.yaml
- connectivity/manifests/echo-ingress-icmp.yaml
This PR expands the ICMP-related netpols used for the connectivity tests to allow both IPv4 ICMP Echo Requests (type 8) and IPV6 ICMP Echo Requests (type 128), to ensure that the tests run correctly also on IPv6-only clusters.
> connectivity tests: support IPv6 in ICMP-related netpols

- connectivity/suite.go
Global NodePort services are not supported when they are managed by iptables/ipvs, since they do not know about remote endpoints. Hence, let's skip the related connectivity tests when running in multicluster mode and KPR NodePort support is disabled, to prevent spurious failures.
Related: cilium/cilium#23128
Related: cilium/cilium#23266
Fixes: #1352
> connectivity: skip nodeport tests with clustermesh if KPR is disabled

- install/install.go
This is to make sure that the shared ingress service can be created if
required.
Reported-by: Xiao Song
> ingress: Create Ingress Service if required

- install/uninstall.go
Wait for the deletion of agent DaemonSet before deleting other resources.
This allows the agent to clean up cilium annotations added to the node.
Related PR: https://github.com/cilium/cilium/pull/23772
> Wait for deletion of agent DaemonSet before deleting other resources.

- defaults/defaults.go
The timeouts are extensively used in connectivity tests which checks whether a policy has denied a connection. Obviously, this leads to waiting 20s.
Before (with the upcoming IPv6 connectivity tests):
./cilium connectivity test  6.99s user 1.42s system 1% cpu 11:48.72
total
After:
./cilium connectivity test  7.06s user 1.40s system 2% cpu 6:14.97
total
> defaults: Lower connectivity timeouts

- connectivity/check/policy.go
Do not set 'mod' to 'false' after it has been set to 'true' in order to wait for policy change even if the last applied policy did not change anything.
> test: Wait for policy change if any policy changed

- status/k8s.go
- status/k8s_test.go
There are a few additional states that indicate a Deployment or DaemonSet is progressing and not yet fully deployed:
- ObservedGeneration < Generation means the relevant controller has not yet observed the changes
- UpdatedReplicas / UpdatedNumberScheduled too small means that the update has not fully rolled out.
Fixes: #413 which was somehow reverted in a refactor
> status: detect when DaemonSets and Deployments are rolling out

- connectivity/check/deployment.go
- connectivity/check/peer.go
- connectivity/check/utils.go
- connectivity/suite.go
- connectivity/tests/cidr.go
- connectivity/tests/dummy.go
- connectivity/tests/health.go
- connectivity/tests/host.go
- connectivity/tests/service.go
- connectivity/tests/world.go
This PR changes the behavior of `IPFamilyNone` (now renamed to `IPFamilyAny` for consistency) to allow both IPv4 and IPv6 addresses, and switches the "waitForPodDNS" check to use it is order to prevent issues on IPv6-only clusters.
> connectivity tests: fix issue on IPv6-only clusters

- install/helm.go
Since https://github.com/cilium/cilium/pull/19401 (to be released in v1.14) there's no need to **_disable_** the `L7 proxy` when WireGuard is **_enabled_** on the > v1.13 Cilium (the relevant log message L7 proxy disabled due to Wireguard encryption).
> As a bonus, the unnecessary log/WARN `Wireguard does not support node encryption yet` has also been removed.
Fixes #1405 
cc: @brb 
Signed-off-by: [Pratyay Banerjee](mailto:putubanerjee23@gmail.com)
> enabled l7Proxy & removed err.log message for WireGuard

- clustermesh/clustermesh.go
With helm, etcd uses v3.5.4.
There is no reason to separate cilium-cli, so we will match them.
https://github.com/cilium/cilium/blob/e8104547227af8fa53ed197e13f5879957d8297c/install/kubernetes/cilium/values.yaml#L2288
The container image in v3.5.4 of etcd is multi-platform.
I am using EKS, which is a managed control plane, so I am running on amd64.
Therefore, when using EKS, there are many configurations where the control plane is amd64, but the node runs on arm64.
Currently, the `-arm64` suffix of etcd only refers to the architecture of the control plane, so it does not cover many usecases.
However, upgrading etcd will solve all the problems.
```
Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.6-eks-48e63af", GitCommit:"9f22d4ae876173884749c0701f01340879ab3f95", …
```
> clustermesh: update etcd version to v3.5.4

- hubble/hubble.go
So far when enabling Hubble metrics in `hubble enable` command, e.g.:
```
cilium hubble enable --helm-set-string=hubble.metrics.enabled="{http,dns,drop,tcp,flow,icmp,port-distribution}"
```
the CLI created a hubble-metrics service, but didn't add a hubble-metrics port to Cilium daemonset. Then Hubble metrics were exposed by Cilium, but the hubble-metrics Endpoints object wasn't populated with the Cilium pod IPs. Prometheus scrape configs often rely on Endpoints objects, so this results in Hubble metrics not being scraped.
This patch fixes that by patching the Cilium agent daemonset with a hubble-metrics port if a metrics service is created in `hubble enable` command.
It's a rough patch and it assumes using the default Hubble metrics port (9965), and Cilium agent name ("cilium"). A proper …
> hubble: Patch Cilium DaemonSet with hubble-metrics port

- internal/cli/cmd/sysdump.go
- sysdump/constants.go
- sysdump/defaults.go
- sysdump/sysdump.go
- sysdump/sysdump_test.go
Scrape cpu and heap profiles from the Cilium agents by default when gathering sysdump.
> Add profiling data(cpu/heap) of cilium agent to sysdump.

- .github/workflows/release.yaml
actions/create-release is no longer maintained. Also, uploading release artifacts using skx/github-action-publish-binaries is a bit of a lottery and sometimes repeatedly fails.
Switch to softprops/action-gh-release instead, which combines creating a release with uploading release artifacts and allows to trigger the release notes auto-generation.
Also, the action seems maintained and is suggested as a replacement for actions/create-release, see
https://github.com/actions/upload-release-asset#github-action---releases-api
> .github/workflows: use softprops/action-gh-release in release workflow

- .github/workflows/release.yaml
Before the release would be named "Release refs/tags/v0.13.1", now it's named "Release v0.13.1".
Fixes: 34db9d12626a (".github/workflows: use softprops/action-gh-release in release workflow")
> .github/workflows: use tag name instead of fully-formed ref in release name

- RELEASE.md
We no longer need to hit the button, the action generates the release notes for us :sparkle:
See https://github.com/cilium/cilium-cli/pull/1433
> RELEASE.md: adjust release instructions after change to new release action

- install/helm.go
Replace logf error wrap directive with string.
Fixes ugly logs like:
```
⚠️ Unable to list kubernetes api resources, try --api-versions if needed: %!w(*fmt.wrapError=&{failed to list api resources: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request 0x14000e26030})
```
> helm: fix incorrect log error formatting directive.

- install/install.go
Use Helm chart to generate resource quotas to ensure that they don't diverge between Helm and cilium-cli.
> install: Generate resource quotas from Helm chart

- connectivity/check/check.go
- connectivity/check/deployment.go
- internal/cli/cmd/connectivity.go
The connectivity test pods will be restricted to nodes matching labels given in the `--node-selector` flag.
Usage:
$ kubectl get nodes
NAME                 STATUS   ROLES           AGE   VERSION
kind-control-plane   Ready    control-plane   15m   v1.25.3
kind-worker          Ready    <none>          15m   v1.25.3
kind-worker2         Ready    <none>          15m   v1.25.3
kind-worker3         Ready    <none>          15m   v1.25.3
kind-worker4         Ready    <none>          15m   v1.25.3
$ kubectl label nodes kind-worker{2,3} connectivity.cilium.io/test=true
$ cilium connectivity test --node-selector connectivity.cilium.io/test=true
[...]
✅ All 32 tests (261 actions) successful, 2 tests skipped, 1 scenarios skipped.
$ kubectl get pods -n cilium-test -o wide
NAME …
> connectivity: allow to restrict connectivity test pods using nodeSelector

- go.mod
- install/helm.go
- install/helm_test.go
- install/testdata/kind.yaml
Break generateManifests() into smaller functions without changing the logic to make it easier to reuse and unit test.
> refactor: Break generateManifests() into smaller functions

- clustermesh/clustermesh.go
This PR fixes an incorrect volume mount specification for the init container of the clustermesh-apiserver deployment created through `cilium clustermesh enable`.
> clustermesh: correctly mount the etcd data dir in the init container

- connectivity/check/policy.go
- connectivity/manifests/client-egress-l7-http-matchheader-secret.yaml
- connectivity/suite.go
- connectivity/tests/common.go
- connectivity/tests/pod.go
- defaults/defaults.go
This adds a test for the L7 policy to add/replace a HTTP header in a request. It does this by sending a request to a new endpoint that required an auth header, which will succeed if injected from a secret.
This came up while needing a test for https://github.com/cilium/cilium/issues/24020 and it will work against the current Cilium version where it was previously not tested in Ginkgo.
> Add a l7 header replace test

- .github/workflows/kind.yaml
- defaults/defaults.go
- install/autodetect.go
- install/install.go
- install/uninstall.go
- internal/cli/cmd/cmd.go
- internal/cli/cmd/install.go
- internal/helm/helm.go
- internal/helm/helm_test.go
- k8s/client.go
please review commit by commit. there are 2 commits:
- refactoring a bit to support helm-based install / uninstall commands.
- implement install / uninstall commands.
let's implement other commands in separate PRs to keep the PR size reasonable.
ref: https://github.com/cilium/cilium-cli/issues/1396
> Add Helm-based install / uninstall commands

- defaults/defaults.go
- internal/cli/cmd/install.go
- Fix quotation for Cilium schedule affinity
- install: Support --nodes-without-cilium in Helm install mode
> install: Support --nodes-without-cilium in Helm install mode

- install/install.go
- internal/cli/cmd/install.go
- --dry-run flag writes resources to stdout without actually installing them.
- --dry-run-helm-values flag writes non-default Helm values to stdout without performing the actual installation.
> helm mode install: Add --dry-run / --dry-run-helm-values flags

- connectivity/check/context.go
- connectivity/check/features.go
- connectivity/suite.go
Make detected Cilium Agent version available for feature detection and use it instead of trying to detect Cilium version from the agent image reference. This helps avoid failures like this when the image tag is not a semantic version (in this case image tag is "test"):
```
connectivity test failed: unable to determine if KNP feature is enabled: failed to parse Cilium version test to semver
```
Cilium agent version was already detected, this PR moves the detection a bit earlier to make it available for feature detection.
Fixes: #1470
Fixes: #1507
> connectivity: Make detected Cilium Agent version available for feature detection
